/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneenti.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import it.servizidigitali.gestioneenti.service.persistence.EnteServizioPK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EnteServizio service. Represents a row in the &quot;ente_servizio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.gestioneenti.model.impl.EnteServizioModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.gestioneenti.model.impl.EnteServizioImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EnteServizio
 * @generated
 */
@ProviderType
public interface EnteServizioModel
	extends BaseModel<EnteServizio>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ente servizio model instance should use the {@link EnteServizio} interface instead.
	 */

	/**
	 * Returns the primary key of this ente servizio.
	 *
	 * @return the primary key of this ente servizio
	 */
	public EnteServizioPK getPrimaryKey();

	/**
	 * Sets the primary key of this ente servizio.
	 *
	 * @param primaryKey the primary key of this ente servizio
	 */
	public void setPrimaryKey(EnteServizioPK primaryKey);

	/**
	 * Returns the uuid of this ente servizio.
	 *
	 * @return the uuid of this ente servizio
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ente servizio.
	 *
	 * @param uuid the uuid of this ente servizio
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the organization ID of this ente servizio.
	 *
	 * @return the organization ID of this ente servizio
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this ente servizio.
	 *
	 * @param organizationId the organization ID of this ente servizio
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the servizio ID of this ente servizio.
	 *
	 * @return the servizio ID of this ente servizio
	 */
	public long getServizioId();

	/**
	 * Sets the servizio ID of this ente servizio.
	 *
	 * @param servizioId the servizio ID of this ente servizio
	 */
	public void setServizioId(long servizioId);

	/**
	 * Returns the group ID of this ente servizio.
	 *
	 * @return the group ID of this ente servizio
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ente servizio.
	 *
	 * @param groupId the group ID of this ente servizio
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ente servizio.
	 *
	 * @return the company ID of this ente servizio
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ente servizio.
	 *
	 * @param companyId the company ID of this ente servizio
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ente servizio.
	 *
	 * @return the user ID of this ente servizio
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ente servizio.
	 *
	 * @param userId the user ID of this ente servizio
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ente servizio.
	 *
	 * @return the user uuid of this ente servizio
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ente servizio.
	 *
	 * @param userUuid the user uuid of this ente servizio
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ente servizio.
	 *
	 * @return the user name of this ente servizio
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ente servizio.
	 *
	 * @param userName the user name of this ente servizio
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ente servizio.
	 *
	 * @return the create date of this ente servizio
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ente servizio.
	 *
	 * @param createDate the create date of this ente servizio
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ente servizio.
	 *
	 * @return the modified date of this ente servizio
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ente servizio.
	 *
	 * @param modifiedDate the modified date of this ente servizio
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the uri of this ente servizio.
	 *
	 * @return the uri of this ente servizio
	 */
	@AutoEscape
	public String getUri();

	/**
	 * Sets the uri of this ente servizio.
	 *
	 * @param uri the uri of this ente servizio
	 */
	public void setUri(String uri);

	/**
	 * Returns the uri guest of this ente servizio.
	 *
	 * @return the uri guest of this ente servizio
	 */
	@AutoEscape
	public String getUriGuest();

	/**
	 * Sets the uri guest of this ente servizio.
	 *
	 * @param uriGuest the uri guest of this ente servizio
	 */
	public void setUriGuest(String uriGuest);

	/**
	 * Returns the uri scheda of this ente servizio.
	 *
	 * @return the uri scheda of this ente servizio
	 */
	@AutoEscape
	public String getUriScheda();

	/**
	 * Sets the uri scheda of this ente servizio.
	 *
	 * @param uriScheda the uri scheda of this ente servizio
	 */
	public void setUriScheda(String uriScheda);

	/**
	 * Returns the autenticazione of this ente servizio.
	 *
	 * @return the autenticazione of this ente servizio
	 */
	public boolean getAutenticazione();

	/**
	 * Returns <code>true</code> if this ente servizio is autenticazione.
	 *
	 * @return <code>true</code> if this ente servizio is autenticazione; <code>false</code> otherwise
	 */
	public boolean isAutenticazione();

	/**
	 * Sets whether this ente servizio is autenticazione.
	 *
	 * @param autenticazione the autenticazione of this ente servizio
	 */
	public void setAutenticazione(boolean autenticazione);

	/**
	 * Returns the data inizio attivazione of this ente servizio.
	 *
	 * @return the data inizio attivazione of this ente servizio
	 */
	public Date getDataInizioAttivazione();

	/**
	 * Sets the data inizio attivazione of this ente servizio.
	 *
	 * @param dataInizioAttivazione the data inizio attivazione of this ente servizio
	 */
	public void setDataInizioAttivazione(Date dataInizioAttivazione);

	/**
	 * Returns the data fine attivazione of this ente servizio.
	 *
	 * @return the data fine attivazione of this ente servizio
	 */
	public Date getDataFineAttivazione();

	/**
	 * Sets the data fine attivazione of this ente servizio.
	 *
	 * @param dataFineAttivazione the data fine attivazione of this ente servizio
	 */
	public void setDataFineAttivazione(Date dataFineAttivazione);

	/**
	 * Returns the cittadino of this ente servizio.
	 *
	 * @return the cittadino of this ente servizio
	 */
	public boolean getCittadino();

	/**
	 * Returns <code>true</code> if this ente servizio is cittadino.
	 *
	 * @return <code>true</code> if this ente servizio is cittadino; <code>false</code> otherwise
	 */
	public boolean isCittadino();

	/**
	 * Sets whether this ente servizio is cittadino.
	 *
	 * @param cittadino the cittadino of this ente servizio
	 */
	public void setCittadino(boolean cittadino);

	/**
	 * Returns the azienda of this ente servizio.
	 *
	 * @return the azienda of this ente servizio
	 */
	public boolean getAzienda();

	/**
	 * Returns <code>true</code> if this ente servizio is azienda.
	 *
	 * @return <code>true</code> if this ente servizio is azienda; <code>false</code> otherwise
	 */
	public boolean isAzienda();

	/**
	 * Sets whether this ente servizio is azienda.
	 *
	 * @param azienda the azienda of this ente servizio
	 */
	public void setAzienda(boolean azienda);

	/**
	 * Returns the delega of this ente servizio.
	 *
	 * @return the delega of this ente servizio
	 */
	public boolean getDelega();

	/**
	 * Returns <code>true</code> if this ente servizio is delega.
	 *
	 * @return <code>true</code> if this ente servizio is delega; <code>false</code> otherwise
	 */
	public boolean isDelega();

	/**
	 * Sets whether this ente servizio is delega.
	 *
	 * @param delega the delega of this ente servizio
	 */
	public void setDelega(boolean delega);

	/**
	 * Returns the chatbot of this ente servizio.
	 *
	 * @return the chatbot of this ente servizio
	 */
	public boolean getChatbot();

	/**
	 * Returns <code>true</code> if this ente servizio is chatbot.
	 *
	 * @return <code>true</code> if this ente servizio is chatbot; <code>false</code> otherwise
	 */
	public boolean isChatbot();

	/**
	 * Sets whether this ente servizio is chatbot.
	 *
	 * @param chatbot the chatbot of this ente servizio
	 */
	public void setChatbot(boolean chatbot);

	/**
	 * Returns the prenotabile of this ente servizio.
	 *
	 * @return the prenotabile of this ente servizio
	 */
	public boolean getPrenotabile();

	/**
	 * Returns <code>true</code> if this ente servizio is prenotabile.
	 *
	 * @return <code>true</code> if this ente servizio is prenotabile; <code>false</code> otherwise
	 */
	public boolean isPrenotabile();

	/**
	 * Sets whether this ente servizio is prenotabile.
	 *
	 * @param prenotabile the prenotabile of this ente servizio
	 */
	public void setPrenotabile(boolean prenotabile);

	/**
	 * Returns the privacy delega of this ente servizio.
	 *
	 * @return the privacy delega of this ente servizio
	 */
	public boolean getPrivacyDelega();

	/**
	 * Returns <code>true</code> if this ente servizio is privacy delega.
	 *
	 * @return <code>true</code> if this ente servizio is privacy delega; <code>false</code> otherwise
	 */
	public boolean isPrivacyDelega();

	/**
	 * Sets whether this ente servizio is privacy delega.
	 *
	 * @param privacyDelega the privacy delega of this ente servizio
	 */
	public void setPrivacyDelega(boolean privacyDelega);

	/**
	 * Returns the allegato delega of this ente servizio.
	 *
	 * @return the allegato delega of this ente servizio
	 */
	public boolean getAllegatoDelega();

	/**
	 * Returns <code>true</code> if this ente servizio is allegato delega.
	 *
	 * @return <code>true</code> if this ente servizio is allegato delega; <code>false</code> otherwise
	 */
	public boolean isAllegatoDelega();

	/**
	 * Sets whether this ente servizio is allegato delega.
	 *
	 * @param allegatoDelega the allegato delega of this ente servizio
	 */
	public void setAllegatoDelega(boolean allegatoDelega);

	/**
	 * Returns the timbro certificato of this ente servizio.
	 *
	 * @return the timbro certificato of this ente servizio
	 */
	public boolean getTimbroCertificato();

	/**
	 * Returns <code>true</code> if this ente servizio is timbro certificato.
	 *
	 * @return <code>true</code> if this ente servizio is timbro certificato; <code>false</code> otherwise
	 */
	public boolean isTimbroCertificato();

	/**
	 * Sets whether this ente servizio is timbro certificato.
	 *
	 * @param timbroCertificato the timbro certificato of this ente servizio
	 */
	public void setTimbroCertificato(boolean timbroCertificato);

	/**
	 * Returns the isee inps of this ente servizio.
	 *
	 * @return the isee inps of this ente servizio
	 */
	public boolean getIseeInps();

	/**
	 * Returns <code>true</code> if this ente servizio is isee inps.
	 *
	 * @return <code>true</code> if this ente servizio is isee inps; <code>false</code> otherwise
	 */
	public boolean isIseeInps();

	/**
	 * Sets whether this ente servizio is isee inps.
	 *
	 * @param iseeInps the isee inps of this ente servizio
	 */
	public void setIseeInps(boolean iseeInps);

	/**
	 * Returns the attivo of this ente servizio.
	 *
	 * @return the attivo of this ente servizio
	 */
	public boolean getAttivo();

	/**
	 * Returns <code>true</code> if this ente servizio is attivo.
	 *
	 * @return <code>true</code> if this ente servizio is attivo; <code>false</code> otherwise
	 */
	public boolean isAttivo();

	/**
	 * Sets whether this ente servizio is attivo.
	 *
	 * @param attivo the attivo of this ente servizio
	 */
	public void setAttivo(boolean attivo);

	@Override
	public EnteServizio cloneWithOriginalValues();

}