/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.scrivaniaoperatore.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import it.servizidigitali.scrivaniaoperatore.model.AttivitaRichiesta;
import it.servizidigitali.scrivaniaoperatore.service.AttivitaRichiestaLocalService;
import it.servizidigitali.scrivaniaoperatore.service.AttivitaRichiestaLocalServiceUtil;
import it.servizidigitali.scrivaniaoperatore.service.persistence.AllegatoRichiestaPersistence;
import it.servizidigitali.scrivaniaoperatore.service.persistence.AttivitaRichiestaPersistence;
import it.servizidigitali.scrivaniaoperatore.service.persistence.CommentoRichiestaPersistence;
import it.servizidigitali.scrivaniaoperatore.service.persistence.IstanzaFormPersistence;
import it.servizidigitali.scrivaniaoperatore.service.persistence.RichiestaFinder;
import it.servizidigitali.scrivaniaoperatore.service.persistence.RichiestaPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the attivita richiesta local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.servizidigitali.scrivaniaoperatore.service.impl.AttivitaRichiestaLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see it.servizidigitali.scrivaniaoperatore.service.impl.AttivitaRichiestaLocalServiceImpl
 * @generated
 */
public abstract class AttivitaRichiestaLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, AttivitaRichiestaLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AttivitaRichiestaLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AttivitaRichiestaLocalServiceUtil</code>.
	 */

	/**
	 * Adds the attivita richiesta to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AttivitaRichiestaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param attivitaRichiesta the attivita richiesta
	 * @return the attivita richiesta that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AttivitaRichiesta addAttivitaRichiesta(
		AttivitaRichiesta attivitaRichiesta) {

		attivitaRichiesta.setNew(true);

		return attivitaRichiestaPersistence.update(attivitaRichiesta);
	}

	/**
	 * Creates a new attivita richiesta with the primary key. Does not add the attivita richiesta to the database.
	 *
	 * @param attivitaRichiestaId the primary key for the new attivita richiesta
	 * @return the new attivita richiesta
	 */
	@Override
	@Transactional(enabled = false)
	public AttivitaRichiesta createAttivitaRichiesta(long attivitaRichiestaId) {
		return attivitaRichiestaPersistence.create(attivitaRichiestaId);
	}

	/**
	 * Deletes the attivita richiesta with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AttivitaRichiestaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param attivitaRichiestaId the primary key of the attivita richiesta
	 * @return the attivita richiesta that was removed
	 * @throws PortalException if a attivita richiesta with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AttivitaRichiesta deleteAttivitaRichiesta(long attivitaRichiestaId)
		throws PortalException {

		return attivitaRichiestaPersistence.remove(attivitaRichiestaId);
	}

	/**
	 * Deletes the attivita richiesta from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AttivitaRichiestaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param attivitaRichiesta the attivita richiesta
	 * @return the attivita richiesta that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AttivitaRichiesta deleteAttivitaRichiesta(
		AttivitaRichiesta attivitaRichiesta) {

		return attivitaRichiestaPersistence.remove(attivitaRichiesta);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return attivitaRichiestaPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AttivitaRichiesta.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return attivitaRichiestaPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.scrivaniaoperatore.model.impl.AttivitaRichiestaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return attivitaRichiestaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.scrivaniaoperatore.model.impl.AttivitaRichiestaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return attivitaRichiestaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return attivitaRichiestaPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return attivitaRichiestaPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AttivitaRichiesta fetchAttivitaRichiesta(long attivitaRichiestaId) {
		return attivitaRichiestaPersistence.fetchByPrimaryKey(
			attivitaRichiestaId);
	}

	/**
	 * Returns the attivita richiesta matching the UUID and group.
	 *
	 * @param uuid the attivita richiesta's UUID
	 * @param groupId the primary key of the group
	 * @return the matching attivita richiesta, or <code>null</code> if a matching attivita richiesta could not be found
	 */
	@Override
	public AttivitaRichiesta fetchAttivitaRichiestaByUuidAndGroupId(
		String uuid, long groupId) {

		return attivitaRichiestaPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the attivita richiesta with the primary key.
	 *
	 * @param attivitaRichiestaId the primary key of the attivita richiesta
	 * @return the attivita richiesta
	 * @throws PortalException if a attivita richiesta with the primary key could not be found
	 */
	@Override
	public AttivitaRichiesta getAttivitaRichiesta(long attivitaRichiestaId)
		throws PortalException {

		return attivitaRichiestaPersistence.findByPrimaryKey(
			attivitaRichiestaId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			attivitaRichiestaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AttivitaRichiesta.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("attivitaRichiestaId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			attivitaRichiestaLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AttivitaRichiesta.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"attivitaRichiestaId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			attivitaRichiestaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AttivitaRichiesta.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("attivitaRichiestaId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<AttivitaRichiesta>() {

				@Override
				public void performAction(AttivitaRichiesta attivitaRichiesta)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, attivitaRichiesta);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(AttivitaRichiesta.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return attivitaRichiestaPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return attivitaRichiestaLocalService.deleteAttivitaRichiesta(
			(AttivitaRichiesta)persistedModel);
	}

	@Override
	public BasePersistence<AttivitaRichiesta> getBasePersistence() {
		return attivitaRichiestaPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return attivitaRichiestaPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the attivita richiestas matching the UUID and company.
	 *
	 * @param uuid the UUID of the attivita richiestas
	 * @param companyId the primary key of the company
	 * @return the matching attivita richiestas, or an empty list if no matches were found
	 */
	@Override
	public List<AttivitaRichiesta> getAttivitaRichiestasByUuidAndCompanyId(
		String uuid, long companyId) {

		return attivitaRichiestaPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of attivita richiestas matching the UUID and company.
	 *
	 * @param uuid the UUID of the attivita richiestas
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of attivita richiestas
	 * @param end the upper bound of the range of attivita richiestas (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching attivita richiestas, or an empty list if no matches were found
	 */
	@Override
	public List<AttivitaRichiesta> getAttivitaRichiestasByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<AttivitaRichiesta> orderByComparator) {

		return attivitaRichiestaPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the attivita richiesta matching the UUID and group.
	 *
	 * @param uuid the attivita richiesta's UUID
	 * @param groupId the primary key of the group
	 * @return the matching attivita richiesta
	 * @throws PortalException if a matching attivita richiesta could not be found
	 */
	@Override
	public AttivitaRichiesta getAttivitaRichiestaByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return attivitaRichiestaPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the attivita richiestas.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.scrivaniaoperatore.model.impl.AttivitaRichiestaModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of attivita richiestas
	 * @param end the upper bound of the range of attivita richiestas (not inclusive)
	 * @return the range of attivita richiestas
	 */
	@Override
	public List<AttivitaRichiesta> getAttivitaRichiestas(int start, int end) {
		return attivitaRichiestaPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of attivita richiestas.
	 *
	 * @return the number of attivita richiestas
	 */
	@Override
	public int getAttivitaRichiestasCount() {
		return attivitaRichiestaPersistence.countAll();
	}

	/**
	 * Updates the attivita richiesta in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AttivitaRichiestaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param attivitaRichiesta the attivita richiesta
	 * @return the attivita richiesta that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AttivitaRichiesta updateAttivitaRichiesta(
		AttivitaRichiesta attivitaRichiesta) {

		return attivitaRichiestaPersistence.update(attivitaRichiesta);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AttivitaRichiestaLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		attivitaRichiestaLocalService = (AttivitaRichiestaLocalService)aopProxy;

		_setLocalServiceUtilService(attivitaRichiestaLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AttivitaRichiestaLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AttivitaRichiesta.class;
	}

	protected String getModelClassName() {
		return AttivitaRichiesta.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				attivitaRichiestaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AttivitaRichiestaLocalService attivitaRichiestaLocalService) {

		try {
			Field field =
				AttivitaRichiestaLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, attivitaRichiestaLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AllegatoRichiestaPersistence allegatoRichiestaPersistence;

	protected AttivitaRichiestaLocalService attivitaRichiestaLocalService;

	@Reference
	protected AttivitaRichiestaPersistence attivitaRichiestaPersistence;

	@Reference
	protected CommentoRichiestaPersistence commentoRichiestaPersistence;

	@Reference
	protected IstanzaFormPersistence istanzaFormPersistence;

	@Reference
	protected RichiestaPersistence richiestaPersistence;

	@Reference
	protected RichiestaFinder richiestaFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}