/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.scrivaniaoperatore.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import it.servizidigitali.scrivaniaoperatore.model.DestinazioneUsoServizioEnte;
import it.servizidigitali.scrivaniaoperatore.service.DestinazioneUsoServizioEnteLocalService;
import it.servizidigitali.scrivaniaoperatore.service.DestinazioneUsoServizioEnteLocalServiceUtil;
import it.servizidigitali.scrivaniaoperatore.service.persistence.AllegatoRichiestaPersistence;
import it.servizidigitali.scrivaniaoperatore.service.persistence.AttivitaRichiestaPersistence;
import it.servizidigitali.scrivaniaoperatore.service.persistence.CommentoRichiestaPersistence;
import it.servizidigitali.scrivaniaoperatore.service.persistence.DestinazioneUsoFinder;
import it.servizidigitali.scrivaniaoperatore.service.persistence.DestinazioneUsoPersistence;
import it.servizidigitali.scrivaniaoperatore.service.persistence.DestinazioneUsoServizioEntePK;
import it.servizidigitali.scrivaniaoperatore.service.persistence.DestinazioneUsoServizioEntePersistence;
import it.servizidigitali.scrivaniaoperatore.service.persistence.IstanzaFormPersistence;
import it.servizidigitali.scrivaniaoperatore.service.persistence.RichiestaFinder;
import it.servizidigitali.scrivaniaoperatore.service.persistence.RichiestaPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the destinazione uso servizio ente local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.servizidigitali.scrivaniaoperatore.service.impl.DestinazioneUsoServizioEnteLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see it.servizidigitali.scrivaniaoperatore.service.impl.DestinazioneUsoServizioEnteLocalServiceImpl
 * @generated
 */
public abstract class DestinazioneUsoServizioEnteLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, DestinazioneUsoServizioEnteLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DestinazioneUsoServizioEnteLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DestinazioneUsoServizioEnteLocalServiceUtil</code>.
	 */

	/**
	 * Adds the destinazione uso servizio ente to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DestinazioneUsoServizioEnteLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param destinazioneUsoServizioEnte the destinazione uso servizio ente
	 * @return the destinazione uso servizio ente that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DestinazioneUsoServizioEnte addDestinazioneUsoServizioEnte(
		DestinazioneUsoServizioEnte destinazioneUsoServizioEnte) {

		destinazioneUsoServizioEnte.setNew(true);

		return destinazioneUsoServizioEntePersistence.update(
			destinazioneUsoServizioEnte);
	}

	/**
	 * Creates a new destinazione uso servizio ente with the primary key. Does not add the destinazione uso servizio ente to the database.
	 *
	 * @param destinazioneUsoServizioEntePK the primary key for the new destinazione uso servizio ente
	 * @return the new destinazione uso servizio ente
	 */
	@Override
	@Transactional(enabled = false)
	public DestinazioneUsoServizioEnte createDestinazioneUsoServizioEnte(
		DestinazioneUsoServizioEntePK destinazioneUsoServizioEntePK) {

		return destinazioneUsoServizioEntePersistence.create(
			destinazioneUsoServizioEntePK);
	}

	/**
	 * Deletes the destinazione uso servizio ente with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DestinazioneUsoServizioEnteLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param destinazioneUsoServizioEntePK the primary key of the destinazione uso servizio ente
	 * @return the destinazione uso servizio ente that was removed
	 * @throws PortalException if a destinazione uso servizio ente with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DestinazioneUsoServizioEnte deleteDestinazioneUsoServizioEnte(
			DestinazioneUsoServizioEntePK destinazioneUsoServizioEntePK)
		throws PortalException {

		return destinazioneUsoServizioEntePersistence.remove(
			destinazioneUsoServizioEntePK);
	}

	/**
	 * Deletes the destinazione uso servizio ente from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DestinazioneUsoServizioEnteLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param destinazioneUsoServizioEnte the destinazione uso servizio ente
	 * @return the destinazione uso servizio ente that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DestinazioneUsoServizioEnte deleteDestinazioneUsoServizioEnte(
		DestinazioneUsoServizioEnte destinazioneUsoServizioEnte) {

		return destinazioneUsoServizioEntePersistence.remove(
			destinazioneUsoServizioEnte);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return destinazioneUsoServizioEntePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DestinazioneUsoServizioEnte.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return destinazioneUsoServizioEntePersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.scrivaniaoperatore.model.impl.DestinazioneUsoServizioEnteModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return destinazioneUsoServizioEntePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.scrivaniaoperatore.model.impl.DestinazioneUsoServizioEnteModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return destinazioneUsoServizioEntePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return destinazioneUsoServizioEntePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return destinazioneUsoServizioEntePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DestinazioneUsoServizioEnte fetchDestinazioneUsoServizioEnte(
		DestinazioneUsoServizioEntePK destinazioneUsoServizioEntePK) {

		return destinazioneUsoServizioEntePersistence.fetchByPrimaryKey(
			destinazioneUsoServizioEntePK);
	}

	/**
	 * Returns the destinazione uso servizio ente matching the UUID and group.
	 *
	 * @param uuid the destinazione uso servizio ente's UUID
	 * @param groupId the primary key of the group
	 * @return the matching destinazione uso servizio ente, or <code>null</code> if a matching destinazione uso servizio ente could not be found
	 */
	@Override
	public DestinazioneUsoServizioEnte
		fetchDestinazioneUsoServizioEnteByUuidAndGroupId(
			String uuid, long groupId) {

		return destinazioneUsoServizioEntePersistence.fetchByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns the destinazione uso servizio ente with the primary key.
	 *
	 * @param destinazioneUsoServizioEntePK the primary key of the destinazione uso servizio ente
	 * @return the destinazione uso servizio ente
	 * @throws PortalException if a destinazione uso servizio ente with the primary key could not be found
	 */
	@Override
	public DestinazioneUsoServizioEnte getDestinazioneUsoServizioEnte(
			DestinazioneUsoServizioEntePK destinazioneUsoServizioEntePK)
		throws PortalException {

		return destinazioneUsoServizioEntePersistence.findByPrimaryKey(
			destinazioneUsoServizioEntePK);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			destinazioneUsoServizioEnteLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DestinazioneUsoServizioEnte.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.destinazioneUsoId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			destinazioneUsoServizioEnteLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			DestinazioneUsoServizioEnte.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.destinazioneUsoId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			destinazioneUsoServizioEnteLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DestinazioneUsoServizioEnte.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.destinazioneUsoId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<DestinazioneUsoServizioEnte>() {

				@Override
				public void performAction(
						DestinazioneUsoServizioEnte destinazioneUsoServizioEnte)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, destinazioneUsoServizioEnte);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					DestinazioneUsoServizioEnte.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return destinazioneUsoServizioEntePersistence.create(
			(DestinazioneUsoServizioEntePK)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return destinazioneUsoServizioEnteLocalService.
			deleteDestinazioneUsoServizioEnte(
				(DestinazioneUsoServizioEnte)persistedModel);
	}

	@Override
	public BasePersistence<DestinazioneUsoServizioEnte> getBasePersistence() {
		return destinazioneUsoServizioEntePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return destinazioneUsoServizioEntePersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the destinazione uso servizio entes matching the UUID and company.
	 *
	 * @param uuid the UUID of the destinazione uso servizio entes
	 * @param companyId the primary key of the company
	 * @return the matching destinazione uso servizio entes, or an empty list if no matches were found
	 */
	@Override
	public List<DestinazioneUsoServizioEnte>
		getDestinazioneUsoServizioEntesByUuidAndCompanyId(
			String uuid, long companyId) {

		return destinazioneUsoServizioEntePersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of destinazione uso servizio entes matching the UUID and company.
	 *
	 * @param uuid the UUID of the destinazione uso servizio entes
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of destinazione uso servizio entes
	 * @param end the upper bound of the range of destinazione uso servizio entes (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching destinazione uso servizio entes, or an empty list if no matches were found
	 */
	@Override
	public List<DestinazioneUsoServizioEnte>
		getDestinazioneUsoServizioEntesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<DestinazioneUsoServizioEnte> orderByComparator) {

		return destinazioneUsoServizioEntePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the destinazione uso servizio ente matching the UUID and group.
	 *
	 * @param uuid the destinazione uso servizio ente's UUID
	 * @param groupId the primary key of the group
	 * @return the matching destinazione uso servizio ente
	 * @throws PortalException if a matching destinazione uso servizio ente could not be found
	 */
	@Override
	public DestinazioneUsoServizioEnte
			getDestinazioneUsoServizioEnteByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return destinazioneUsoServizioEntePersistence.findByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns a range of all the destinazione uso servizio entes.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.scrivaniaoperatore.model.impl.DestinazioneUsoServizioEnteModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of destinazione uso servizio entes
	 * @param end the upper bound of the range of destinazione uso servizio entes (not inclusive)
	 * @return the range of destinazione uso servizio entes
	 */
	@Override
	public List<DestinazioneUsoServizioEnte> getDestinazioneUsoServizioEntes(
		int start, int end) {

		return destinazioneUsoServizioEntePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of destinazione uso servizio entes.
	 *
	 * @return the number of destinazione uso servizio entes
	 */
	@Override
	public int getDestinazioneUsoServizioEntesCount() {
		return destinazioneUsoServizioEntePersistence.countAll();
	}

	/**
	 * Updates the destinazione uso servizio ente in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DestinazioneUsoServizioEnteLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param destinazioneUsoServizioEnte the destinazione uso servizio ente
	 * @return the destinazione uso servizio ente that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DestinazioneUsoServizioEnte updateDestinazioneUsoServizioEnte(
		DestinazioneUsoServizioEnte destinazioneUsoServizioEnte) {

		return destinazioneUsoServizioEntePersistence.update(
			destinazioneUsoServizioEnte);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DestinazioneUsoServizioEnteLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		destinazioneUsoServizioEnteLocalService =
			(DestinazioneUsoServizioEnteLocalService)aopProxy;

		_setLocalServiceUtilService(destinazioneUsoServizioEnteLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DestinazioneUsoServizioEnteLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DestinazioneUsoServizioEnte.class;
	}

	protected String getModelClassName() {
		return DestinazioneUsoServizioEnte.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				destinazioneUsoServizioEntePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		DestinazioneUsoServizioEnteLocalService
			destinazioneUsoServizioEnteLocalService) {

		try {
			Field field =
				DestinazioneUsoServizioEnteLocalServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, destinazioneUsoServizioEnteLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AllegatoRichiestaPersistence allegatoRichiestaPersistence;

	@Reference
	protected AttivitaRichiestaPersistence attivitaRichiestaPersistence;

	@Reference
	protected CommentoRichiestaPersistence commentoRichiestaPersistence;

	@Reference
	protected DestinazioneUsoPersistence destinazioneUsoPersistence;

	@Reference
	protected DestinazioneUsoFinder destinazioneUsoFinder;

	protected DestinazioneUsoServizioEnteLocalService
		destinazioneUsoServizioEnteLocalService;

	@Reference
	protected DestinazioneUsoServizioEntePersistence
		destinazioneUsoServizioEntePersistence;

	@Reference
	protected IstanzaFormPersistence istanzaFormPersistence;

	@Reference
	protected RichiestaPersistence richiestaPersistence;

	@Reference
	protected RichiestaFinder richiestaFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}