package it.servizidigitali.camunda.integration.client.constant;

public interface CustomProcessVariables {
	String ID_RICHIESTA_SERVIZIO = "ID_RICHIESTA_SERVIZIO";
	String ID_GRUPPO_REFERENTI = "ID_GRUPPO_REFERENTI";

	String DENOMINAZIONE_RICHIEDENTE = "DENOMINAZIONE_RICHIEDENTE";
	String COD_FISCALE_RICHIEDENTE = "COD_FISCALE_RICHIEDENTE";
	String EMAIL_RICHIEDENTE = "EMAIL_RICHIEDENTE";
	String PARTITA_IVA_RICHIEDENTE = "PARTITA_IVA_RICHIEDENTE";

	String NUMERO_PROTOCOLLO = "NUMERO_PROTOCOLLO";
	String DATA_PROTOCOLLO = "DATA_PROTOCOLLO";

	String OGGETTO = "OGGETTO";
	String NOTE = "NOTE";

	String FILE_ALLEGATI = "FILE_ALLEGATI";

	String NOME_FILE_FIRMATO = "NOME_FILE_FIRMATO";
	String PDF_FIRMATO = "PDF_FIRMATO";

	String CODICE_IPA_COMUNE = "CODICE_IPA_COMUNE";
	String DENOMINAZIONE_COMUNE = "DENOMINAZIONE_COMUNE";

	String CODICE_SERVIZIO = "CODICE_SERVIZIO";
	String DENOMINAZIONE_SERVIZIO = "DENOMINAZIONE_SERVIZIO";

	String CODICE_AREA_TEMATICA = "CODICE_AREA_TEMATICA";
	String DENOMINAZIONE_AREA_TEMATICA = "AREA_TEMATICA";

	String INTEGRAZIONI_COMPLETATE_MESSAGE = "DOCUMENTAZIONE_INSERITA";
	String INTEGRAZIONI_ANNULLATE_MESSAGE = "ANNULLAMENTO";

	String ESITO_PROCEDIMENTO = "ESITO_PROCEDIMENTO";

	String DATA_CREAZIONE_RICHIESTA = "DATA_CREAZIONE_RICHIESTA";
	String STATO_RICHIESTA = "STATO_RICHIESTA";

	String UPDATE_STATO_RICHIESTA = "UPDATE_STATO_RICHIESTA";

	String MINORI_FUORI_BACINO = "MINORI_FUORI_BACINO";
}
