/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneforms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DefinizioneAllegato service. Represents a row in the &quot;definizione_allegato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.gestioneforms.model.impl.DefinizioneAllegatoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.gestioneforms.model.impl.DefinizioneAllegatoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DefinizioneAllegato
 * @generated
 */
@ProviderType
public interface DefinizioneAllegatoModel
	extends BaseModel<DefinizioneAllegato>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a definizione allegato model instance should use the {@link DefinizioneAllegato} interface instead.
	 */

	/**
	 * Returns the primary key of this definizione allegato.
	 *
	 * @return the primary key of this definizione allegato
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this definizione allegato.
	 *
	 * @param primaryKey the primary key of this definizione allegato
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this definizione allegato.
	 *
	 * @return the uuid of this definizione allegato
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this definizione allegato.
	 *
	 * @param uuid the uuid of this definizione allegato
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the definizione allegato ID of this definizione allegato.
	 *
	 * @return the definizione allegato ID of this definizione allegato
	 */
	public long getDefinizioneAllegatoId();

	/**
	 * Sets the definizione allegato ID of this definizione allegato.
	 *
	 * @param definizioneAllegatoId the definizione allegato ID of this definizione allegato
	 */
	public void setDefinizioneAllegatoId(long definizioneAllegatoId);

	/**
	 * Returns the group ID of this definizione allegato.
	 *
	 * @return the group ID of this definizione allegato
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this definizione allegato.
	 *
	 * @param groupId the group ID of this definizione allegato
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this definizione allegato.
	 *
	 * @return the company ID of this definizione allegato
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this definizione allegato.
	 *
	 * @param companyId the company ID of this definizione allegato
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this definizione allegato.
	 *
	 * @return the user ID of this definizione allegato
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this definizione allegato.
	 *
	 * @param userId the user ID of this definizione allegato
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this definizione allegato.
	 *
	 * @return the user uuid of this definizione allegato
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this definizione allegato.
	 *
	 * @param userUuid the user uuid of this definizione allegato
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this definizione allegato.
	 *
	 * @return the user name of this definizione allegato
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this definizione allegato.
	 *
	 * @param userName the user name of this definizione allegato
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this definizione allegato.
	 *
	 * @return the create date of this definizione allegato
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this definizione allegato.
	 *
	 * @param createDate the create date of this definizione allegato
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this definizione allegato.
	 *
	 * @return the modified date of this definizione allegato
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this definizione allegato.
	 *
	 * @param modifiedDate the modified date of this definizione allegato
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the denominazione of this definizione allegato.
	 *
	 * @return the denominazione of this definizione allegato
	 */
	@AutoEscape
	public String getDenominazione();

	/**
	 * Sets the denominazione of this definizione allegato.
	 *
	 * @param denominazione the denominazione of this definizione allegato
	 */
	public void setDenominazione(String denominazione);

	/**
	 * Returns the file entry ID of this definizione allegato.
	 *
	 * @return the file entry ID of this definizione allegato
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this definizione allegato.
	 *
	 * @param fileEntryId the file entry ID of this definizione allegato
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the filename modello of this definizione allegato.
	 *
	 * @return the filename modello of this definizione allegato
	 */
	@AutoEscape
	public String getFilenameModello();

	/**
	 * Sets the filename modello of this definizione allegato.
	 *
	 * @param filenameModello the filename modello of this definizione allegato
	 */
	public void setFilenameModello(String filenameModello);

	/**
	 * Returns the tipi file ammessi of this definizione allegato.
	 *
	 * @return the tipi file ammessi of this definizione allegato
	 */
	@AutoEscape
	public String getTipiFileAmmessi();

	/**
	 * Sets the tipi file ammessi of this definizione allegato.
	 *
	 * @param tipiFileAmmessi the tipi file ammessi of this definizione allegato
	 */
	public void setTipiFileAmmessi(String tipiFileAmmessi);

	/**
	 * Returns the codici tipologia documento of this definizione allegato.
	 *
	 * @return the codici tipologia documento of this definizione allegato
	 */
	@AutoEscape
	public String getCodiciTipologiaDocumento();

	/**
	 * Sets the codici tipologia documento of this definizione allegato.
	 *
	 * @param codiciTipologiaDocumento the codici tipologia documento of this definizione allegato
	 */
	public void setCodiciTipologiaDocumento(String codiciTipologiaDocumento);

	/**
	 * Returns the obbligatorio of this definizione allegato.
	 *
	 * @return the obbligatorio of this definizione allegato
	 */
	public boolean getObbligatorio();

	/**
	 * Returns <code>true</code> if this definizione allegato is obbligatorio.
	 *
	 * @return <code>true</code> if this definizione allegato is obbligatorio; <code>false</code> otherwise
	 */
	public boolean isObbligatorio();

	/**
	 * Sets whether this definizione allegato is obbligatorio.
	 *
	 * @param obbligatorio the obbligatorio of this definizione allegato
	 */
	public void setObbligatorio(boolean obbligatorio);

	/**
	 * Returns the organization ID of this definizione allegato.
	 *
	 * @return the organization ID of this definizione allegato
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this definizione allegato.
	 *
	 * @param organizationId the organization ID of this definizione allegato
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the form ID of this definizione allegato.
	 *
	 * @return the form ID of this definizione allegato
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this definizione allegato.
	 *
	 * @param formId the form ID of this definizione allegato
	 */
	public void setFormId(long formId);

	@Override
	public DefinizioneAllegato cloneWithOriginalValues();

}