/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneforms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Form service. Represents a row in the &quot;form&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.gestioneforms.model.impl.FormModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.gestioneforms.model.impl.FormImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Form
 * @generated
 */
@ProviderType
public interface FormModel
	extends BaseModel<Form>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form model instance should use the {@link Form} interface instead.
	 */

	/**
	 * Returns the primary key of this form.
	 *
	 * @return the primary key of this form
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form.
	 *
	 * @param primaryKey the primary key of this form
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this form.
	 *
	 * @return the uuid of this form
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this form.
	 *
	 * @param uuid the uuid of this form
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the form ID of this form.
	 *
	 * @return the form ID of this form
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this form.
	 *
	 * @param formId the form ID of this form
	 */
	public void setFormId(long formId);

	/**
	 * Returns the group ID of this form.
	 *
	 * @return the group ID of this form
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this form.
	 *
	 * @param groupId the group ID of this form
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this form.
	 *
	 * @return the company ID of this form
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this form.
	 *
	 * @param companyId the company ID of this form
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this form.
	 *
	 * @return the user ID of this form
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this form.
	 *
	 * @param userId the user ID of this form
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this form.
	 *
	 * @return the user uuid of this form
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this form.
	 *
	 * @param userUuid the user uuid of this form
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this form.
	 *
	 * @return the user name of this form
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this form.
	 *
	 * @param userName the user name of this form
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this form.
	 *
	 * @return the create date of this form
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this form.
	 *
	 * @param createDate the create date of this form
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this form.
	 *
	 * @return the modified date of this form
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this form.
	 *
	 * @param modifiedDate the modified date of this form
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this form.
	 *
	 * @return the nome of this form
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this form.
	 *
	 * @param nome the nome of this form
	 */
	public void setNome(String nome);

	/**
	 * Returns the descrizione of this form.
	 *
	 * @return the descrizione of this form
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this form.
	 *
	 * @param descrizione the descrizione of this form
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the codice of this form.
	 *
	 * @return the codice of this form
	 */
	@AutoEscape
	public String getCodice();

	/**
	 * Sets the codice of this form.
	 *
	 * @param codice the codice of this form
	 */
	public void setCodice(String codice);

	/**
	 * Returns the json of this form.
	 *
	 * @return the json of this form
	 */
	@AutoEscape
	public String getJson();

	/**
	 * Sets the json of this form.
	 *
	 * @param json the json of this form
	 */
	public void setJson(String json);

	/**
	 * Returns the principale of this form.
	 *
	 * @return the principale of this form
	 */
	public boolean getPrincipale();

	/**
	 * Returns <code>true</code> if this form is principale.
	 *
	 * @return <code>true</code> if this form is principale; <code>false</code> otherwise
	 */
	public boolean isPrincipale();

	/**
	 * Sets whether this form is principale.
	 *
	 * @param principale the principale of this form
	 */
	public void setPrincipale(boolean principale);

	/**
	 * Returns the multiutente of this form.
	 *
	 * @return the multiutente of this form
	 */
	public boolean getMultiutente();

	/**
	 * Returns <code>true</code> if this form is multiutente.
	 *
	 * @return <code>true</code> if this form is multiutente; <code>false</code> otherwise
	 */
	public boolean isMultiutente();

	/**
	 * Sets whether this form is multiutente.
	 *
	 * @param multiutente the multiutente of this form
	 */
	public void setMultiutente(boolean multiutente);

	/**
	 * Returns the organization ID of this form.
	 *
	 * @return the organization ID of this form
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this form.
	 *
	 * @param organizationId the organization ID of this form
	 */
	public void setOrganizationId(long organizationId);

	@Override
	public Form cloneWithOriginalValues();

}