/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.accreditamentoenti.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Ente service. Represents a row in the &quot;ente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.accreditamentoenti.model.impl.EnteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.accreditamentoenti.model.impl.EnteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Ente
 * @generated
 */
@ProviderType
public interface EnteModel
	extends BaseModel<Ente>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ente model instance should use the {@link Ente} interface instead.
	 */

	/**
	 * Returns the primary key of this ente.
	 *
	 * @return the primary key of this ente
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ente.
	 *
	 * @param primaryKey the primary key of this ente
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ente.
	 *
	 * @return the uuid of this ente
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ente.
	 *
	 * @param uuid the uuid of this ente
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ente ID of this ente.
	 *
	 * @return the ente ID of this ente
	 */
	public long getEnteId();

	/**
	 * Sets the ente ID of this ente.
	 *
	 * @param enteId the ente ID of this ente
	 */
	public void setEnteId(long enteId);

	/**
	 * Returns the group ID of this ente.
	 *
	 * @return the group ID of this ente
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ente.
	 *
	 * @param groupId the group ID of this ente
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ente.
	 *
	 * @return the company ID of this ente
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ente.
	 *
	 * @param companyId the company ID of this ente
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ente.
	 *
	 * @return the user ID of this ente
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ente.
	 *
	 * @param userId the user ID of this ente
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ente.
	 *
	 * @return the user uuid of this ente
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ente.
	 *
	 * @param userUuid the user uuid of this ente
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ente.
	 *
	 * @return the user name of this ente
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ente.
	 *
	 * @param userName the user name of this ente
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ente.
	 *
	 * @return the create date of this ente
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ente.
	 *
	 * @param createDate the create date of this ente
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ente.
	 *
	 * @return the modified date of this ente
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ente.
	 *
	 * @param modifiedDate the modified date of this ente
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the denominazione of this ente.
	 *
	 * @return the denominazione of this ente
	 */
	@AutoEscape
	public String getDenominazione();

	/**
	 * Sets the denominazione of this ente.
	 *
	 * @param denominazione the denominazione of this ente
	 */
	public void setDenominazione(String denominazione);

	/**
	 * Returns the struttura riferimento of this ente.
	 *
	 * @return the struttura riferimento of this ente
	 */
	@AutoEscape
	public String getStrutturaRiferimento();

	/**
	 * Sets the struttura riferimento of this ente.
	 *
	 * @param strutturaRiferimento the struttura riferimento of this ente
	 */
	public void setStrutturaRiferimento(String strutturaRiferimento);

	/**
	 * Returns the sito web of this ente.
	 *
	 * @return the sito web of this ente
	 */
	@AutoEscape
	public String getSitoWeb();

	/**
	 * Sets the sito web of this ente.
	 *
	 * @param sitoWeb the sito web of this ente
	 */
	public void setSitoWeb(String sitoWeb);

	/**
	 * Returns the tipo of this ente.
	 *
	 * @return the tipo of this ente
	 */
	@AutoEscape
	public String getTipo();

	/**
	 * Sets the tipo of this ente.
	 *
	 * @param tipo the tipo of this ente
	 */
	public void setTipo(String tipo);

	/**
	 * Returns the codice ipa of this ente.
	 *
	 * @return the codice ipa of this ente
	 */
	@AutoEscape
	public String getCodiceIPA();

	/**
	 * Sets the codice ipa of this ente.
	 *
	 * @param codiceIPA the codice ipa of this ente
	 */
	public void setCodiceIPA(String codiceIPA);

	/**
	 * Returns the pec of this ente.
	 *
	 * @return the pec of this ente
	 */
	@AutoEscape
	public String getPec();

	/**
	 * Sets the pec of this ente.
	 *
	 * @param pec the pec of this ente
	 */
	public void setPec(String pec);

	@Override
	public Ente cloneWithOriginalValues();

}