/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.accreditamentoenti.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Example service. Represents a row in the &quot;example&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.accreditamentoenti.model.impl.ExampleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.accreditamentoenti.model.impl.ExampleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Example
 * @generated
 */
@ProviderType
public interface ExampleModel
	extends BaseModel<Example>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a example model instance should use the {@link Example} interface instead.
	 */

	/**
	 * Returns the primary key of this example.
	 *
	 * @return the primary key of this example
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this example.
	 *
	 * @param primaryKey the primary key of this example
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this example.
	 *
	 * @return the uuid of this example
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this example.
	 *
	 * @param uuid the uuid of this example
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the example ID of this example.
	 *
	 * @return the example ID of this example
	 */
	public long getExampleId();

	/**
	 * Sets the example ID of this example.
	 *
	 * @param exampleId the example ID of this example
	 */
	public void setExampleId(long exampleId);

	/**
	 * Returns the group ID of this example.
	 *
	 * @return the group ID of this example
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this example.
	 *
	 * @param groupId the group ID of this example
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this example.
	 *
	 * @return the company ID of this example
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this example.
	 *
	 * @param companyId the company ID of this example
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this example.
	 *
	 * @return the user ID of this example
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this example.
	 *
	 * @param userId the user ID of this example
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this example.
	 *
	 * @return the user uuid of this example
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this example.
	 *
	 * @param userUuid the user uuid of this example
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this example.
	 *
	 * @return the user name of this example
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this example.
	 *
	 * @param userName the user name of this example
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this example.
	 *
	 * @return the create date of this example
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this example.
	 *
	 * @param createDate the create date of this example
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this example.
	 *
	 * @return the modified date of this example
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this example.
	 *
	 * @param modifiedDate the modified date of this example
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Example cloneWithOriginalValues();

}