/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.profiloutente.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import it.servizidigitali.profiloutente.model.CanaleComunicazione;
import it.servizidigitali.profiloutente.service.CanaleComunicazioneLocalService;
import it.servizidigitali.profiloutente.service.CanaleComunicazioneLocalServiceUtil;
import it.servizidigitali.profiloutente.service.persistence.CanaleComunicazionePersistence;
import it.servizidigitali.profiloutente.service.persistence.UtenteOrganizzazioneCanaleComunicazionePersistence;
import it.servizidigitali.profiloutente.service.persistence.UtenteOrganizzazionePersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the canale comunicazione local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.servizidigitali.profiloutente.service.impl.CanaleComunicazioneLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see it.servizidigitali.profiloutente.service.impl.CanaleComunicazioneLocalServiceImpl
 * @generated
 */
public abstract class CanaleComunicazioneLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CanaleComunicazioneLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CanaleComunicazioneLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CanaleComunicazioneLocalServiceUtil</code>.
	 */

	/**
	 * Adds the canale comunicazione to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CanaleComunicazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param canaleComunicazione the canale comunicazione
	 * @return the canale comunicazione that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CanaleComunicazione addCanaleComunicazione(
		CanaleComunicazione canaleComunicazione) {

		canaleComunicazione.setNew(true);

		return canaleComunicazionePersistence.update(canaleComunicazione);
	}

	/**
	 * Creates a new canale comunicazione with the primary key. Does not add the canale comunicazione to the database.
	 *
	 * @param canaleComunicazioneId the primary key for the new canale comunicazione
	 * @return the new canale comunicazione
	 */
	@Override
	@Transactional(enabled = false)
	public CanaleComunicazione createCanaleComunicazione(
		long canaleComunicazioneId) {

		return canaleComunicazionePersistence.create(canaleComunicazioneId);
	}

	/**
	 * Deletes the canale comunicazione with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CanaleComunicazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param canaleComunicazioneId the primary key of the canale comunicazione
	 * @return the canale comunicazione that was removed
	 * @throws PortalException if a canale comunicazione with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CanaleComunicazione deleteCanaleComunicazione(
			long canaleComunicazioneId)
		throws PortalException {

		return canaleComunicazionePersistence.remove(canaleComunicazioneId);
	}

	/**
	 * Deletes the canale comunicazione from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CanaleComunicazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param canaleComunicazione the canale comunicazione
	 * @return the canale comunicazione that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CanaleComunicazione deleteCanaleComunicazione(
		CanaleComunicazione canaleComunicazione) {

		return canaleComunicazionePersistence.remove(canaleComunicazione);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return canaleComunicazionePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CanaleComunicazione.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return canaleComunicazionePersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.profiloutente.model.impl.CanaleComunicazioneModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return canaleComunicazionePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.profiloutente.model.impl.CanaleComunicazioneModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return canaleComunicazionePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return canaleComunicazionePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return canaleComunicazionePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CanaleComunicazione fetchCanaleComunicazione(
		long canaleComunicazioneId) {

		return canaleComunicazionePersistence.fetchByPrimaryKey(
			canaleComunicazioneId);
	}

	/**
	 * Returns the canale comunicazione matching the UUID and group.
	 *
	 * @param uuid the canale comunicazione's UUID
	 * @param groupId the primary key of the group
	 * @return the matching canale comunicazione, or <code>null</code> if a matching canale comunicazione could not be found
	 */
	@Override
	public CanaleComunicazione fetchCanaleComunicazioneByUuidAndGroupId(
		String uuid, long groupId) {

		return canaleComunicazionePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the canale comunicazione with the primary key.
	 *
	 * @param canaleComunicazioneId the primary key of the canale comunicazione
	 * @return the canale comunicazione
	 * @throws PortalException if a canale comunicazione with the primary key could not be found
	 */
	@Override
	public CanaleComunicazione getCanaleComunicazione(
			long canaleComunicazioneId)
		throws PortalException {

		return canaleComunicazionePersistence.findByPrimaryKey(
			canaleComunicazioneId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			canaleComunicazioneLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CanaleComunicazione.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"canaleComunicazioneId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			canaleComunicazioneLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CanaleComunicazione.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"canaleComunicazioneId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			canaleComunicazioneLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CanaleComunicazione.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"canaleComunicazioneId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<CanaleComunicazione>() {

				@Override
				public void performAction(
						CanaleComunicazione canaleComunicazione)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, canaleComunicazione);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					CanaleComunicazione.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return canaleComunicazionePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return canaleComunicazioneLocalService.deleteCanaleComunicazione(
			(CanaleComunicazione)persistedModel);
	}

	@Override
	public BasePersistence<CanaleComunicazione> getBasePersistence() {
		return canaleComunicazionePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return canaleComunicazionePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the canale comunicaziones matching the UUID and company.
	 *
	 * @param uuid the UUID of the canale comunicaziones
	 * @param companyId the primary key of the company
	 * @return the matching canale comunicaziones, or an empty list if no matches were found
	 */
	@Override
	public List<CanaleComunicazione> getCanaleComunicazionesByUuidAndCompanyId(
		String uuid, long companyId) {

		return canaleComunicazionePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of canale comunicaziones matching the UUID and company.
	 *
	 * @param uuid the UUID of the canale comunicaziones
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of canale comunicaziones
	 * @param end the upper bound of the range of canale comunicaziones (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching canale comunicaziones, or an empty list if no matches were found
	 */
	@Override
	public List<CanaleComunicazione> getCanaleComunicazionesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<CanaleComunicazione> orderByComparator) {

		return canaleComunicazionePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the canale comunicazione matching the UUID and group.
	 *
	 * @param uuid the canale comunicazione's UUID
	 * @param groupId the primary key of the group
	 * @return the matching canale comunicazione
	 * @throws PortalException if a matching canale comunicazione could not be found
	 */
	@Override
	public CanaleComunicazione getCanaleComunicazioneByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return canaleComunicazionePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the canale comunicaziones.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.profiloutente.model.impl.CanaleComunicazioneModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of canale comunicaziones
	 * @param end the upper bound of the range of canale comunicaziones (not inclusive)
	 * @return the range of canale comunicaziones
	 */
	@Override
	public List<CanaleComunicazione> getCanaleComunicaziones(
		int start, int end) {

		return canaleComunicazionePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of canale comunicaziones.
	 *
	 * @return the number of canale comunicaziones
	 */
	@Override
	public int getCanaleComunicazionesCount() {
		return canaleComunicazionePersistence.countAll();
	}

	/**
	 * Updates the canale comunicazione in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CanaleComunicazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param canaleComunicazione the canale comunicazione
	 * @return the canale comunicazione that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CanaleComunicazione updateCanaleComunicazione(
		CanaleComunicazione canaleComunicazione) {

		return canaleComunicazionePersistence.update(canaleComunicazione);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CanaleComunicazioneLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		canaleComunicazioneLocalService =
			(CanaleComunicazioneLocalService)aopProxy;

		_setLocalServiceUtilService(canaleComunicazioneLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CanaleComunicazioneLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CanaleComunicazione.class;
	}

	protected String getModelClassName() {
		return CanaleComunicazione.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				canaleComunicazionePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		CanaleComunicazioneLocalService canaleComunicazioneLocalService) {

		try {
			Field field =
				CanaleComunicazioneLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, canaleComunicazioneLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected CanaleComunicazioneLocalService canaleComunicazioneLocalService;

	@Reference
	protected CanaleComunicazionePersistence canaleComunicazionePersistence;

	@Reference
	protected UtenteOrganizzazionePersistence utenteOrganizzazionePersistence;

	@Reference
	protected UtenteOrganizzazioneCanaleComunicazionePersistence
		utenteOrganizzazioneCanaleComunicazionePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}