/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.profiloutente.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import it.servizidigitali.profiloutente.model.UtenteOrganizzazioneCanaleComunicazione;
import it.servizidigitali.profiloutente.service.UtenteOrganizzazioneCanaleComunicazioneLocalService;
import it.servizidigitali.profiloutente.service.UtenteOrganizzazioneCanaleComunicazioneLocalServiceUtil;
import it.servizidigitali.profiloutente.service.persistence.CanaleComunicazionePersistence;
import it.servizidigitali.profiloutente.service.persistence.UtenteOrganizzazioneCanaleComunicazionePK;
import it.servizidigitali.profiloutente.service.persistence.UtenteOrganizzazioneCanaleComunicazionePersistence;
import it.servizidigitali.profiloutente.service.persistence.UtenteOrganizzazionePersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the utente organizzazione canale comunicazione local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.servizidigitali.profiloutente.service.impl.UtenteOrganizzazioneCanaleComunicazioneLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see it.servizidigitali.profiloutente.service.impl.UtenteOrganizzazioneCanaleComunicazioneLocalServiceImpl
 * @generated
 */
public abstract class
	UtenteOrganizzazioneCanaleComunicazioneLocalServiceBaseImpl
		extends BaseLocalServiceImpl
		implements AopService, IdentifiableOSGiService,
				   UtenteOrganizzazioneCanaleComunicazioneLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>UtenteOrganizzazioneCanaleComunicazioneLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>UtenteOrganizzazioneCanaleComunicazioneLocalServiceUtil</code>.
	 */

	/**
	 * Adds the utente organizzazione canale comunicazione to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UtenteOrganizzazioneCanaleComunicazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param utenteOrganizzazioneCanaleComunicazione the utente organizzazione canale comunicazione
	 * @return the utente organizzazione canale comunicazione that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UtenteOrganizzazioneCanaleComunicazione
		addUtenteOrganizzazioneCanaleComunicazione(
			UtenteOrganizzazioneCanaleComunicazione
				utenteOrganizzazioneCanaleComunicazione) {

		utenteOrganizzazioneCanaleComunicazione.setNew(true);

		return utenteOrganizzazioneCanaleComunicazionePersistence.update(
			utenteOrganizzazioneCanaleComunicazione);
	}

	/**
	 * Creates a new utente organizzazione canale comunicazione with the primary key. Does not add the utente organizzazione canale comunicazione to the database.
	 *
	 * @param utenteOrganizzazioneCanaleComunicazionePK the primary key for the new utente organizzazione canale comunicazione
	 * @return the new utente organizzazione canale comunicazione
	 */
	@Override
	@Transactional(enabled = false)
	public UtenteOrganizzazioneCanaleComunicazione
		createUtenteOrganizzazioneCanaleComunicazione(
			UtenteOrganizzazioneCanaleComunicazionePK
				utenteOrganizzazioneCanaleComunicazionePK) {

		return utenteOrganizzazioneCanaleComunicazionePersistence.create(
			utenteOrganizzazioneCanaleComunicazionePK);
	}

	/**
	 * Deletes the utente organizzazione canale comunicazione with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UtenteOrganizzazioneCanaleComunicazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param utenteOrganizzazioneCanaleComunicazionePK the primary key of the utente organizzazione canale comunicazione
	 * @return the utente organizzazione canale comunicazione that was removed
	 * @throws PortalException if a utente organizzazione canale comunicazione with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UtenteOrganizzazioneCanaleComunicazione
			deleteUtenteOrganizzazioneCanaleComunicazione(
				UtenteOrganizzazioneCanaleComunicazionePK
					utenteOrganizzazioneCanaleComunicazionePK)
		throws PortalException {

		return utenteOrganizzazioneCanaleComunicazionePersistence.remove(
			utenteOrganizzazioneCanaleComunicazionePK);
	}

	/**
	 * Deletes the utente organizzazione canale comunicazione from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UtenteOrganizzazioneCanaleComunicazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param utenteOrganizzazioneCanaleComunicazione the utente organizzazione canale comunicazione
	 * @return the utente organizzazione canale comunicazione that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UtenteOrganizzazioneCanaleComunicazione
		deleteUtenteOrganizzazioneCanaleComunicazione(
			UtenteOrganizzazioneCanaleComunicazione
				utenteOrganizzazioneCanaleComunicazione) {

		return utenteOrganizzazioneCanaleComunicazionePersistence.remove(
			utenteOrganizzazioneCanaleComunicazione);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return utenteOrganizzazioneCanaleComunicazionePersistence.dslQuery(
			dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			UtenteOrganizzazioneCanaleComunicazione.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return utenteOrganizzazioneCanaleComunicazionePersistence.
			findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.profiloutente.model.impl.UtenteOrganizzazioneCanaleComunicazioneModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return utenteOrganizzazioneCanaleComunicazionePersistence.
			findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.profiloutente.model.impl.UtenteOrganizzazioneCanaleComunicazioneModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return utenteOrganizzazioneCanaleComunicazionePersistence.
			findWithDynamicQuery(dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return utenteOrganizzazioneCanaleComunicazionePersistence.
			countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return utenteOrganizzazioneCanaleComunicazionePersistence.
			countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public UtenteOrganizzazioneCanaleComunicazione
		fetchUtenteOrganizzazioneCanaleComunicazione(
			UtenteOrganizzazioneCanaleComunicazionePK
				utenteOrganizzazioneCanaleComunicazionePK) {

		return utenteOrganizzazioneCanaleComunicazionePersistence.
			fetchByPrimaryKey(utenteOrganizzazioneCanaleComunicazionePK);
	}

	/**
	 * Returns the utente organizzazione canale comunicazione matching the UUID and group.
	 *
	 * @param uuid the utente organizzazione canale comunicazione's UUID
	 * @param groupId the primary key of the group
	 * @return the matching utente organizzazione canale comunicazione, or <code>null</code> if a matching utente organizzazione canale comunicazione could not be found
	 */
	@Override
	public UtenteOrganizzazioneCanaleComunicazione
		fetchUtenteOrganizzazioneCanaleComunicazioneByUuidAndGroupId(
			String uuid, long groupId) {

		return utenteOrganizzazioneCanaleComunicazionePersistence.fetchByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns the utente organizzazione canale comunicazione with the primary key.
	 *
	 * @param utenteOrganizzazioneCanaleComunicazionePK the primary key of the utente organizzazione canale comunicazione
	 * @return the utente organizzazione canale comunicazione
	 * @throws PortalException if a utente organizzazione canale comunicazione with the primary key could not be found
	 */
	@Override
	public UtenteOrganizzazioneCanaleComunicazione
			getUtenteOrganizzazioneCanaleComunicazione(
				UtenteOrganizzazioneCanaleComunicazionePK
					utenteOrganizzazioneCanaleComunicazionePK)
		throws PortalException {

		return utenteOrganizzazioneCanaleComunicazionePersistence.
			findByPrimaryKey(utenteOrganizzazioneCanaleComunicazionePK);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			utenteOrganizzazioneCanaleComunicazioneLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			UtenteOrganizzazioneCanaleComunicazione.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("primaryKey.utenteId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			utenteOrganizzazioneCanaleComunicazioneLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			UtenteOrganizzazioneCanaleComunicazione.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.utenteId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			utenteOrganizzazioneCanaleComunicazioneLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			UtenteOrganizzazioneCanaleComunicazione.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("primaryKey.utenteId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<UtenteOrganizzazioneCanaleComunicazione>() {

				@Override
				public void performAction(
						UtenteOrganizzazioneCanaleComunicazione
							utenteOrganizzazioneCanaleComunicazione)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext,
						utenteOrganizzazioneCanaleComunicazione);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					UtenteOrganizzazioneCanaleComunicazione.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return utenteOrganizzazioneCanaleComunicazionePersistence.create(
			(UtenteOrganizzazioneCanaleComunicazionePK)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return utenteOrganizzazioneCanaleComunicazioneLocalService.
			deleteUtenteOrganizzazioneCanaleComunicazione(
				(UtenteOrganizzazioneCanaleComunicazione)persistedModel);
	}

	@Override
	public BasePersistence<UtenteOrganizzazioneCanaleComunicazione>
		getBasePersistence() {

		return utenteOrganizzazioneCanaleComunicazionePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return utenteOrganizzazioneCanaleComunicazionePersistence.
			findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the utente organizzazione canale comunicaziones matching the UUID and company.
	 *
	 * @param uuid the UUID of the utente organizzazione canale comunicaziones
	 * @param companyId the primary key of the company
	 * @return the matching utente organizzazione canale comunicaziones, or an empty list if no matches were found
	 */
	@Override
	public List<UtenteOrganizzazioneCanaleComunicazione>
		getUtenteOrganizzazioneCanaleComunicazionesByUuidAndCompanyId(
			String uuid, long companyId) {

		return utenteOrganizzazioneCanaleComunicazionePersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of utente organizzazione canale comunicaziones matching the UUID and company.
	 *
	 * @param uuid the UUID of the utente organizzazione canale comunicaziones
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of utente organizzazione canale comunicaziones
	 * @param end the upper bound of the range of utente organizzazione canale comunicaziones (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching utente organizzazione canale comunicaziones, or an empty list if no matches were found
	 */
	@Override
	public List<UtenteOrganizzazioneCanaleComunicazione>
		getUtenteOrganizzazioneCanaleComunicazionesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<UtenteOrganizzazioneCanaleComunicazione>
				orderByComparator) {

		return utenteOrganizzazioneCanaleComunicazionePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the utente organizzazione canale comunicazione matching the UUID and group.
	 *
	 * @param uuid the utente organizzazione canale comunicazione's UUID
	 * @param groupId the primary key of the group
	 * @return the matching utente organizzazione canale comunicazione
	 * @throws PortalException if a matching utente organizzazione canale comunicazione could not be found
	 */
	@Override
	public UtenteOrganizzazioneCanaleComunicazione
			getUtenteOrganizzazioneCanaleComunicazioneByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return utenteOrganizzazioneCanaleComunicazionePersistence.findByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns a range of all the utente organizzazione canale comunicaziones.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.profiloutente.model.impl.UtenteOrganizzazioneCanaleComunicazioneModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of utente organizzazione canale comunicaziones
	 * @param end the upper bound of the range of utente organizzazione canale comunicaziones (not inclusive)
	 * @return the range of utente organizzazione canale comunicaziones
	 */
	@Override
	public List<UtenteOrganizzazioneCanaleComunicazione>
		getUtenteOrganizzazioneCanaleComunicaziones(int start, int end) {

		return utenteOrganizzazioneCanaleComunicazionePersistence.findAll(
			start, end);
	}

	/**
	 * Returns the number of utente organizzazione canale comunicaziones.
	 *
	 * @return the number of utente organizzazione canale comunicaziones
	 */
	@Override
	public int getUtenteOrganizzazioneCanaleComunicazionesCount() {
		return utenteOrganizzazioneCanaleComunicazionePersistence.countAll();
	}

	/**
	 * Updates the utente organizzazione canale comunicazione in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UtenteOrganizzazioneCanaleComunicazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param utenteOrganizzazioneCanaleComunicazione the utente organizzazione canale comunicazione
	 * @return the utente organizzazione canale comunicazione that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UtenteOrganizzazioneCanaleComunicazione
		updateUtenteOrganizzazioneCanaleComunicazione(
			UtenteOrganizzazioneCanaleComunicazione
				utenteOrganizzazioneCanaleComunicazione) {

		return utenteOrganizzazioneCanaleComunicazionePersistence.update(
			utenteOrganizzazioneCanaleComunicazione);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			UtenteOrganizzazioneCanaleComunicazioneLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		utenteOrganizzazioneCanaleComunicazioneLocalService =
			(UtenteOrganizzazioneCanaleComunicazioneLocalService)aopProxy;

		_setLocalServiceUtilService(
			utenteOrganizzazioneCanaleComunicazioneLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return UtenteOrganizzazioneCanaleComunicazioneLocalService.class.
			getName();
	}

	protected Class<?> getModelClass() {
		return UtenteOrganizzazioneCanaleComunicazione.class;
	}

	protected String getModelClassName() {
		return UtenteOrganizzazioneCanaleComunicazione.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				utenteOrganizzazioneCanaleComunicazionePersistence.
					getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		UtenteOrganizzazioneCanaleComunicazioneLocalService
			utenteOrganizzazioneCanaleComunicazioneLocalService) {

		try {
			Field field =
				UtenteOrganizzazioneCanaleComunicazioneLocalServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(
				null, utenteOrganizzazioneCanaleComunicazioneLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CanaleComunicazionePersistence canaleComunicazionePersistence;

	@Reference
	protected UtenteOrganizzazionePersistence utenteOrganizzazionePersistence;

	protected UtenteOrganizzazioneCanaleComunicazioneLocalService
		utenteOrganizzazioneCanaleComunicazioneLocalService;

	@Reference
	protected UtenteOrganizzazioneCanaleComunicazionePersistence
		utenteOrganizzazioneCanaleComunicazionePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}