/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.profiloutente.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import it.servizidigitali.profiloutente.model.UtenteOrganizzazione;
import it.servizidigitali.profiloutente.service.UtenteOrganizzazioneLocalService;
import it.servizidigitali.profiloutente.service.UtenteOrganizzazioneLocalServiceUtil;
import it.servizidigitali.profiloutente.service.persistence.CanaleComunicazionePersistence;
import it.servizidigitali.profiloutente.service.persistence.UtenteOrganizzazioneCanaleComunicazionePersistence;
import it.servizidigitali.profiloutente.service.persistence.UtenteOrganizzazionePK;
import it.servizidigitali.profiloutente.service.persistence.UtenteOrganizzazionePersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the utente organizzazione local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.servizidigitali.profiloutente.service.impl.UtenteOrganizzazioneLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see it.servizidigitali.profiloutente.service.impl.UtenteOrganizzazioneLocalServiceImpl
 * @generated
 */
public abstract class UtenteOrganizzazioneLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   UtenteOrganizzazioneLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>UtenteOrganizzazioneLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>UtenteOrganizzazioneLocalServiceUtil</code>.
	 */

	/**
	 * Adds the utente organizzazione to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UtenteOrganizzazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param utenteOrganizzazione the utente organizzazione
	 * @return the utente organizzazione that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UtenteOrganizzazione addUtenteOrganizzazione(
		UtenteOrganizzazione utenteOrganizzazione) {

		utenteOrganizzazione.setNew(true);

		return utenteOrganizzazionePersistence.update(utenteOrganizzazione);
	}

	/**
	 * Creates a new utente organizzazione with the primary key. Does not add the utente organizzazione to the database.
	 *
	 * @param utenteOrganizzazionePK the primary key for the new utente organizzazione
	 * @return the new utente organizzazione
	 */
	@Override
	@Transactional(enabled = false)
	public UtenteOrganizzazione createUtenteOrganizzazione(
		UtenteOrganizzazionePK utenteOrganizzazionePK) {

		return utenteOrganizzazionePersistence.create(utenteOrganizzazionePK);
	}

	/**
	 * Deletes the utente organizzazione with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UtenteOrganizzazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param utenteOrganizzazionePK the primary key of the utente organizzazione
	 * @return the utente organizzazione that was removed
	 * @throws PortalException if a utente organizzazione with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UtenteOrganizzazione deleteUtenteOrganizzazione(
			UtenteOrganizzazionePK utenteOrganizzazionePK)
		throws PortalException {

		return utenteOrganizzazionePersistence.remove(utenteOrganizzazionePK);
	}

	/**
	 * Deletes the utente organizzazione from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UtenteOrganizzazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param utenteOrganizzazione the utente organizzazione
	 * @return the utente organizzazione that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UtenteOrganizzazione deleteUtenteOrganizzazione(
		UtenteOrganizzazione utenteOrganizzazione) {

		return utenteOrganizzazionePersistence.remove(utenteOrganizzazione);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return utenteOrganizzazionePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			UtenteOrganizzazione.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return utenteOrganizzazionePersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.profiloutente.model.impl.UtenteOrganizzazioneModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return utenteOrganizzazionePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.profiloutente.model.impl.UtenteOrganizzazioneModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return utenteOrganizzazionePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return utenteOrganizzazionePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return utenteOrganizzazionePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public UtenteOrganizzazione fetchUtenteOrganizzazione(
		UtenteOrganizzazionePK utenteOrganizzazionePK) {

		return utenteOrganizzazionePersistence.fetchByPrimaryKey(
			utenteOrganizzazionePK);
	}

	/**
	 * Returns the utente organizzazione matching the UUID and group.
	 *
	 * @param uuid the utente organizzazione's UUID
	 * @param groupId the primary key of the group
	 * @return the matching utente organizzazione, or <code>null</code> if a matching utente organizzazione could not be found
	 */
	@Override
	public UtenteOrganizzazione fetchUtenteOrganizzazioneByUuidAndGroupId(
		String uuid, long groupId) {

		return utenteOrganizzazionePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the utente organizzazione with the primary key.
	 *
	 * @param utenteOrganizzazionePK the primary key of the utente organizzazione
	 * @return the utente organizzazione
	 * @throws PortalException if a utente organizzazione with the primary key could not be found
	 */
	@Override
	public UtenteOrganizzazione getUtenteOrganizzazione(
			UtenteOrganizzazionePK utenteOrganizzazionePK)
		throws PortalException {

		return utenteOrganizzazionePersistence.findByPrimaryKey(
			utenteOrganizzazionePK);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			utenteOrganizzazioneLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UtenteOrganizzazione.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("primaryKey.utenteId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			utenteOrganizzazioneLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			UtenteOrganizzazione.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.utenteId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			utenteOrganizzazioneLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UtenteOrganizzazione.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("primaryKey.utenteId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<UtenteOrganizzazione>() {

				@Override
				public void performAction(
						UtenteOrganizzazione utenteOrganizzazione)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, utenteOrganizzazione);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					UtenteOrganizzazione.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return utenteOrganizzazionePersistence.create(
			(UtenteOrganizzazionePK)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return utenteOrganizzazioneLocalService.deleteUtenteOrganizzazione(
			(UtenteOrganizzazione)persistedModel);
	}

	@Override
	public BasePersistence<UtenteOrganizzazione> getBasePersistence() {
		return utenteOrganizzazionePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return utenteOrganizzazionePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the utente organizzaziones matching the UUID and company.
	 *
	 * @param uuid the UUID of the utente organizzaziones
	 * @param companyId the primary key of the company
	 * @return the matching utente organizzaziones, or an empty list if no matches were found
	 */
	@Override
	public List<UtenteOrganizzazione>
		getUtenteOrganizzazionesByUuidAndCompanyId(
			String uuid, long companyId) {

		return utenteOrganizzazionePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of utente organizzaziones matching the UUID and company.
	 *
	 * @param uuid the UUID of the utente organizzaziones
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of utente organizzaziones
	 * @param end the upper bound of the range of utente organizzaziones (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching utente organizzaziones, or an empty list if no matches were found
	 */
	@Override
	public List<UtenteOrganizzazione>
		getUtenteOrganizzazionesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<UtenteOrganizzazione> orderByComparator) {

		return utenteOrganizzazionePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the utente organizzazione matching the UUID and group.
	 *
	 * @param uuid the utente organizzazione's UUID
	 * @param groupId the primary key of the group
	 * @return the matching utente organizzazione
	 * @throws PortalException if a matching utente organizzazione could not be found
	 */
	@Override
	public UtenteOrganizzazione getUtenteOrganizzazioneByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return utenteOrganizzazionePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the utente organizzaziones.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.profiloutente.model.impl.UtenteOrganizzazioneModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of utente organizzaziones
	 * @param end the upper bound of the range of utente organizzaziones (not inclusive)
	 * @return the range of utente organizzaziones
	 */
	@Override
	public List<UtenteOrganizzazione> getUtenteOrganizzaziones(
		int start, int end) {

		return utenteOrganizzazionePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of utente organizzaziones.
	 *
	 * @return the number of utente organizzaziones
	 */
	@Override
	public int getUtenteOrganizzazionesCount() {
		return utenteOrganizzazionePersistence.countAll();
	}

	/**
	 * Updates the utente organizzazione in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UtenteOrganizzazioneLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param utenteOrganizzazione the utente organizzazione
	 * @return the utente organizzazione that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UtenteOrganizzazione updateUtenteOrganizzazione(
		UtenteOrganizzazione utenteOrganizzazione) {

		return utenteOrganizzazionePersistence.update(utenteOrganizzazione);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			UtenteOrganizzazioneLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		utenteOrganizzazioneLocalService =
			(UtenteOrganizzazioneLocalService)aopProxy;

		_setLocalServiceUtilService(utenteOrganizzazioneLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return UtenteOrganizzazioneLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return UtenteOrganizzazione.class;
	}

	protected String getModelClassName() {
		return UtenteOrganizzazione.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				utenteOrganizzazionePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		UtenteOrganizzazioneLocalService utenteOrganizzazioneLocalService) {

		try {
			Field field =
				UtenteOrganizzazioneLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, utenteOrganizzazioneLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CanaleComunicazionePersistence canaleComunicazionePersistence;

	protected UtenteOrganizzazioneLocalService utenteOrganizzazioneLocalService;

	@Reference
	protected UtenteOrganizzazionePersistence utenteOrganizzazionePersistence;

	@Reference
	protected UtenteOrganizzazioneCanaleComunicazionePersistence
		utenteOrganizzazioneCanaleComunicazionePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}