/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.scrivaniaoperatore.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AllegatoRichiesta service. Represents a row in the &quot;allegato_richiesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.scrivaniaoperatore.model.impl.AllegatoRichiestaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.scrivaniaoperatore.model.impl.AllegatoRichiestaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AllegatoRichiesta
 * @generated
 */
@ProviderType
public interface AllegatoRichiestaModel
	extends BaseModel<AllegatoRichiesta>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a allegato richiesta model instance should use the {@link AllegatoRichiesta} interface instead.
	 */

	/**
	 * Returns the primary key of this allegato richiesta.
	 *
	 * @return the primary key of this allegato richiesta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this allegato richiesta.
	 *
	 * @param primaryKey the primary key of this allegato richiesta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this allegato richiesta.
	 *
	 * @return the uuid of this allegato richiesta
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this allegato richiesta.
	 *
	 * @param uuid the uuid of this allegato richiesta
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the allegato richiesta ID of this allegato richiesta.
	 *
	 * @return the allegato richiesta ID of this allegato richiesta
	 */
	public long getAllegatoRichiestaId();

	/**
	 * Sets the allegato richiesta ID of this allegato richiesta.
	 *
	 * @param allegatoRichiestaId the allegato richiesta ID of this allegato richiesta
	 */
	public void setAllegatoRichiestaId(long allegatoRichiestaId);

	/**
	 * Returns the group ID of this allegato richiesta.
	 *
	 * @return the group ID of this allegato richiesta
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this allegato richiesta.
	 *
	 * @param groupId the group ID of this allegato richiesta
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this allegato richiesta.
	 *
	 * @return the company ID of this allegato richiesta
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this allegato richiesta.
	 *
	 * @param companyId the company ID of this allegato richiesta
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this allegato richiesta.
	 *
	 * @return the user ID of this allegato richiesta
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this allegato richiesta.
	 *
	 * @param userId the user ID of this allegato richiesta
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this allegato richiesta.
	 *
	 * @return the user uuid of this allegato richiesta
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this allegato richiesta.
	 *
	 * @param userUuid the user uuid of this allegato richiesta
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this allegato richiesta.
	 *
	 * @return the user name of this allegato richiesta
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this allegato richiesta.
	 *
	 * @param userName the user name of this allegato richiesta
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this allegato richiesta.
	 *
	 * @return the create date of this allegato richiesta
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this allegato richiesta.
	 *
	 * @param createDate the create date of this allegato richiesta
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this allegato richiesta.
	 *
	 * @return the modified date of this allegato richiesta
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this allegato richiesta.
	 *
	 * @param modifiedDate the modified date of this allegato richiesta
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the id documentale of this allegato richiesta.
	 *
	 * @return the id documentale of this allegato richiesta
	 */
	@AutoEscape
	public String getIdDocumentale();

	/**
	 * Sets the id documentale of this allegato richiesta.
	 *
	 * @param idDocumentale the id documentale of this allegato richiesta
	 */
	public void setIdDocumentale(String idDocumentale);

	/**
	 * Returns the nome of this allegato richiesta.
	 *
	 * @return the nome of this allegato richiesta
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this allegato richiesta.
	 *
	 * @param nome the nome of this allegato richiesta
	 */
	public void setNome(String nome);

	/**
	 * Returns the titolo of this allegato richiesta.
	 *
	 * @return the titolo of this allegato richiesta
	 */
	@AutoEscape
	public String getTitolo();

	/**
	 * Sets the titolo of this allegato richiesta.
	 *
	 * @param titolo the titolo of this allegato richiesta
	 */
	public void setTitolo(String titolo);

	/**
	 * Returns the descrizione of this allegato richiesta.
	 *
	 * @return the descrizione of this allegato richiesta
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this allegato richiesta.
	 *
	 * @param descrizione the descrizione of this allegato richiesta
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the url of this allegato richiesta.
	 *
	 * @return the url of this allegato richiesta
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this allegato richiesta.
	 *
	 * @param url the url of this allegato richiesta
	 */
	public void setUrl(String url);

	/**
	 * Returns the principale of this allegato richiesta.
	 *
	 * @return the principale of this allegato richiesta
	 */
	public boolean getPrincipale();

	/**
	 * Returns <code>true</code> if this allegato richiesta is principale.
	 *
	 * @return <code>true</code> if this allegato richiesta is principale; <code>false</code> otherwise
	 */
	public boolean isPrincipale();

	/**
	 * Sets whether this allegato richiesta is principale.
	 *
	 * @param principale the principale of this allegato richiesta
	 */
	public void setPrincipale(boolean principale);

	/**
	 * Returns the interno of this allegato richiesta.
	 *
	 * @return the interno of this allegato richiesta
	 */
	public boolean getInterno();

	/**
	 * Returns <code>true</code> if this allegato richiesta is interno.
	 *
	 * @return <code>true</code> if this allegato richiesta is interno; <code>false</code> otherwise
	 */
	public boolean isInterno();

	/**
	 * Sets whether this allegato richiesta is interno.
	 *
	 * @param interno the interno of this allegato richiesta
	 */
	public void setInterno(boolean interno);

	/**
	 * Returns the visibile of this allegato richiesta.
	 *
	 * @return the visibile of this allegato richiesta
	 */
	public boolean getVisibile();

	/**
	 * Returns <code>true</code> if this allegato richiesta is visibile.
	 *
	 * @return <code>true</code> if this allegato richiesta is visibile; <code>false</code> otherwise
	 */
	public boolean isVisibile();

	/**
	 * Sets whether this allegato richiesta is visibile.
	 *
	 * @param visibile the visibile of this allegato richiesta
	 */
	public void setVisibile(boolean visibile);

	/**
	 * Returns the definizione allegato ID of this allegato richiesta.
	 *
	 * @return the definizione allegato ID of this allegato richiesta
	 */
	public Long getDefinizioneAllegatoId();

	/**
	 * Sets the definizione allegato ID of this allegato richiesta.
	 *
	 * @param definizioneAllegatoId the definizione allegato ID of this allegato richiesta
	 */
	public void setDefinizioneAllegatoId(Long definizioneAllegatoId);

	/**
	 * Returns the richiesta ID of this allegato richiesta.
	 *
	 * @return the richiesta ID of this allegato richiesta
	 */
	public long getRichiestaId();

	/**
	 * Sets the richiesta ID of this allegato richiesta.
	 *
	 * @param richiestaId the richiesta ID of this allegato richiesta
	 */
	public void setRichiestaId(long richiestaId);

	@Override
	public AllegatoRichiesta cloneWithOriginalValues();

}