/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.scrivaniaoperatore.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AttivitaRichiesta service. Represents a row in the &quot;attivita_richiesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.scrivaniaoperatore.model.impl.AttivitaRichiestaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.scrivaniaoperatore.model.impl.AttivitaRichiestaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AttivitaRichiesta
 * @generated
 */
@ProviderType
public interface AttivitaRichiestaModel
	extends BaseModel<AttivitaRichiesta>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a attivita richiesta model instance should use the {@link AttivitaRichiesta} interface instead.
	 */

	/**
	 * Returns the primary key of this attivita richiesta.
	 *
	 * @return the primary key of this attivita richiesta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this attivita richiesta.
	 *
	 * @param primaryKey the primary key of this attivita richiesta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this attivita richiesta.
	 *
	 * @return the uuid of this attivita richiesta
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this attivita richiesta.
	 *
	 * @param uuid the uuid of this attivita richiesta
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the attivita richiesta ID of this attivita richiesta.
	 *
	 * @return the attivita richiesta ID of this attivita richiesta
	 */
	public long getAttivitaRichiestaId();

	/**
	 * Sets the attivita richiesta ID of this attivita richiesta.
	 *
	 * @param attivitaRichiestaId the attivita richiesta ID of this attivita richiesta
	 */
	public void setAttivitaRichiestaId(long attivitaRichiestaId);

	/**
	 * Returns the group ID of this attivita richiesta.
	 *
	 * @return the group ID of this attivita richiesta
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this attivita richiesta.
	 *
	 * @param groupId the group ID of this attivita richiesta
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this attivita richiesta.
	 *
	 * @return the company ID of this attivita richiesta
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this attivita richiesta.
	 *
	 * @param companyId the company ID of this attivita richiesta
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this attivita richiesta.
	 *
	 * @return the user ID of this attivita richiesta
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this attivita richiesta.
	 *
	 * @param userId the user ID of this attivita richiesta
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this attivita richiesta.
	 *
	 * @return the user uuid of this attivita richiesta
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this attivita richiesta.
	 *
	 * @param userUuid the user uuid of this attivita richiesta
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this attivita richiesta.
	 *
	 * @return the user name of this attivita richiesta
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this attivita richiesta.
	 *
	 * @param userName the user name of this attivita richiesta
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this attivita richiesta.
	 *
	 * @return the create date of this attivita richiesta
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this attivita richiesta.
	 *
	 * @param createDate the create date of this attivita richiesta
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this attivita richiesta.
	 *
	 * @return the modified date of this attivita richiesta
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this attivita richiesta.
	 *
	 * @param modifiedDate the modified date of this attivita richiesta
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the note of this attivita richiesta.
	 *
	 * @return the note of this attivita richiesta
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this attivita richiesta.
	 *
	 * @param note the note of this attivita richiesta
	 */
	public void setNote(String note);

	/**
	 * Returns the stato of this attivita richiesta.
	 *
	 * @return the stato of this attivita richiesta
	 */
	@AutoEscape
	public String getStato();

	/**
	 * Sets the stato of this attivita richiesta.
	 *
	 * @param stato the stato of this attivita richiesta
	 */
	public void setStato(String stato);

	/**
	 * Returns the richiesta ID of this attivita richiesta.
	 *
	 * @return the richiesta ID of this attivita richiesta
	 */
	public long getRichiestaId();

	/**
	 * Sets the richiesta ID of this attivita richiesta.
	 *
	 * @param richiestaId the richiesta ID of this attivita richiesta
	 */
	public void setRichiestaId(long richiestaId);

	@Override
	public AttivitaRichiesta cloneWithOriginalValues();

}