/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.scrivaniaoperatore.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CommentoRichiesta service. Represents a row in the &quot;commento_richiesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.scrivaniaoperatore.model.impl.CommentoRichiestaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.scrivaniaoperatore.model.impl.CommentoRichiestaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommentoRichiesta
 * @generated
 */
@ProviderType
public interface CommentoRichiestaModel
	extends BaseModel<CommentoRichiesta>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commento richiesta model instance should use the {@link CommentoRichiesta} interface instead.
	 */

	/**
	 * Returns the primary key of this commento richiesta.
	 *
	 * @return the primary key of this commento richiesta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commento richiesta.
	 *
	 * @param primaryKey the primary key of this commento richiesta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this commento richiesta.
	 *
	 * @return the uuid of this commento richiesta
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this commento richiesta.
	 *
	 * @param uuid the uuid of this commento richiesta
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the commento richiesta ID of this commento richiesta.
	 *
	 * @return the commento richiesta ID of this commento richiesta
	 */
	public long getCommentoRichiestaId();

	/**
	 * Sets the commento richiesta ID of this commento richiesta.
	 *
	 * @param commentoRichiestaId the commento richiesta ID of this commento richiesta
	 */
	public void setCommentoRichiestaId(long commentoRichiestaId);

	/**
	 * Returns the group ID of this commento richiesta.
	 *
	 * @return the group ID of this commento richiesta
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this commento richiesta.
	 *
	 * @param groupId the group ID of this commento richiesta
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this commento richiesta.
	 *
	 * @return the company ID of this commento richiesta
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commento richiesta.
	 *
	 * @param companyId the company ID of this commento richiesta
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commento richiesta.
	 *
	 * @return the user ID of this commento richiesta
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commento richiesta.
	 *
	 * @param userId the user ID of this commento richiesta
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commento richiesta.
	 *
	 * @return the user uuid of this commento richiesta
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commento richiesta.
	 *
	 * @param userUuid the user uuid of this commento richiesta
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commento richiesta.
	 *
	 * @return the user name of this commento richiesta
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commento richiesta.
	 *
	 * @param userName the user name of this commento richiesta
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commento richiesta.
	 *
	 * @return the create date of this commento richiesta
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commento richiesta.
	 *
	 * @param createDate the create date of this commento richiesta
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commento richiesta.
	 *
	 * @return the modified date of this commento richiesta
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commento richiesta.
	 *
	 * @param modifiedDate the modified date of this commento richiesta
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the testo of this commento richiesta.
	 *
	 * @return the testo of this commento richiesta
	 */
	@AutoEscape
	public String getTesto();

	/**
	 * Sets the testo of this commento richiesta.
	 *
	 * @param testo the testo of this commento richiesta
	 */
	public void setTesto(String testo);

	/**
	 * Returns the task ID of this commento richiesta.
	 *
	 * @return the task ID of this commento richiesta
	 */
	@AutoEscape
	public String getTaskId();

	/**
	 * Sets the task ID of this commento richiesta.
	 *
	 * @param taskId the task ID of this commento richiesta
	 */
	public void setTaskId(String taskId);

	/**
	 * Returns the visibile of this commento richiesta.
	 *
	 * @return the visibile of this commento richiesta
	 */
	public boolean getVisibile();

	/**
	 * Returns <code>true</code> if this commento richiesta is visibile.
	 *
	 * @return <code>true</code> if this commento richiesta is visibile; <code>false</code> otherwise
	 */
	public boolean isVisibile();

	/**
	 * Sets whether this commento richiesta is visibile.
	 *
	 * @param visibile the visibile of this commento richiesta
	 */
	public void setVisibile(boolean visibile);

	/**
	 * Returns the richiesta ID of this commento richiesta.
	 *
	 * @return the richiesta ID of this commento richiesta
	 */
	public long getRichiestaId();

	/**
	 * Sets the richiesta ID of this commento richiesta.
	 *
	 * @param richiestaId the richiesta ID of this commento richiesta
	 */
	public void setRichiestaId(long richiestaId);

	@Override
	public CommentoRichiesta cloneWithOriginalValues();

}