/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.scrivaniaoperatore.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import it.servizidigitali.scrivaniaoperatore.service.persistence.DestinazioneUsoServizioEntePK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DestinazioneUsoServizioEnte service. Represents a row in the &quot;destinazione_uso_servizio_ente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.scrivaniaoperatore.model.impl.DestinazioneUsoServizioEnteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.scrivaniaoperatore.model.impl.DestinazioneUsoServizioEnteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DestinazioneUsoServizioEnte
 * @generated
 */
@ProviderType
public interface DestinazioneUsoServizioEnteModel
	extends BaseModel<DestinazioneUsoServizioEnte>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a destinazione uso servizio ente model instance should use the {@link DestinazioneUsoServizioEnte} interface instead.
	 */

	/**
	 * Returns the primary key of this destinazione uso servizio ente.
	 *
	 * @return the primary key of this destinazione uso servizio ente
	 */
	public DestinazioneUsoServizioEntePK getPrimaryKey();

	/**
	 * Sets the primary key of this destinazione uso servizio ente.
	 *
	 * @param primaryKey the primary key of this destinazione uso servizio ente
	 */
	public void setPrimaryKey(DestinazioneUsoServizioEntePK primaryKey);

	/**
	 * Returns the uuid of this destinazione uso servizio ente.
	 *
	 * @return the uuid of this destinazione uso servizio ente
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this destinazione uso servizio ente.
	 *
	 * @param uuid the uuid of this destinazione uso servizio ente
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the destinazione uso ID of this destinazione uso servizio ente.
	 *
	 * @return the destinazione uso ID of this destinazione uso servizio ente
	 */
	public long getDestinazioneUsoId();

	/**
	 * Sets the destinazione uso ID of this destinazione uso servizio ente.
	 *
	 * @param destinazioneUsoId the destinazione uso ID of this destinazione uso servizio ente
	 */
	public void setDestinazioneUsoId(long destinazioneUsoId);

	/**
	 * Returns the servizio ID of this destinazione uso servizio ente.
	 *
	 * @return the servizio ID of this destinazione uso servizio ente
	 */
	public long getServizioId();

	/**
	 * Sets the servizio ID of this destinazione uso servizio ente.
	 *
	 * @param servizioId the servizio ID of this destinazione uso servizio ente
	 */
	public void setServizioId(long servizioId);

	/**
	 * Returns the organization ID of this destinazione uso servizio ente.
	 *
	 * @return the organization ID of this destinazione uso servizio ente
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this destinazione uso servizio ente.
	 *
	 * @param organizationId the organization ID of this destinazione uso servizio ente
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the group ID of this destinazione uso servizio ente.
	 *
	 * @return the group ID of this destinazione uso servizio ente
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this destinazione uso servizio ente.
	 *
	 * @param groupId the group ID of this destinazione uso servizio ente
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this destinazione uso servizio ente.
	 *
	 * @return the company ID of this destinazione uso servizio ente
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this destinazione uso servizio ente.
	 *
	 * @param companyId the company ID of this destinazione uso servizio ente
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this destinazione uso servizio ente.
	 *
	 * @return the user ID of this destinazione uso servizio ente
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this destinazione uso servizio ente.
	 *
	 * @param userId the user ID of this destinazione uso servizio ente
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this destinazione uso servizio ente.
	 *
	 * @return the user uuid of this destinazione uso servizio ente
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this destinazione uso servizio ente.
	 *
	 * @param userUuid the user uuid of this destinazione uso servizio ente
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this destinazione uso servizio ente.
	 *
	 * @return the user name of this destinazione uso servizio ente
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this destinazione uso servizio ente.
	 *
	 * @param userName the user name of this destinazione uso servizio ente
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this destinazione uso servizio ente.
	 *
	 * @return the create date of this destinazione uso servizio ente
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this destinazione uso servizio ente.
	 *
	 * @param createDate the create date of this destinazione uso servizio ente
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this destinazione uso servizio ente.
	 *
	 * @return the modified date of this destinazione uso servizio ente
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this destinazione uso servizio ente.
	 *
	 * @param modifiedDate the modified date of this destinazione uso servizio ente
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public DestinazioneUsoServizioEnte cloneWithOriginalValues();

}