/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.scrivaniaoperatore.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.math.BigDecimal;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DestinazioneUso service. Represents a row in the &quot;destinazione_uso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.scrivaniaoperatore.model.impl.DestinazioneUsoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.scrivaniaoperatore.model.impl.DestinazioneUsoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DestinazioneUso
 * @generated
 */
@ProviderType
public interface DestinazioneUsoModel
	extends BaseModel<DestinazioneUso>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a destinazione uso model instance should use the {@link DestinazioneUso} interface instead.
	 */

	/**
	 * Returns the primary key of this destinazione uso.
	 *
	 * @return the primary key of this destinazione uso
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this destinazione uso.
	 *
	 * @param primaryKey the primary key of this destinazione uso
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this destinazione uso.
	 *
	 * @return the uuid of this destinazione uso
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this destinazione uso.
	 *
	 * @param uuid the uuid of this destinazione uso
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the destinazione uso ID of this destinazione uso.
	 *
	 * @return the destinazione uso ID of this destinazione uso
	 */
	public long getDestinazioneUsoId();

	/**
	 * Sets the destinazione uso ID of this destinazione uso.
	 *
	 * @param destinazioneUsoId the destinazione uso ID of this destinazione uso
	 */
	public void setDestinazioneUsoId(long destinazioneUsoId);

	/**
	 * Returns the group ID of this destinazione uso.
	 *
	 * @return the group ID of this destinazione uso
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this destinazione uso.
	 *
	 * @param groupId the group ID of this destinazione uso
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this destinazione uso.
	 *
	 * @return the company ID of this destinazione uso
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this destinazione uso.
	 *
	 * @param companyId the company ID of this destinazione uso
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this destinazione uso.
	 *
	 * @return the user ID of this destinazione uso
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this destinazione uso.
	 *
	 * @param userId the user ID of this destinazione uso
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this destinazione uso.
	 *
	 * @return the user uuid of this destinazione uso
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this destinazione uso.
	 *
	 * @param userUuid the user uuid of this destinazione uso
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this destinazione uso.
	 *
	 * @return the user name of this destinazione uso
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this destinazione uso.
	 *
	 * @param userName the user name of this destinazione uso
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this destinazione uso.
	 *
	 * @return the create date of this destinazione uso
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this destinazione uso.
	 *
	 * @param createDate the create date of this destinazione uso
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this destinazione uso.
	 *
	 * @return the modified date of this destinazione uso
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this destinazione uso.
	 *
	 * @param modifiedDate the modified date of this destinazione uso
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this destinazione uso.
	 *
	 * @return the nome of this destinazione uso
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this destinazione uso.
	 *
	 * @param nome the nome of this destinazione uso
	 */
	public void setNome(String nome);

	/**
	 * Returns the descrizione of this destinazione uso.
	 *
	 * @return the descrizione of this destinazione uso
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this destinazione uso.
	 *
	 * @param descrizione the descrizione of this destinazione uso
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the pagamento bollo of this destinazione uso.
	 *
	 * @return the pagamento bollo of this destinazione uso
	 */
	public boolean getPagamentoBollo();

	/**
	 * Returns <code>true</code> if this destinazione uso is pagamento bollo.
	 *
	 * @return <code>true</code> if this destinazione uso is pagamento bollo; <code>false</code> otherwise
	 */
	public boolean isPagamentoBollo();

	/**
	 * Sets whether this destinazione uso is pagamento bollo.
	 *
	 * @param pagamentoBollo the pagamento bollo of this destinazione uso
	 */
	public void setPagamentoBollo(boolean pagamentoBollo);

	/**
	 * Returns the importo of this destinazione uso.
	 *
	 * @return the importo of this destinazione uso
	 */
	public BigDecimal getImporto();

	/**
	 * Sets the importo of this destinazione uso.
	 *
	 * @param importo the importo of this destinazione uso
	 */
	public void setImporto(BigDecimal importo);

	@Override
	public DestinazioneUso cloneWithOriginalValues();

}