/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.scrivaniaoperatore.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the IstanzaForm service. Represents a row in the &quot;istanza_form&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.scrivaniaoperatore.model.impl.IstanzaFormModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.scrivaniaoperatore.model.impl.IstanzaFormImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IstanzaForm
 * @generated
 */
@ProviderType
public interface IstanzaFormModel
	extends BaseModel<IstanzaForm>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a istanza form model instance should use the {@link IstanzaForm} interface instead.
	 */

	/**
	 * Returns the primary key of this istanza form.
	 *
	 * @return the primary key of this istanza form
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this istanza form.
	 *
	 * @param primaryKey the primary key of this istanza form
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this istanza form.
	 *
	 * @return the uuid of this istanza form
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this istanza form.
	 *
	 * @param uuid the uuid of this istanza form
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the istanza form ID of this istanza form.
	 *
	 * @return the istanza form ID of this istanza form
	 */
	public long getIstanzaFormId();

	/**
	 * Sets the istanza form ID of this istanza form.
	 *
	 * @param istanzaFormId the istanza form ID of this istanza form
	 */
	public void setIstanzaFormId(long istanzaFormId);

	/**
	 * Returns the group ID of this istanza form.
	 *
	 * @return the group ID of this istanza form
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this istanza form.
	 *
	 * @param groupId the group ID of this istanza form
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this istanza form.
	 *
	 * @return the company ID of this istanza form
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this istanza form.
	 *
	 * @param companyId the company ID of this istanza form
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this istanza form.
	 *
	 * @return the user ID of this istanza form
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this istanza form.
	 *
	 * @param userId the user ID of this istanza form
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this istanza form.
	 *
	 * @return the user uuid of this istanza form
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this istanza form.
	 *
	 * @param userUuid the user uuid of this istanza form
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this istanza form.
	 *
	 * @return the user name of this istanza form
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this istanza form.
	 *
	 * @param userName the user name of this istanza form
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this istanza form.
	 *
	 * @return the create date of this istanza form
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this istanza form.
	 *
	 * @param createDate the create date of this istanza form
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this istanza form.
	 *
	 * @return the modified date of this istanza form
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this istanza form.
	 *
	 * @param modifiedDate the modified date of this istanza form
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the json of this istanza form.
	 *
	 * @return the json of this istanza form
	 */
	@AutoEscape
	public String getJson();

	/**
	 * Sets the json of this istanza form.
	 *
	 * @param json the json of this istanza form
	 */
	public void setJson(String json);

	/**
	 * Returns the form ID of this istanza form.
	 *
	 * @return the form ID of this istanza form
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this istanza form.
	 *
	 * @param formId the form ID of this istanza form
	 */
	public void setFormId(long formId);

	/**
	 * Returns the richiesta ID of this istanza form.
	 *
	 * @return the richiesta ID of this istanza form
	 */
	public long getRichiestaId();

	/**
	 * Sets the richiesta ID of this istanza form.
	 *
	 * @param richiestaId the richiesta ID of this istanza form
	 */
	public void setRichiestaId(long richiestaId);

	@Override
	public IstanzaForm cloneWithOriginalValues();

}