/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.scrivaniaoperatore.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.servizidigitali.scrivaniaoperatore.model.AttivitaRichiesta;
import it.servizidigitali.scrivaniaoperatore.model.AttivitaRichiestaModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AttivitaRichiesta service. Represents a row in the &quot;attivita_richiesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AttivitaRichiestaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AttivitaRichiestaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AttivitaRichiestaImpl
 * @generated
 */
public class AttivitaRichiestaModelImpl
	extends BaseModelImpl<AttivitaRichiesta> implements AttivitaRichiestaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a attivita richiesta model instance should use the <code>AttivitaRichiesta</code> interface instead.
	 */
	public static final String TABLE_NAME = "attivita_richiesta";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"attivitaRichiestaId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"note", Types.VARCHAR}, {"stato", Types.VARCHAR},
		{"richiestaId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("attivitaRichiestaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("note", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stato", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("richiestaId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table attivita_richiesta (uuid_ VARCHAR(75) null,attivitaRichiestaId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,note VARCHAR(75) null,stato VARCHAR(75) null,richiestaId LONG)";

	public static final String TABLE_SQL_DROP = "drop table attivita_richiesta";

	public static final String ORDER_BY_JPQL =
		" ORDER BY attivitaRichiesta.attivitaRichiestaId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY attivita_richiesta.attivitaRichiestaId ASC";

	public static final String DATA_SOURCE = "servizidigitaliDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RICHIESTAID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ATTIVITARICHIESTAID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AttivitaRichiestaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _attivitaRichiestaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAttivitaRichiestaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _attivitaRichiestaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AttivitaRichiesta.class;
	}

	@Override
	public String getModelClassName() {
		return AttivitaRichiesta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AttivitaRichiesta, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AttivitaRichiesta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AttivitaRichiesta, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AttivitaRichiesta)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AttivitaRichiesta, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AttivitaRichiesta, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AttivitaRichiesta)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AttivitaRichiesta, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AttivitaRichiesta, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AttivitaRichiesta>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AttivitaRichiesta.class.getClassLoader(), AttivitaRichiesta.class,
			ModelWrapper.class);

		try {
			Constructor<AttivitaRichiesta> constructor =
				(Constructor<AttivitaRichiesta>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<AttivitaRichiesta, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AttivitaRichiesta, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AttivitaRichiesta, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<AttivitaRichiesta, Object>>();
		Map<String, BiConsumer<AttivitaRichiesta, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<AttivitaRichiesta, ?>>();

		attributeGetterFunctions.put("uuid", AttivitaRichiesta::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<AttivitaRichiesta, String>)AttivitaRichiesta::setUuid);
		attributeGetterFunctions.put(
			"attivitaRichiestaId", AttivitaRichiesta::getAttivitaRichiestaId);
		attributeSetterBiConsumers.put(
			"attivitaRichiestaId",
			(BiConsumer<AttivitaRichiesta, Long>)
				AttivitaRichiesta::setAttivitaRichiestaId);
		attributeGetterFunctions.put("groupId", AttivitaRichiesta::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<AttivitaRichiesta, Long>)AttivitaRichiesta::setGroupId);
		attributeGetterFunctions.put(
			"companyId", AttivitaRichiesta::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AttivitaRichiesta, Long>)
				AttivitaRichiesta::setCompanyId);
		attributeGetterFunctions.put("userId", AttivitaRichiesta::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<AttivitaRichiesta, Long>)AttivitaRichiesta::setUserId);
		attributeGetterFunctions.put(
			"userName", AttivitaRichiesta::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<AttivitaRichiesta, String>)
				AttivitaRichiesta::setUserName);
		attributeGetterFunctions.put(
			"createDate", AttivitaRichiesta::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<AttivitaRichiesta, Date>)
				AttivitaRichiesta::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", AttivitaRichiesta::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AttivitaRichiesta, Date>)
				AttivitaRichiesta::setModifiedDate);
		attributeGetterFunctions.put("note", AttivitaRichiesta::getNote);
		attributeSetterBiConsumers.put(
			"note",
			(BiConsumer<AttivitaRichiesta, String>)AttivitaRichiesta::setNote);
		attributeGetterFunctions.put("stato", AttivitaRichiesta::getStato);
		attributeSetterBiConsumers.put(
			"stato",
			(BiConsumer<AttivitaRichiesta, String>)AttivitaRichiesta::setStato);
		attributeGetterFunctions.put(
			"richiestaId", AttivitaRichiesta::getRichiestaId);
		attributeSetterBiConsumers.put(
			"richiestaId",
			(BiConsumer<AttivitaRichiesta, Long>)
				AttivitaRichiesta::setRichiestaId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getAttivitaRichiestaId() {
		return _attivitaRichiestaId;
	}

	@Override
	public void setAttivitaRichiestaId(long attivitaRichiestaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_attivitaRichiestaId = attivitaRichiestaId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getNote() {
		if (_note == null) {
			return "";
		}
		else {
			return _note;
		}
	}

	@Override
	public void setNote(String note) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_note = note;
	}

	@Override
	public String getStato() {
		if (_stato == null) {
			return "";
		}
		else {
			return _stato;
		}
	}

	@Override
	public void setStato(String stato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stato = stato;
	}

	@Override
	public long getRichiestaId() {
		return _richiestaId;
	}

	@Override
	public void setRichiestaId(long richiestaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_richiestaId = richiestaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalRichiestaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("richiestaId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AttivitaRichiesta.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AttivitaRichiesta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AttivitaRichiesta toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AttivitaRichiesta>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AttivitaRichiestaImpl attivitaRichiestaImpl =
			new AttivitaRichiestaImpl();

		attivitaRichiestaImpl.setUuid(getUuid());
		attivitaRichiestaImpl.setAttivitaRichiestaId(getAttivitaRichiestaId());
		attivitaRichiestaImpl.setGroupId(getGroupId());
		attivitaRichiestaImpl.setCompanyId(getCompanyId());
		attivitaRichiestaImpl.setUserId(getUserId());
		attivitaRichiestaImpl.setUserName(getUserName());
		attivitaRichiestaImpl.setCreateDate(getCreateDate());
		attivitaRichiestaImpl.setModifiedDate(getModifiedDate());
		attivitaRichiestaImpl.setNote(getNote());
		attivitaRichiestaImpl.setStato(getStato());
		attivitaRichiestaImpl.setRichiestaId(getRichiestaId());

		attivitaRichiestaImpl.resetOriginalValues();

		return attivitaRichiestaImpl;
	}

	@Override
	public AttivitaRichiesta cloneWithOriginalValues() {
		AttivitaRichiestaImpl attivitaRichiestaImpl =
			new AttivitaRichiestaImpl();

		attivitaRichiestaImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		attivitaRichiestaImpl.setAttivitaRichiestaId(
			this.<Long>getColumnOriginalValue("attivitaRichiestaId"));
		attivitaRichiestaImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		attivitaRichiestaImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		attivitaRichiestaImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		attivitaRichiestaImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		attivitaRichiestaImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		attivitaRichiestaImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		attivitaRichiestaImpl.setNote(
			this.<String>getColumnOriginalValue("note"));
		attivitaRichiestaImpl.setStato(
			this.<String>getColumnOriginalValue("stato"));
		attivitaRichiestaImpl.setRichiestaId(
			this.<Long>getColumnOriginalValue("richiestaId"));

		return attivitaRichiestaImpl;
	}

	@Override
	public int compareTo(AttivitaRichiesta attivitaRichiesta) {
		long primaryKey = attivitaRichiesta.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AttivitaRichiesta)) {
			return false;
		}

		AttivitaRichiesta attivitaRichiesta = (AttivitaRichiesta)object;

		long primaryKey = attivitaRichiesta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AttivitaRichiesta> toCacheModel() {
		AttivitaRichiestaCacheModel attivitaRichiestaCacheModel =
			new AttivitaRichiestaCacheModel();

		attivitaRichiestaCacheModel.uuid = getUuid();

		String uuid = attivitaRichiestaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			attivitaRichiestaCacheModel.uuid = null;
		}

		attivitaRichiestaCacheModel.attivitaRichiestaId =
			getAttivitaRichiestaId();

		attivitaRichiestaCacheModel.groupId = getGroupId();

		attivitaRichiestaCacheModel.companyId = getCompanyId();

		attivitaRichiestaCacheModel.userId = getUserId();

		attivitaRichiestaCacheModel.userName = getUserName();

		String userName = attivitaRichiestaCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			attivitaRichiestaCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			attivitaRichiestaCacheModel.createDate = createDate.getTime();
		}
		else {
			attivitaRichiestaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			attivitaRichiestaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			attivitaRichiestaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		attivitaRichiestaCacheModel.note = getNote();

		String note = attivitaRichiestaCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			attivitaRichiestaCacheModel.note = null;
		}

		attivitaRichiestaCacheModel.stato = getStato();

		String stato = attivitaRichiestaCacheModel.stato;

		if ((stato != null) && (stato.length() == 0)) {
			attivitaRichiestaCacheModel.stato = null;
		}

		attivitaRichiestaCacheModel.richiestaId = getRichiestaId();

		return attivitaRichiestaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AttivitaRichiesta, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AttivitaRichiesta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AttivitaRichiesta, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AttivitaRichiesta)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AttivitaRichiesta, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AttivitaRichiesta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AttivitaRichiesta, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AttivitaRichiesta)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AttivitaRichiesta>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _attivitaRichiestaId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _note;
	private String _stato;
	private long _richiestaId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AttivitaRichiesta, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AttivitaRichiesta)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("attivitaRichiestaId", _attivitaRichiestaId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("note", _note);
		_columnOriginalValues.put("stato", _stato);
		_columnOriginalValues.put("richiestaId", _richiestaId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("attivitaRichiestaId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("note", 256L);

		columnBitmasks.put("stato", 512L);

		columnBitmasks.put("richiestaId", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AttivitaRichiesta _escapedModel;

}