/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.scrivaniaoperatore.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.servizidigitali.scrivaniaoperatore.model.DestinazioneUso;
import it.servizidigitali.scrivaniaoperatore.model.DestinazioneUsoModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.math.BigDecimal;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DestinazioneUso service. Represents a row in the &quot;destinazione_uso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DestinazioneUsoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DestinazioneUsoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DestinazioneUsoImpl
 * @generated
 */
public class DestinazioneUsoModelImpl
	extends BaseModelImpl<DestinazioneUso> implements DestinazioneUsoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a destinazione uso model instance should use the <code>DestinazioneUso</code> interface instead.
	 */
	public static final String TABLE_NAME = "destinazione_uso";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"destinazioneUsoId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"nome", Types.VARCHAR}, {"descrizione", Types.VARCHAR},
		{"pagamentoBollo", Types.BOOLEAN}, {"importo", Types.DECIMAL}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("destinazioneUsoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pagamentoBollo", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("importo", Types.DECIMAL);
	}

	public static final String TABLE_SQL_CREATE =
		"create table destinazione_uso (uuid_ VARCHAR(75) null,destinazioneUsoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nome VARCHAR(75) null,descrizione VARCHAR(75) null,pagamentoBollo BOOLEAN,importo DECIMAL(30, 16) null)";

	public static final String TABLE_SQL_DROP = "drop table destinazione_uso";

	public static final String ORDER_BY_JPQL =
		" ORDER BY destinazioneUso.destinazioneUsoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY destinazione_uso.destinazioneUsoId ASC";

	public static final String DATA_SOURCE = "servizidigitaliDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PAGAMENTOBOLLO_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESTINAZIONEUSOID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DestinazioneUsoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _destinazioneUsoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDestinazioneUsoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _destinazioneUsoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DestinazioneUso.class;
	}

	@Override
	public String getModelClassName() {
		return DestinazioneUso.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DestinazioneUso, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DestinazioneUso, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DestinazioneUso, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DestinazioneUso)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DestinazioneUso, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DestinazioneUso, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DestinazioneUso)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DestinazioneUso, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DestinazioneUso, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DestinazioneUso>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DestinazioneUso.class.getClassLoader(), DestinazioneUso.class,
			ModelWrapper.class);

		try {
			Constructor<DestinazioneUso> constructor =
				(Constructor<DestinazioneUso>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<DestinazioneUso, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DestinazioneUso, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DestinazioneUso, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<DestinazioneUso, Object>>();
		Map<String, BiConsumer<DestinazioneUso, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DestinazioneUso, ?>>();

		attributeGetterFunctions.put("uuid", DestinazioneUso::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<DestinazioneUso, String>)DestinazioneUso::setUuid);
		attributeGetterFunctions.put(
			"destinazioneUsoId", DestinazioneUso::getDestinazioneUsoId);
		attributeSetterBiConsumers.put(
			"destinazioneUsoId",
			(BiConsumer<DestinazioneUso, Long>)
				DestinazioneUso::setDestinazioneUsoId);
		attributeGetterFunctions.put("groupId", DestinazioneUso::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<DestinazioneUso, Long>)DestinazioneUso::setGroupId);
		attributeGetterFunctions.put(
			"companyId", DestinazioneUso::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<DestinazioneUso, Long>)DestinazioneUso::setCompanyId);
		attributeGetterFunctions.put("userId", DestinazioneUso::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<DestinazioneUso, Long>)DestinazioneUso::setUserId);
		attributeGetterFunctions.put("userName", DestinazioneUso::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<DestinazioneUso, String>)DestinazioneUso::setUserName);
		attributeGetterFunctions.put(
			"createDate", DestinazioneUso::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DestinazioneUso, Date>)DestinazioneUso::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", DestinazioneUso::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DestinazioneUso, Date>)
				DestinazioneUso::setModifiedDate);
		attributeGetterFunctions.put("nome", DestinazioneUso::getNome);
		attributeSetterBiConsumers.put(
			"nome",
			(BiConsumer<DestinazioneUso, String>)DestinazioneUso::setNome);
		attributeGetterFunctions.put(
			"descrizione", DestinazioneUso::getDescrizione);
		attributeSetterBiConsumers.put(
			"descrizione",
			(BiConsumer<DestinazioneUso, String>)
				DestinazioneUso::setDescrizione);
		attributeGetterFunctions.put(
			"pagamentoBollo", DestinazioneUso::getPagamentoBollo);
		attributeSetterBiConsumers.put(
			"pagamentoBollo",
			(BiConsumer<DestinazioneUso, Boolean>)
				DestinazioneUso::setPagamentoBollo);
		attributeGetterFunctions.put("importo", DestinazioneUso::getImporto);
		attributeSetterBiConsumers.put(
			"importo",
			(BiConsumer<DestinazioneUso, BigDecimal>)
				DestinazioneUso::setImporto);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getDestinazioneUsoId() {
		return _destinazioneUsoId;
	}

	@Override
	public void setDestinazioneUsoId(long destinazioneUsoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_destinazioneUsoId = destinazioneUsoId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nome = nome;
	}

	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return "";
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descrizione = descrizione;
	}

	@Override
	public boolean getPagamentoBollo() {
		return _pagamentoBollo;
	}

	@Override
	public boolean isPagamentoBollo() {
		return _pagamentoBollo;
	}

	@Override
	public void setPagamentoBollo(boolean pagamentoBollo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pagamentoBollo = pagamentoBollo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalPagamentoBollo() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("pagamentoBollo"));
	}

	@Override
	public BigDecimal getImporto() {
		return _importo;
	}

	@Override
	public void setImporto(BigDecimal importo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_importo = importo;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(DestinazioneUso.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DestinazioneUso.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DestinazioneUso toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DestinazioneUso>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DestinazioneUsoImpl destinazioneUsoImpl = new DestinazioneUsoImpl();

		destinazioneUsoImpl.setUuid(getUuid());
		destinazioneUsoImpl.setDestinazioneUsoId(getDestinazioneUsoId());
		destinazioneUsoImpl.setGroupId(getGroupId());
		destinazioneUsoImpl.setCompanyId(getCompanyId());
		destinazioneUsoImpl.setUserId(getUserId());
		destinazioneUsoImpl.setUserName(getUserName());
		destinazioneUsoImpl.setCreateDate(getCreateDate());
		destinazioneUsoImpl.setModifiedDate(getModifiedDate());
		destinazioneUsoImpl.setNome(getNome());
		destinazioneUsoImpl.setDescrizione(getDescrizione());
		destinazioneUsoImpl.setPagamentoBollo(isPagamentoBollo());
		destinazioneUsoImpl.setImporto(getImporto());

		destinazioneUsoImpl.resetOriginalValues();

		return destinazioneUsoImpl;
	}

	@Override
	public DestinazioneUso cloneWithOriginalValues() {
		DestinazioneUsoImpl destinazioneUsoImpl = new DestinazioneUsoImpl();

		destinazioneUsoImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		destinazioneUsoImpl.setDestinazioneUsoId(
			this.<Long>getColumnOriginalValue("destinazioneUsoId"));
		destinazioneUsoImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		destinazioneUsoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		destinazioneUsoImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		destinazioneUsoImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		destinazioneUsoImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		destinazioneUsoImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		destinazioneUsoImpl.setNome(
			this.<String>getColumnOriginalValue("nome"));
		destinazioneUsoImpl.setDescrizione(
			this.<String>getColumnOriginalValue("descrizione"));
		destinazioneUsoImpl.setPagamentoBollo(
			this.<Boolean>getColumnOriginalValue("pagamentoBollo"));
		destinazioneUsoImpl.setImporto(
			this.<BigDecimal>getColumnOriginalValue("importo"));

		return destinazioneUsoImpl;
	}

	@Override
	public int compareTo(DestinazioneUso destinazioneUso) {
		long primaryKey = destinazioneUso.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DestinazioneUso)) {
			return false;
		}

		DestinazioneUso destinazioneUso = (DestinazioneUso)object;

		long primaryKey = destinazioneUso.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DestinazioneUso> toCacheModel() {
		DestinazioneUsoCacheModel destinazioneUsoCacheModel =
			new DestinazioneUsoCacheModel();

		destinazioneUsoCacheModel.uuid = getUuid();

		String uuid = destinazioneUsoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			destinazioneUsoCacheModel.uuid = null;
		}

		destinazioneUsoCacheModel.destinazioneUsoId = getDestinazioneUsoId();

		destinazioneUsoCacheModel.groupId = getGroupId();

		destinazioneUsoCacheModel.companyId = getCompanyId();

		destinazioneUsoCacheModel.userId = getUserId();

		destinazioneUsoCacheModel.userName = getUserName();

		String userName = destinazioneUsoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			destinazioneUsoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			destinazioneUsoCacheModel.createDate = createDate.getTime();
		}
		else {
			destinazioneUsoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			destinazioneUsoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			destinazioneUsoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		destinazioneUsoCacheModel.nome = getNome();

		String nome = destinazioneUsoCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			destinazioneUsoCacheModel.nome = null;
		}

		destinazioneUsoCacheModel.descrizione = getDescrizione();

		String descrizione = destinazioneUsoCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			destinazioneUsoCacheModel.descrizione = null;
		}

		destinazioneUsoCacheModel.pagamentoBollo = isPagamentoBollo();

		destinazioneUsoCacheModel.importo = getImporto();

		return destinazioneUsoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DestinazioneUso, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DestinazioneUso, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DestinazioneUso, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DestinazioneUso)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DestinazioneUso, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DestinazioneUso, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DestinazioneUso, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DestinazioneUso)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DestinazioneUso>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _destinazioneUsoId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _nome;
	private String _descrizione;
	private boolean _pagamentoBollo;
	private BigDecimal _importo;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<DestinazioneUso, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DestinazioneUso)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("destinazioneUsoId", _destinazioneUsoId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("nome", _nome);
		_columnOriginalValues.put("descrizione", _descrizione);
		_columnOriginalValues.put("pagamentoBollo", _pagamentoBollo);
		_columnOriginalValues.put("importo", _importo);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("destinazioneUsoId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("nome", 256L);

		columnBitmasks.put("descrizione", 512L);

		columnBitmasks.put("pagamentoBollo", 1024L);

		columnBitmasks.put("importo", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DestinazioneUso _escapedModel;

}