/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.scrivaniaoperatore.model.impl;

import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.servizidigitali.scrivaniaoperatore.model.DestinazioneUsoServizioEnte;
import it.servizidigitali.scrivaniaoperatore.model.DestinazioneUsoServizioEnteModel;
import it.servizidigitali.scrivaniaoperatore.service.persistence.DestinazioneUsoServizioEntePK;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DestinazioneUsoServizioEnte service. Represents a row in the &quot;destinazione_uso_servizio_ente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DestinazioneUsoServizioEnteModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DestinazioneUsoServizioEnteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DestinazioneUsoServizioEnteImpl
 * @generated
 */
public class DestinazioneUsoServizioEnteModelImpl
	extends BaseModelImpl<DestinazioneUsoServizioEnte>
	implements DestinazioneUsoServizioEnteModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a destinazione uso servizio ente model instance should use the <code>DestinazioneUsoServizioEnte</code> interface instead.
	 */
	public static final String TABLE_NAME = "destinazione_uso_servizio_ente";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"destinazioneUsoId", Types.BIGINT},
		{"servizioId", Types.BIGINT}, {"organizationId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("destinazioneUsoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("servizioId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("organizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table destinazione_uso_servizio_ente (uuid_ VARCHAR(75) null,destinazioneUsoId LONG not null,servizioId LONG not null,organizationId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,primary key (destinazioneUsoId, servizioId, organizationId))";

	public static final String TABLE_SQL_DROP =
		"drop table destinazione_uso_servizio_ente";

	public static final String ORDER_BY_JPQL =
		" ORDER BY destinazioneUsoServizioEnte.id.destinazioneUsoId ASC, destinazioneUsoServizioEnte.id.servizioId ASC, destinazioneUsoServizioEnte.id.organizationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY destinazione_uso_servizio_ente.destinazioneUsoId ASC, destinazione_uso_servizio_ente.servizioId ASC, destinazione_uso_servizio_ente.organizationId ASC";

	public static final String DATA_SOURCE = "servizidigitaliDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESTINAZIONEUSOID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ORGANIZATIONID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SERVIZIOID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DestinazioneUsoServizioEnteModelImpl() {
	}

	@Override
	public DestinazioneUsoServizioEntePK getPrimaryKey() {
		return new DestinazioneUsoServizioEntePK(
			_destinazioneUsoId, _servizioId, _organizationId);
	}

	@Override
	public void setPrimaryKey(DestinazioneUsoServizioEntePK primaryKey) {
		setDestinazioneUsoId(primaryKey.destinazioneUsoId);
		setServizioId(primaryKey.servizioId);
		setOrganizationId(primaryKey.organizationId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new DestinazioneUsoServizioEntePK(
			_destinazioneUsoId, _servizioId, _organizationId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((DestinazioneUsoServizioEntePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return DestinazioneUsoServizioEnte.class;
	}

	@Override
	public String getModelClassName() {
		return DestinazioneUsoServizioEnte.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DestinazioneUsoServizioEnte, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DestinazioneUsoServizioEnte, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DestinazioneUsoServizioEnte, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(DestinazioneUsoServizioEnte)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DestinazioneUsoServizioEnte, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DestinazioneUsoServizioEnte, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DestinazioneUsoServizioEnte)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DestinazioneUsoServizioEnte, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DestinazioneUsoServizioEnte, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DestinazioneUsoServizioEnte>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DestinazioneUsoServizioEnte.class.getClassLoader(),
			DestinazioneUsoServizioEnte.class, ModelWrapper.class);

		try {
			Constructor<DestinazioneUsoServizioEnte> constructor =
				(Constructor<DestinazioneUsoServizioEnte>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<DestinazioneUsoServizioEnte, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<DestinazioneUsoServizioEnte, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<DestinazioneUsoServizioEnte, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<DestinazioneUsoServizioEnte, Object>>();
		Map<String, BiConsumer<DestinazioneUsoServizioEnte, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<DestinazioneUsoServizioEnte, ?>>();

		attributeGetterFunctions.put(
			"uuid", DestinazioneUsoServizioEnte::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<DestinazioneUsoServizioEnte, String>)
				DestinazioneUsoServizioEnte::setUuid);
		attributeGetterFunctions.put(
			"destinazioneUsoId",
			DestinazioneUsoServizioEnte::getDestinazioneUsoId);
		attributeSetterBiConsumers.put(
			"destinazioneUsoId",
			(BiConsumer<DestinazioneUsoServizioEnte, Long>)
				DestinazioneUsoServizioEnte::setDestinazioneUsoId);
		attributeGetterFunctions.put(
			"servizioId", DestinazioneUsoServizioEnte::getServizioId);
		attributeSetterBiConsumers.put(
			"servizioId",
			(BiConsumer<DestinazioneUsoServizioEnte, Long>)
				DestinazioneUsoServizioEnte::setServizioId);
		attributeGetterFunctions.put(
			"organizationId", DestinazioneUsoServizioEnte::getOrganizationId);
		attributeSetterBiConsumers.put(
			"organizationId",
			(BiConsumer<DestinazioneUsoServizioEnte, Long>)
				DestinazioneUsoServizioEnte::setOrganizationId);
		attributeGetterFunctions.put(
			"groupId", DestinazioneUsoServizioEnte::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<DestinazioneUsoServizioEnte, Long>)
				DestinazioneUsoServizioEnte::setGroupId);
		attributeGetterFunctions.put(
			"companyId", DestinazioneUsoServizioEnte::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<DestinazioneUsoServizioEnte, Long>)
				DestinazioneUsoServizioEnte::setCompanyId);
		attributeGetterFunctions.put(
			"userId", DestinazioneUsoServizioEnte::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<DestinazioneUsoServizioEnte, Long>)
				DestinazioneUsoServizioEnte::setUserId);
		attributeGetterFunctions.put(
			"userName", DestinazioneUsoServizioEnte::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<DestinazioneUsoServizioEnte, String>)
				DestinazioneUsoServizioEnte::setUserName);
		attributeGetterFunctions.put(
			"createDate", DestinazioneUsoServizioEnte::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DestinazioneUsoServizioEnte, Date>)
				DestinazioneUsoServizioEnte::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", DestinazioneUsoServizioEnte::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DestinazioneUsoServizioEnte, Date>)
				DestinazioneUsoServizioEnte::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getDestinazioneUsoId() {
		return _destinazioneUsoId;
	}

	@Override
	public void setDestinazioneUsoId(long destinazioneUsoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_destinazioneUsoId = destinazioneUsoId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDestinazioneUsoId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("destinazioneUsoId"));
	}

	@Override
	public long getServizioId() {
		return _servizioId;
	}

	@Override
	public void setServizioId(long servizioId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_servizioId = servizioId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalServizioId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("servizioId"));
	}

	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_organizationId = organizationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalOrganizationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("organizationId"));
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				DestinazioneUsoServizioEnte.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public DestinazioneUsoServizioEnte toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DestinazioneUsoServizioEnte>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DestinazioneUsoServizioEnteImpl destinazioneUsoServizioEnteImpl =
			new DestinazioneUsoServizioEnteImpl();

		destinazioneUsoServizioEnteImpl.setUuid(getUuid());
		destinazioneUsoServizioEnteImpl.setDestinazioneUsoId(
			getDestinazioneUsoId());
		destinazioneUsoServizioEnteImpl.setServizioId(getServizioId());
		destinazioneUsoServizioEnteImpl.setOrganizationId(getOrganizationId());
		destinazioneUsoServizioEnteImpl.setGroupId(getGroupId());
		destinazioneUsoServizioEnteImpl.setCompanyId(getCompanyId());
		destinazioneUsoServizioEnteImpl.setUserId(getUserId());
		destinazioneUsoServizioEnteImpl.setUserName(getUserName());
		destinazioneUsoServizioEnteImpl.setCreateDate(getCreateDate());
		destinazioneUsoServizioEnteImpl.setModifiedDate(getModifiedDate());

		destinazioneUsoServizioEnteImpl.resetOriginalValues();

		return destinazioneUsoServizioEnteImpl;
	}

	@Override
	public DestinazioneUsoServizioEnte cloneWithOriginalValues() {
		DestinazioneUsoServizioEnteImpl destinazioneUsoServizioEnteImpl =
			new DestinazioneUsoServizioEnteImpl();

		destinazioneUsoServizioEnteImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		destinazioneUsoServizioEnteImpl.setDestinazioneUsoId(
			this.<Long>getColumnOriginalValue("destinazioneUsoId"));
		destinazioneUsoServizioEnteImpl.setServizioId(
			this.<Long>getColumnOriginalValue("servizioId"));
		destinazioneUsoServizioEnteImpl.setOrganizationId(
			this.<Long>getColumnOriginalValue("organizationId"));
		destinazioneUsoServizioEnteImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		destinazioneUsoServizioEnteImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		destinazioneUsoServizioEnteImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		destinazioneUsoServizioEnteImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		destinazioneUsoServizioEnteImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		destinazioneUsoServizioEnteImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return destinazioneUsoServizioEnteImpl;
	}

	@Override
	public int compareTo(
		DestinazioneUsoServizioEnte destinazioneUsoServizioEnte) {

		DestinazioneUsoServizioEntePK primaryKey =
			destinazioneUsoServizioEnte.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DestinazioneUsoServizioEnte)) {
			return false;
		}

		DestinazioneUsoServizioEnte destinazioneUsoServizioEnte =
			(DestinazioneUsoServizioEnte)object;

		DestinazioneUsoServizioEntePK primaryKey =
			destinazioneUsoServizioEnte.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DestinazioneUsoServizioEnte> toCacheModel() {
		DestinazioneUsoServizioEnteCacheModel
			destinazioneUsoServizioEnteCacheModel =
				new DestinazioneUsoServizioEnteCacheModel();

		destinazioneUsoServizioEnteCacheModel.destinazioneUsoServizioEntePK =
			getPrimaryKey();

		destinazioneUsoServizioEnteCacheModel.uuid = getUuid();

		String uuid = destinazioneUsoServizioEnteCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			destinazioneUsoServizioEnteCacheModel.uuid = null;
		}

		destinazioneUsoServizioEnteCacheModel.destinazioneUsoId =
			getDestinazioneUsoId();

		destinazioneUsoServizioEnteCacheModel.servizioId = getServizioId();

		destinazioneUsoServizioEnteCacheModel.organizationId =
			getOrganizationId();

		destinazioneUsoServizioEnteCacheModel.groupId = getGroupId();

		destinazioneUsoServizioEnteCacheModel.companyId = getCompanyId();

		destinazioneUsoServizioEnteCacheModel.userId = getUserId();

		destinazioneUsoServizioEnteCacheModel.userName = getUserName();

		String userName = destinazioneUsoServizioEnteCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			destinazioneUsoServizioEnteCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			destinazioneUsoServizioEnteCacheModel.createDate =
				createDate.getTime();
		}
		else {
			destinazioneUsoServizioEnteCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			destinazioneUsoServizioEnteCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			destinazioneUsoServizioEnteCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return destinazioneUsoServizioEnteCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DestinazioneUsoServizioEnte, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DestinazioneUsoServizioEnte, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DestinazioneUsoServizioEnte, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DestinazioneUsoServizioEnte)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DestinazioneUsoServizioEnte, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DestinazioneUsoServizioEnte, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DestinazioneUsoServizioEnte, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(DestinazioneUsoServizioEnte)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, DestinazioneUsoServizioEnte>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private String _uuid;
	private long _destinazioneUsoId;
	private long _servizioId;
	private long _organizationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<DestinazioneUsoServizioEnte, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DestinazioneUsoServizioEnte)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("destinazioneUsoId", _destinazioneUsoId);
		_columnOriginalValues.put("servizioId", _servizioId);
		_columnOriginalValues.put("organizationId", _organizationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("destinazioneUsoId", 2L);

		columnBitmasks.put("servizioId", 4L);

		columnBitmasks.put("organizationId", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("companyId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DestinazioneUsoServizioEnte _escapedModel;

}