/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneprocessi.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.servizidigitali.gestioneprocessi.model.Processo;
import it.servizidigitali.gestioneprocessi.model.ProcessoModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Processo service. Represents a row in the &quot;processo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProcessoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProcessoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProcessoImpl
 * @generated
 */
public class ProcessoModelImpl
	extends BaseModelImpl<Processo> implements ProcessoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a processo model instance should use the <code>Processo</code> interface instead.
	 */
	public static final String TABLE_NAME = "processo";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"processoId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"codice", Types.VARCHAR}, {"nome", Types.VARCHAR},
		{"stato", Types.VARCHAR}, {"multiente", Types.BOOLEAN},
		{"fileEntryId", Types.BIGINT}, {"attivo", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("processoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("codice", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stato", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("multiente", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("attivo", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table processo (uuid_ VARCHAR(75) null,processoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,codice VARCHAR(75) null,nome VARCHAR(75) null,stato VARCHAR(75) null,multiente BOOLEAN,fileEntryId LONG,attivo BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table processo";

	public static final String ORDER_BY_JPQL =
		" ORDER BY processo.processoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY processo.processoId ASC";

	public static final String DATA_SOURCE = "servizidigitaliDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ATTIVO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CODICE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MULTIENTE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATO_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROCESSOID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProcessoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _processoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProcessoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _processoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Processo.class;
	}

	@Override
	public String getModelClassName() {
		return Processo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Processo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Processo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Processo, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Processo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Processo, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Processo, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Processo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Processo, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Processo, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Processo>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Processo.class.getClassLoader(), Processo.class,
			ModelWrapper.class);

		try {
			Constructor<Processo> constructor =
				(Constructor<Processo>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Processo, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Processo, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Processo, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Processo, Object>>();
		Map<String, BiConsumer<Processo, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Processo, ?>>();

		attributeGetterFunctions.put("uuid", Processo::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Processo, String>)Processo::setUuid);
		attributeGetterFunctions.put("processoId", Processo::getProcessoId);
		attributeSetterBiConsumers.put(
			"processoId", (BiConsumer<Processo, Long>)Processo::setProcessoId);
		attributeGetterFunctions.put("groupId", Processo::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Processo, Long>)Processo::setGroupId);
		attributeGetterFunctions.put("companyId", Processo::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Processo, Long>)Processo::setCompanyId);
		attributeGetterFunctions.put("userId", Processo::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Processo, Long>)Processo::setUserId);
		attributeGetterFunctions.put("userName", Processo::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Processo, String>)Processo::setUserName);
		attributeGetterFunctions.put("createDate", Processo::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Processo, Date>)Processo::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Processo::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Processo, Date>)Processo::setModifiedDate);
		attributeGetterFunctions.put("codice", Processo::getCodice);
		attributeSetterBiConsumers.put(
			"codice", (BiConsumer<Processo, String>)Processo::setCodice);
		attributeGetterFunctions.put("nome", Processo::getNome);
		attributeSetterBiConsumers.put(
			"nome", (BiConsumer<Processo, String>)Processo::setNome);
		attributeGetterFunctions.put("stato", Processo::getStato);
		attributeSetterBiConsumers.put(
			"stato", (BiConsumer<Processo, String>)Processo::setStato);
		attributeGetterFunctions.put("multiente", Processo::getMultiente);
		attributeSetterBiConsumers.put(
			"multiente", (BiConsumer<Processo, Boolean>)Processo::setMultiente);
		attributeGetterFunctions.put("fileEntryId", Processo::getFileEntryId);
		attributeSetterBiConsumers.put(
			"fileEntryId",
			(BiConsumer<Processo, Long>)Processo::setFileEntryId);
		attributeGetterFunctions.put("attivo", Processo::getAttivo);
		attributeSetterBiConsumers.put(
			"attivo", (BiConsumer<Processo, Boolean>)Processo::setAttivo);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getProcessoId() {
		return _processoId;
	}

	@Override
	public void setProcessoId(long processoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_processoId = processoId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getCodice() {
		if (_codice == null) {
			return "";
		}
		else {
			return _codice;
		}
	}

	@Override
	public void setCodice(String codice) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_codice = codice;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCodice() {
		return getColumnOriginalValue("codice");
	}

	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nome = nome;
	}

	@Override
	public String getStato() {
		if (_stato == null) {
			return "";
		}
		else {
			return _stato;
		}
	}

	@Override
	public void setStato(String stato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stato = stato;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStato() {
		return getColumnOriginalValue("stato");
	}

	@Override
	public boolean getMultiente() {
		return _multiente;
	}

	@Override
	public boolean isMultiente() {
		return _multiente;
	}

	@Override
	public void setMultiente(boolean multiente) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_multiente = multiente;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalMultiente() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("multiente"));
	}

	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	@Override
	public boolean getAttivo() {
		return _attivo;
	}

	@Override
	public boolean isAttivo() {
		return _attivo;
	}

	@Override
	public void setAttivo(boolean attivo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_attivo = attivo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalAttivo() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("attivo"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Processo.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Processo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Processo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Processo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProcessoImpl processoImpl = new ProcessoImpl();

		processoImpl.setUuid(getUuid());
		processoImpl.setProcessoId(getProcessoId());
		processoImpl.setGroupId(getGroupId());
		processoImpl.setCompanyId(getCompanyId());
		processoImpl.setUserId(getUserId());
		processoImpl.setUserName(getUserName());
		processoImpl.setCreateDate(getCreateDate());
		processoImpl.setModifiedDate(getModifiedDate());
		processoImpl.setCodice(getCodice());
		processoImpl.setNome(getNome());
		processoImpl.setStato(getStato());
		processoImpl.setMultiente(isMultiente());
		processoImpl.setFileEntryId(getFileEntryId());
		processoImpl.setAttivo(isAttivo());

		processoImpl.resetOriginalValues();

		return processoImpl;
	}

	@Override
	public Processo cloneWithOriginalValues() {
		ProcessoImpl processoImpl = new ProcessoImpl();

		processoImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		processoImpl.setProcessoId(
			this.<Long>getColumnOriginalValue("processoId"));
		processoImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		processoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		processoImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		processoImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		processoImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		processoImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		processoImpl.setCodice(this.<String>getColumnOriginalValue("codice"));
		processoImpl.setNome(this.<String>getColumnOriginalValue("nome"));
		processoImpl.setStato(this.<String>getColumnOriginalValue("stato"));
		processoImpl.setMultiente(
			this.<Boolean>getColumnOriginalValue("multiente"));
		processoImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));
		processoImpl.setAttivo(this.<Boolean>getColumnOriginalValue("attivo"));

		return processoImpl;
	}

	@Override
	public int compareTo(Processo processo) {
		long primaryKey = processo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Processo)) {
			return false;
		}

		Processo processo = (Processo)object;

		long primaryKey = processo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Processo> toCacheModel() {
		ProcessoCacheModel processoCacheModel = new ProcessoCacheModel();

		processoCacheModel.uuid = getUuid();

		String uuid = processoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			processoCacheModel.uuid = null;
		}

		processoCacheModel.processoId = getProcessoId();

		processoCacheModel.groupId = getGroupId();

		processoCacheModel.companyId = getCompanyId();

		processoCacheModel.userId = getUserId();

		processoCacheModel.userName = getUserName();

		String userName = processoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			processoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			processoCacheModel.createDate = createDate.getTime();
		}
		else {
			processoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			processoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			processoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		processoCacheModel.codice = getCodice();

		String codice = processoCacheModel.codice;

		if ((codice != null) && (codice.length() == 0)) {
			processoCacheModel.codice = null;
		}

		processoCacheModel.nome = getNome();

		String nome = processoCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			processoCacheModel.nome = null;
		}

		processoCacheModel.stato = getStato();

		String stato = processoCacheModel.stato;

		if ((stato != null) && (stato.length() == 0)) {
			processoCacheModel.stato = null;
		}

		processoCacheModel.multiente = isMultiente();

		processoCacheModel.fileEntryId = getFileEntryId();

		processoCacheModel.attivo = isAttivo();

		return processoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Processo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Processo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Processo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Processo)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Processo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Processo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Processo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Processo)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Processo>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _processoId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _codice;
	private String _nome;
	private String _stato;
	private boolean _multiente;
	private long _fileEntryId;
	private boolean _attivo;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Processo, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Processo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("processoId", _processoId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("codice", _codice);
		_columnOriginalValues.put("nome", _nome);
		_columnOriginalValues.put("stato", _stato);
		_columnOriginalValues.put("multiente", _multiente);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
		_columnOriginalValues.put("attivo", _attivo);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("processoId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("codice", 256L);

		columnBitmasks.put("nome", 512L);

		columnBitmasks.put("stato", 1024L);

		columnBitmasks.put("multiente", 2048L);

		columnBitmasks.put("fileEntryId", 4096L);

		columnBitmasks.put("attivo", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Processo _escapedModel;

}