info:
    description: "ServiziDigitaliRestService REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "ServiziDigitaliRestService"
    version: v1.0
openapi: 3.0.1
components:
    parameters:
        pageParam:
          name: page
          in: query
          description: "Paginazione: Pagina "
          required: false
          schema:
            type: integer
            default: 0
            format: int32
        sizeParam:
          name: size
          in: query
          description: "Paginazione: Numero di elementi per pagina "
          required: false
          schema:
            type: integer
            default: 10
            format: int32
        qParam:
          name: q
          in: query
          description: "Ricerca fulltext"
          required: false
          schema:
            type: string
            
    schemas:
        RichiestaServizio:
            type: object
            properties:
              id:
                description: Id
                type: integer
                format: int64
              stato:
                description: Stato
                type: string
        InsertRichiestaServizioRequest:
            type: object
            properties:
                stato:
                  description: Stato
                  type: string
        UpdateRichiestaServizioRequest:
            type: object
            properties:
                id:
                  description: Id
                  type: integer
                  format: int64
                stato:
                  description: Stato
                  type: string
paths:
    "/richieste-servizio":
        get:
            operationId: searchRichiesteServizio
            tags: ["RichiesteServizio"]
            parameters:
              - $ref: '#/components/parameters/pageParam'
              - $ref: '#/components/parameters/sizeParam'
              - $ref: '#/components/parameters/qParam'
            responses:
                200:
                    description: Ricerca richieste servizio
                    content: 
                      application/json:
                        schema: 
                          type: array
                          items:
                            $ref: '#/components/schemas/RichiestaServizio'
                      application/xml:
                        schema: 
                          type: array
                          items:
                            $ref: '#/components/schemas/RichiestaServizio'
        post:
            operationId: insertRichiestaServizio
            tags: ["RichiesteServizio"]
            requestBody:
                content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/InsertRichiestaServizioRequest'
                    application/xml:
                      schema:
                        $ref: '#/components/schemas/InsertRichiestaServizioRequest'
            responses:
              201:
                description: Richiesta inserita
                content:
                    application/json:
                          schema:
                              $ref: '#/components/schemas/RichiestaServizio'
                    application/xml:
                      schema: 
                          $ref: '#/components/schemas/RichiestaServizio'
                  
    "/richieste-servizio/{id}":
        get:
            operationId: getRichiestaServizio
            tags: ["RichiesteServizio"]
            parameters:
              - name: id
                in: path
                description: ID richiesta
                required: true
                schema:
                  type: integer
                  format: int64
            responses:
              200:
                description: Dettaglio della richiesta
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/RichiestaServizio'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/RichiestaServizio'
        patch:
            operationId: patchRichiestaServizio
            description: Modifica di una richiesta servizio
            tags: ["RichiesteServizio"]
            parameters:
                - name: id
                  in: path
                  description: ID Richiesta
                  required: true
                  schema:
                    type: integer
                    format: int64
            requestBody:
                content:
                  "application/json":
                      schema:
                          $ref: '#/components/schemas/UpdateRichiestaServizioRequest'
                  "application/xml":
                      schema:
                          $ref: '#/components/schemas/UpdateRichiestaServizioRequest'
            responses:
                200:
                    description: "Richiesta modificata"
                    content:
                        application/json:
                          schema: 
                              $ref: '#/components/schemas/RichiestaServizio'
                        application/xml:
                          schema: 
                              $ref: '#/components/schemas/RichiestaServizio'
        put:
            operationId: updateRichiestaServizio
            description: Modifica di una richiesta servizio
            tags: ["RichiesteServizio"]
            parameters:
                - name: id
                  in: path
                  description: ID Richiesta
                  required: true
                  schema:
                    type: integer
                    format: int64
            requestBody:
                content:
                  "application/json":
                      schema:
                          $ref: '#/components/schemas/UpdateRichiestaServizioRequest'
                  "application/xml":
                      schema:
                          $ref: '#/components/schemas/UpdateRichiestaServizioRequest'
            responses:
                200:
                    description: "Richiesta modificata"
                    content:
                        application/json:
                          schema: 
                              $ref: '#/components/schemas/RichiestaServizio'
                        application/xml:
                          schema: 
                              $ref: '#/components/schemas/RichiestaServizio'
          
                      