/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.profiloutente.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import it.servizidigitali.profiloutente.service.persistence.UtenteOrganizzazionePK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UtenteOrganizzazione service. Represents a row in the &quot;utente_organizzazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.profiloutente.model.impl.UtenteOrganizzazioneModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.profiloutente.model.impl.UtenteOrganizzazioneImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UtenteOrganizzazione
 * @generated
 */
@ProviderType
public interface UtenteOrganizzazioneModel
	extends BaseModel<UtenteOrganizzazione>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a utente organizzazione model instance should use the {@link UtenteOrganizzazione} interface instead.
	 */

	/**
	 * Returns the primary key of this utente organizzazione.
	 *
	 * @return the primary key of this utente organizzazione
	 */
	public UtenteOrganizzazionePK getPrimaryKey();

	/**
	 * Sets the primary key of this utente organizzazione.
	 *
	 * @param primaryKey the primary key of this utente organizzazione
	 */
	public void setPrimaryKey(UtenteOrganizzazionePK primaryKey);

	/**
	 * Returns the uuid of this utente organizzazione.
	 *
	 * @return the uuid of this utente organizzazione
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this utente organizzazione.
	 *
	 * @param uuid the uuid of this utente organizzazione
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the utente ID of this utente organizzazione.
	 *
	 * @return the utente ID of this utente organizzazione
	 */
	public long getUtenteId();

	/**
	 * Sets the utente ID of this utente organizzazione.
	 *
	 * @param utenteId the utente ID of this utente organizzazione
	 */
	public void setUtenteId(long utenteId);

	/**
	 * Returns the organization ID of this utente organizzazione.
	 *
	 * @return the organization ID of this utente organizzazione
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this utente organizzazione.
	 *
	 * @param organizationId the organization ID of this utente organizzazione
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the group ID of this utente organizzazione.
	 *
	 * @return the group ID of this utente organizzazione
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this utente organizzazione.
	 *
	 * @param groupId the group ID of this utente organizzazione
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this utente organizzazione.
	 *
	 * @return the company ID of this utente organizzazione
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this utente organizzazione.
	 *
	 * @param companyId the company ID of this utente organizzazione
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this utente organizzazione.
	 *
	 * @return the user ID of this utente organizzazione
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this utente organizzazione.
	 *
	 * @param userId the user ID of this utente organizzazione
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this utente organizzazione.
	 *
	 * @return the user uuid of this utente organizzazione
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this utente organizzazione.
	 *
	 * @param userUuid the user uuid of this utente organizzazione
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this utente organizzazione.
	 *
	 * @return the user name of this utente organizzazione
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this utente organizzazione.
	 *
	 * @param userName the user name of this utente organizzazione
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this utente organizzazione.
	 *
	 * @return the create date of this utente organizzazione
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this utente organizzazione.
	 *
	 * @param createDate the create date of this utente organizzazione
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this utente organizzazione.
	 *
	 * @return the modified date of this utente organizzazione
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this utente organizzazione.
	 *
	 * @param modifiedDate the modified date of this utente organizzazione
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the preferito of this utente organizzazione.
	 *
	 * @return the preferito of this utente organizzazione
	 */
	public boolean getPreferito();

	/**
	 * Returns <code>true</code> if this utente organizzazione is preferito.
	 *
	 * @return <code>true</code> if this utente organizzazione is preferito; <code>false</code> otherwise
	 */
	public boolean isPreferito();

	/**
	 * Sets whether this utente organizzazione is preferito.
	 *
	 * @param preferito the preferito of this utente organizzazione
	 */
	public void setPreferito(boolean preferito);

	@Override
	public UtenteOrganizzazione cloneWithOriginalValues();

}