/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneservizi.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.servizidigitali.gestioneservizi.model.AreaTematica;
import it.servizidigitali.gestioneservizi.model.AreaTematicaModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AreaTematica service. Represents a row in the &quot;area_tematica&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AreaTematicaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AreaTematicaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AreaTematicaImpl
 * @generated
 */
public class AreaTematicaModelImpl
	extends BaseModelImpl<AreaTematica> implements AreaTematicaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a area tematica model instance should use the <code>AreaTematica</code> interface instead.
	 */
	public static final String TABLE_NAME = "area_tematica";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"areaTematicaId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"nome", Types.VARCHAR}, {"descrizione", Types.VARCHAR},
		{"codice", Types.VARCHAR}, {"sportello", Types.VARCHAR},
		{"uriVocabolario", Types.VARCHAR}, {"ordine", Types.INTEGER},
		{"visibile", Types.BOOLEAN}, {"attiva", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("areaTematicaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("codice", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sportello", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("uriVocabolario", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ordine", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("visibile", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("attiva", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table area_tematica (uuid_ VARCHAR(75) null,areaTematicaId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nome VARCHAR(75) null,descrizione VARCHAR(75) null,codice VARCHAR(75) null,sportello VARCHAR(75) null,uriVocabolario VARCHAR(75) null,ordine INTEGER,visibile BOOLEAN,attiva BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table area_tematica";

	public static final String ORDER_BY_JPQL =
		" ORDER BY areaTematica.nome ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY area_tematica.nome ASC";

	public static final String DATA_SOURCE = "servizidigitaliDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ATTIVA_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CODICE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOME_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AreaTematicaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _areaTematicaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAreaTematicaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _areaTematicaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AreaTematica.class;
	}

	@Override
	public String getModelClassName() {
		return AreaTematica.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AreaTematica, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AreaTematica, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AreaTematica, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AreaTematica)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AreaTematica, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AreaTematica, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AreaTematica)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AreaTematica, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AreaTematica, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AreaTematica>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AreaTematica.class.getClassLoader(), AreaTematica.class,
			ModelWrapper.class);

		try {
			Constructor<AreaTematica> constructor =
				(Constructor<AreaTematica>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<AreaTematica, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AreaTematica, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AreaTematica, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AreaTematica, Object>>();
		Map<String, BiConsumer<AreaTematica, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AreaTematica, ?>>();

		attributeGetterFunctions.put("uuid", AreaTematica::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<AreaTematica, String>)AreaTematica::setUuid);
		attributeGetterFunctions.put(
			"areaTematicaId", AreaTematica::getAreaTematicaId);
		attributeSetterBiConsumers.put(
			"areaTematicaId",
			(BiConsumer<AreaTematica, Long>)AreaTematica::setAreaTematicaId);
		attributeGetterFunctions.put("groupId", AreaTematica::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<AreaTematica, Long>)AreaTematica::setGroupId);
		attributeGetterFunctions.put("companyId", AreaTematica::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AreaTematica, Long>)AreaTematica::setCompanyId);
		attributeGetterFunctions.put("userId", AreaTematica::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<AreaTematica, Long>)AreaTematica::setUserId);
		attributeGetterFunctions.put("userName", AreaTematica::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<AreaTematica, String>)AreaTematica::setUserName);
		attributeGetterFunctions.put("createDate", AreaTematica::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<AreaTematica, Date>)AreaTematica::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", AreaTematica::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AreaTematica, Date>)AreaTematica::setModifiedDate);
		attributeGetterFunctions.put("nome", AreaTematica::getNome);
		attributeSetterBiConsumers.put(
			"nome", (BiConsumer<AreaTematica, String>)AreaTematica::setNome);
		attributeGetterFunctions.put(
			"descrizione", AreaTematica::getDescrizione);
		attributeSetterBiConsumers.put(
			"descrizione",
			(BiConsumer<AreaTematica, String>)AreaTematica::setDescrizione);
		attributeGetterFunctions.put("codice", AreaTematica::getCodice);
		attributeSetterBiConsumers.put(
			"codice",
			(BiConsumer<AreaTematica, String>)AreaTematica::setCodice);
		attributeGetterFunctions.put("sportello", AreaTematica::getSportello);
		attributeSetterBiConsumers.put(
			"sportello",
			(BiConsumer<AreaTematica, String>)AreaTematica::setSportello);
		attributeGetterFunctions.put(
			"uriVocabolario", AreaTematica::getUriVocabolario);
		attributeSetterBiConsumers.put(
			"uriVocabolario",
			(BiConsumer<AreaTematica, String>)AreaTematica::setUriVocabolario);
		attributeGetterFunctions.put("ordine", AreaTematica::getOrdine);
		attributeSetterBiConsumers.put(
			"ordine",
			(BiConsumer<AreaTematica, Integer>)AreaTematica::setOrdine);
		attributeGetterFunctions.put("visibile", AreaTematica::getVisibile);
		attributeSetterBiConsumers.put(
			"visibile",
			(BiConsumer<AreaTematica, Boolean>)AreaTematica::setVisibile);
		attributeGetterFunctions.put("attiva", AreaTematica::getAttiva);
		attributeSetterBiConsumers.put(
			"attiva",
			(BiConsumer<AreaTematica, Boolean>)AreaTematica::setAttiva);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getAreaTematicaId() {
		return _areaTematicaId;
	}

	@Override
	public void setAreaTematicaId(long areaTematicaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_areaTematicaId = areaTematicaId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nome = nome;
	}

	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return "";
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descrizione = descrizione;
	}

	@Override
	public String getCodice() {
		if (_codice == null) {
			return "";
		}
		else {
			return _codice;
		}
	}

	@Override
	public void setCodice(String codice) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_codice = codice;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCodice() {
		return getColumnOriginalValue("codice");
	}

	@Override
	public String getSportello() {
		if (_sportello == null) {
			return "";
		}
		else {
			return _sportello;
		}
	}

	@Override
	public void setSportello(String sportello) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sportello = sportello;
	}

	@Override
	public String getUriVocabolario() {
		if (_uriVocabolario == null) {
			return "";
		}
		else {
			return _uriVocabolario;
		}
	}

	@Override
	public void setUriVocabolario(String uriVocabolario) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uriVocabolario = uriVocabolario;
	}

	@Override
	public int getOrdine() {
		return _ordine;
	}

	@Override
	public void setOrdine(int ordine) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ordine = ordine;
	}

	@Override
	public boolean getVisibile() {
		return _visibile;
	}

	@Override
	public boolean isVisibile() {
		return _visibile;
	}

	@Override
	public void setVisibile(boolean visibile) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_visibile = visibile;
	}

	@Override
	public boolean getAttiva() {
		return _attiva;
	}

	@Override
	public boolean isAttiva() {
		return _attiva;
	}

	@Override
	public void setAttiva(boolean attiva) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_attiva = attiva;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalAttiva() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("attiva"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AreaTematica.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AreaTematica.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AreaTematica toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AreaTematica>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AreaTematicaImpl areaTematicaImpl = new AreaTematicaImpl();

		areaTematicaImpl.setUuid(getUuid());
		areaTematicaImpl.setAreaTematicaId(getAreaTematicaId());
		areaTematicaImpl.setGroupId(getGroupId());
		areaTematicaImpl.setCompanyId(getCompanyId());
		areaTematicaImpl.setUserId(getUserId());
		areaTematicaImpl.setUserName(getUserName());
		areaTematicaImpl.setCreateDate(getCreateDate());
		areaTematicaImpl.setModifiedDate(getModifiedDate());
		areaTematicaImpl.setNome(getNome());
		areaTematicaImpl.setDescrizione(getDescrizione());
		areaTematicaImpl.setCodice(getCodice());
		areaTematicaImpl.setSportello(getSportello());
		areaTematicaImpl.setUriVocabolario(getUriVocabolario());
		areaTematicaImpl.setOrdine(getOrdine());
		areaTematicaImpl.setVisibile(isVisibile());
		areaTematicaImpl.setAttiva(isAttiva());

		areaTematicaImpl.resetOriginalValues();

		return areaTematicaImpl;
	}

	@Override
	public AreaTematica cloneWithOriginalValues() {
		AreaTematicaImpl areaTematicaImpl = new AreaTematicaImpl();

		areaTematicaImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		areaTematicaImpl.setAreaTematicaId(
			this.<Long>getColumnOriginalValue("areaTematicaId"));
		areaTematicaImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		areaTematicaImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		areaTematicaImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		areaTematicaImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		areaTematicaImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		areaTematicaImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		areaTematicaImpl.setNome(this.<String>getColumnOriginalValue("nome"));
		areaTematicaImpl.setDescrizione(
			this.<String>getColumnOriginalValue("descrizione"));
		areaTematicaImpl.setCodice(
			this.<String>getColumnOriginalValue("codice"));
		areaTematicaImpl.setSportello(
			this.<String>getColumnOriginalValue("sportello"));
		areaTematicaImpl.setUriVocabolario(
			this.<String>getColumnOriginalValue("uriVocabolario"));
		areaTematicaImpl.setOrdine(
			this.<Integer>getColumnOriginalValue("ordine"));
		areaTematicaImpl.setVisibile(
			this.<Boolean>getColumnOriginalValue("visibile"));
		areaTematicaImpl.setAttiva(
			this.<Boolean>getColumnOriginalValue("attiva"));

		return areaTematicaImpl;
	}

	@Override
	public int compareTo(AreaTematica areaTematica) {
		int value = 0;

		value = getNome().compareTo(areaTematica.getNome());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AreaTematica)) {
			return false;
		}

		AreaTematica areaTematica = (AreaTematica)object;

		long primaryKey = areaTematica.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AreaTematica> toCacheModel() {
		AreaTematicaCacheModel areaTematicaCacheModel =
			new AreaTematicaCacheModel();

		areaTematicaCacheModel.uuid = getUuid();

		String uuid = areaTematicaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			areaTematicaCacheModel.uuid = null;
		}

		areaTematicaCacheModel.areaTematicaId = getAreaTematicaId();

		areaTematicaCacheModel.groupId = getGroupId();

		areaTematicaCacheModel.companyId = getCompanyId();

		areaTematicaCacheModel.userId = getUserId();

		areaTematicaCacheModel.userName = getUserName();

		String userName = areaTematicaCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			areaTematicaCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			areaTematicaCacheModel.createDate = createDate.getTime();
		}
		else {
			areaTematicaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			areaTematicaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			areaTematicaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		areaTematicaCacheModel.nome = getNome();

		String nome = areaTematicaCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			areaTematicaCacheModel.nome = null;
		}

		areaTematicaCacheModel.descrizione = getDescrizione();

		String descrizione = areaTematicaCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			areaTematicaCacheModel.descrizione = null;
		}

		areaTematicaCacheModel.codice = getCodice();

		String codice = areaTematicaCacheModel.codice;

		if ((codice != null) && (codice.length() == 0)) {
			areaTematicaCacheModel.codice = null;
		}

		areaTematicaCacheModel.sportello = getSportello();

		String sportello = areaTematicaCacheModel.sportello;

		if ((sportello != null) && (sportello.length() == 0)) {
			areaTematicaCacheModel.sportello = null;
		}

		areaTematicaCacheModel.uriVocabolario = getUriVocabolario();

		String uriVocabolario = areaTematicaCacheModel.uriVocabolario;

		if ((uriVocabolario != null) && (uriVocabolario.length() == 0)) {
			areaTematicaCacheModel.uriVocabolario = null;
		}

		areaTematicaCacheModel.ordine = getOrdine();

		areaTematicaCacheModel.visibile = isVisibile();

		areaTematicaCacheModel.attiva = isAttiva();

		return areaTematicaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AreaTematica, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AreaTematica, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AreaTematica, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AreaTematica)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AreaTematica, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AreaTematica, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AreaTematica, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AreaTematica)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AreaTematica>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _areaTematicaId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _nome;
	private String _descrizione;
	private String _codice;
	private String _sportello;
	private String _uriVocabolario;
	private int _ordine;
	private boolean _visibile;
	private boolean _attiva;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AreaTematica, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AreaTematica)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("areaTematicaId", _areaTematicaId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("nome", _nome);
		_columnOriginalValues.put("descrizione", _descrizione);
		_columnOriginalValues.put("codice", _codice);
		_columnOriginalValues.put("sportello", _sportello);
		_columnOriginalValues.put("uriVocabolario", _uriVocabolario);
		_columnOriginalValues.put("ordine", _ordine);
		_columnOriginalValues.put("visibile", _visibile);
		_columnOriginalValues.put("attiva", _attiva);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("areaTematicaId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("nome", 256L);

		columnBitmasks.put("descrizione", 512L);

		columnBitmasks.put("codice", 1024L);

		columnBitmasks.put("sportello", 2048L);

		columnBitmasks.put("uriVocabolario", 4096L);

		columnBitmasks.put("ordine", 8192L);

		columnBitmasks.put("visibile", 16384L);

		columnBitmasks.put("attiva", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AreaTematica _escapedModel;

}