/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneprocedure.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.servizidigitali.gestioneprocedure.model.ProceduraForm;
import it.servizidigitali.gestioneprocedure.model.ProceduraFormModel;
import it.servizidigitali.gestioneprocedure.service.persistence.ProceduraFormPK;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProceduraForm service. Represents a row in the &quot;procedura_form&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProceduraFormModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProceduraFormImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProceduraFormImpl
 * @generated
 */
public class ProceduraFormModelImpl
	extends BaseModelImpl<ProceduraForm> implements ProceduraFormModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a procedura form model instance should use the <code>ProceduraForm</code> interface instead.
	 */
	public static final String TABLE_NAME = "procedura_form";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"proceduraId", Types.BIGINT},
		{"formId", Types.BIGINT}, {"companyId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("proceduraId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("formId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table procedura_form (uuid_ VARCHAR(75) null,proceduraId LONG not null,formId LONG not null,companyId LONG,primary key (proceduraId, formId))";

	public static final String TABLE_SQL_DROP = "drop table procedura_form";

	public static final String ORDER_BY_JPQL =
		" ORDER BY proceduraForm.id.proceduraId ASC, proceduraForm.id.formId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY procedura_form.proceduraId ASC, procedura_form.formId ASC";

	public static final String DATA_SOURCE = "servizidigitaliDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROCEDURAID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FORMID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProceduraFormModelImpl() {
	}

	@Override
	public ProceduraFormPK getPrimaryKey() {
		return new ProceduraFormPK(_proceduraId, _formId);
	}

	@Override
	public void setPrimaryKey(ProceduraFormPK primaryKey) {
		setProceduraId(primaryKey.proceduraId);
		setFormId(primaryKey.formId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new ProceduraFormPK(_proceduraId, _formId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((ProceduraFormPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ProceduraForm.class;
	}

	@Override
	public String getModelClassName() {
		return ProceduraForm.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProceduraForm, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProceduraForm, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProceduraForm, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProceduraForm)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProceduraForm, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProceduraForm, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProceduraForm)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProceduraForm, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProceduraForm, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ProceduraForm>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ProceduraForm.class.getClassLoader(), ProceduraForm.class,
			ModelWrapper.class);

		try {
			Constructor<ProceduraForm> constructor =
				(Constructor<ProceduraForm>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ProceduraForm, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProceduraForm, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProceduraForm, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ProceduraForm, Object>>();
		Map<String, BiConsumer<ProceduraForm, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ProceduraForm, ?>>();

		attributeGetterFunctions.put("uuid", ProceduraForm::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<ProceduraForm, String>)ProceduraForm::setUuid);
		attributeGetterFunctions.put(
			"proceduraId", ProceduraForm::getProceduraId);
		attributeSetterBiConsumers.put(
			"proceduraId",
			(BiConsumer<ProceduraForm, Long>)ProceduraForm::setProceduraId);
		attributeGetterFunctions.put("formId", ProceduraForm::getFormId);
		attributeSetterBiConsumers.put(
			"formId",
			(BiConsumer<ProceduraForm, Long>)ProceduraForm::setFormId);
		attributeGetterFunctions.put("companyId", ProceduraForm::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProceduraForm, Long>)ProceduraForm::setCompanyId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getProceduraId() {
		return _proceduraId;
	}

	@Override
	public void setProceduraId(long proceduraId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_proceduraId = proceduraId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProceduraId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("proceduraId"));
	}

	@Override
	public long getFormId() {
		return _formId;
	}

	@Override
	public void setFormId(long formId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_formId = formId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ProceduraForm toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProceduraForm>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProceduraFormImpl proceduraFormImpl = new ProceduraFormImpl();

		proceduraFormImpl.setUuid(getUuid());
		proceduraFormImpl.setProceduraId(getProceduraId());
		proceduraFormImpl.setFormId(getFormId());
		proceduraFormImpl.setCompanyId(getCompanyId());

		proceduraFormImpl.resetOriginalValues();

		return proceduraFormImpl;
	}

	@Override
	public ProceduraForm cloneWithOriginalValues() {
		ProceduraFormImpl proceduraFormImpl = new ProceduraFormImpl();

		proceduraFormImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		proceduraFormImpl.setProceduraId(
			this.<Long>getColumnOriginalValue("proceduraId"));
		proceduraFormImpl.setFormId(
			this.<Long>getColumnOriginalValue("formId"));
		proceduraFormImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));

		return proceduraFormImpl;
	}

	@Override
	public int compareTo(ProceduraForm proceduraForm) {
		ProceduraFormPK primaryKey = proceduraForm.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProceduraForm)) {
			return false;
		}

		ProceduraForm proceduraForm = (ProceduraForm)object;

		ProceduraFormPK primaryKey = proceduraForm.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProceduraForm> toCacheModel() {
		ProceduraFormCacheModel proceduraFormCacheModel =
			new ProceduraFormCacheModel();

		proceduraFormCacheModel.proceduraFormPK = getPrimaryKey();

		proceduraFormCacheModel.uuid = getUuid();

		String uuid = proceduraFormCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			proceduraFormCacheModel.uuid = null;
		}

		proceduraFormCacheModel.proceduraId = getProceduraId();

		proceduraFormCacheModel.formId = getFormId();

		proceduraFormCacheModel.companyId = getCompanyId();

		return proceduraFormCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProceduraForm, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProceduraForm, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProceduraForm, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ProceduraForm)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ProceduraForm, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ProceduraForm, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProceduraForm, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ProceduraForm)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProceduraForm>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _proceduraId;
	private long _formId;
	private long _companyId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProceduraForm, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProceduraForm)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("proceduraId", _proceduraId);
		_columnOriginalValues.put("formId", _formId);
		_columnOriginalValues.put("companyId", _companyId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("proceduraId", 2L);

		columnBitmasks.put("formId", 4L);

		columnBitmasks.put("companyId", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProceduraForm _escapedModel;

}