/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneprocedure.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Procedura service. Represents a row in the &quot;procedura&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.gestioneprocedure.model.impl.ProceduraModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.gestioneprocedure.model.impl.ProceduraImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Procedura
 * @generated
 */
@ProviderType
public interface ProceduraModel
	extends BaseModel<Procedura>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a procedura model instance should use the {@link Procedura} interface instead.
	 */

	/**
	 * Returns the primary key of this procedura.
	 *
	 * @return the primary key of this procedura
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this procedura.
	 *
	 * @param primaryKey the primary key of this procedura
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this procedura.
	 *
	 * @return the uuid of this procedura
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this procedura.
	 *
	 * @param uuid the uuid of this procedura
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the procedura ID of this procedura.
	 *
	 * @return the procedura ID of this procedura
	 */
	public long getProceduraId();

	/**
	 * Sets the procedura ID of this procedura.
	 *
	 * @param proceduraId the procedura ID of this procedura
	 */
	public void setProceduraId(long proceduraId);

	/**
	 * Returns the group ID of this procedura.
	 *
	 * @return the group ID of this procedura
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this procedura.
	 *
	 * @param groupId the group ID of this procedura
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this procedura.
	 *
	 * @return the company ID of this procedura
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this procedura.
	 *
	 * @param companyId the company ID of this procedura
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this procedura.
	 *
	 * @return the user ID of this procedura
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this procedura.
	 *
	 * @param userId the user ID of this procedura
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this procedura.
	 *
	 * @return the user uuid of this procedura
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this procedura.
	 *
	 * @param userUuid the user uuid of this procedura
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this procedura.
	 *
	 * @return the user name of this procedura
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this procedura.
	 *
	 * @param userName the user name of this procedura
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this procedura.
	 *
	 * @return the create date of this procedura
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this procedura.
	 *
	 * @param createDate the create date of this procedura
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this procedura.
	 *
	 * @return the modified date of this procedura
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this procedura.
	 *
	 * @param modifiedDate the modified date of this procedura
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this procedura.
	 *
	 * @return the nome of this procedura
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this procedura.
	 *
	 * @param nome the nome of this procedura
	 */
	public void setNome(String nome);

	/**
	 * Returns the pec destinazione of this procedura.
	 *
	 * @return the pec destinazione of this procedura
	 */
	@AutoEscape
	public String getPecDestinazione();

	/**
	 * Sets the pec destinazione of this procedura.
	 *
	 * @param pecDestinazione the pec destinazione of this procedura
	 */
	public void setPecDestinazione(String pecDestinazione);

	/**
	 * Returns the configurazioni presentatore form of this procedura.
	 *
	 * @return the configurazioni presentatore form of this procedura
	 */
	@AutoEscape
	public String getConfigurazioniPresentatoreForm();

	/**
	 * Sets the configurazioni presentatore form of this procedura.
	 *
	 * @param configurazioniPresentatoreForm the configurazioni presentatore form of this procedura
	 */
	public void setConfigurazioniPresentatoreForm(
		String configurazioniPresentatoreForm);

	/**
	 * Returns the attiva of this procedura.
	 *
	 * @return the attiva of this procedura
	 */
	public boolean getAttiva();

	/**
	 * Returns <code>true</code> if this procedura is attiva.
	 *
	 * @return <code>true</code> if this procedura is attiva; <code>false</code> otherwise
	 */
	public boolean isAttiva();

	/**
	 * Sets whether this procedura is attiva.
	 *
	 * @param attiva the attiva of this procedura
	 */
	public void setAttiva(boolean attiva);

	/**
	 * Returns the servizio ID of this procedura.
	 *
	 * @return the servizio ID of this procedura
	 */
	public long getServizioId();

	/**
	 * Sets the servizio ID of this procedura.
	 *
	 * @param servizioId the servizio ID of this procedura
	 */
	public void setServizioId(long servizioId);

	/**
	 * Returns the processo ID of this procedura.
	 *
	 * @return the processo ID of this procedura
	 */
	public long getProcessoId();

	/**
	 * Sets the processo ID of this procedura.
	 *
	 * @param processoId the processo ID of this procedura
	 */
	public void setProcessoId(long processoId);

	@Override
	public Procedura cloneWithOriginalValues();

}