/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneprocedure.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import it.servizidigitali.gestioneprocedure.service.persistence.ProceduraFormPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProceduraForm service. Represents a row in the &quot;procedura_form&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.gestioneprocedure.model.impl.ProceduraFormModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.gestioneprocedure.model.impl.ProceduraFormImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProceduraForm
 * @generated
 */
@ProviderType
public interface ProceduraFormModel
	extends BaseModel<ProceduraForm>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a procedura form model instance should use the {@link ProceduraForm} interface instead.
	 */

	/**
	 * Returns the primary key of this procedura form.
	 *
	 * @return the primary key of this procedura form
	 */
	public ProceduraFormPK getPrimaryKey();

	/**
	 * Sets the primary key of this procedura form.
	 *
	 * @param primaryKey the primary key of this procedura form
	 */
	public void setPrimaryKey(ProceduraFormPK primaryKey);

	/**
	 * Returns the uuid of this procedura form.
	 *
	 * @return the uuid of this procedura form
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this procedura form.
	 *
	 * @param uuid the uuid of this procedura form
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the procedura ID of this procedura form.
	 *
	 * @return the procedura ID of this procedura form
	 */
	public long getProceduraId();

	/**
	 * Sets the procedura ID of this procedura form.
	 *
	 * @param proceduraId the procedura ID of this procedura form
	 */
	public void setProceduraId(long proceduraId);

	/**
	 * Returns the form ID of this procedura form.
	 *
	 * @return the form ID of this procedura form
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this procedura form.
	 *
	 * @param formId the form ID of this procedura form
	 */
	public void setFormId(long formId);

	/**
	 * Returns the company ID of this procedura form.
	 *
	 * @return the company ID of this procedura form
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this procedura form.
	 *
	 * @param companyId the company ID of this procedura form
	 */
	@Override
	public void setCompanyId(long companyId);

	@Override
	public ProceduraForm cloneWithOriginalValues();

}