/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneprocedure.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TemplatePdf service. Represents a row in the &quot;template_pdf&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.gestioneprocedure.model.impl.TemplatePdfModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.gestioneprocedure.model.impl.TemplatePdfImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TemplatePdf
 * @generated
 */
@ProviderType
public interface TemplatePdfModel
	extends BaseModel<TemplatePdf>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a template pdf model instance should use the {@link TemplatePdf} interface instead.
	 */

	/**
	 * Returns the primary key of this template pdf.
	 *
	 * @return the primary key of this template pdf
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this template pdf.
	 *
	 * @param primaryKey the primary key of this template pdf
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this template pdf.
	 *
	 * @return the uuid of this template pdf
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this template pdf.
	 *
	 * @param uuid the uuid of this template pdf
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the template pdf ID of this template pdf.
	 *
	 * @return the template pdf ID of this template pdf
	 */
	public long getTemplatePdfId();

	/**
	 * Sets the template pdf ID of this template pdf.
	 *
	 * @param templatePdfId the template pdf ID of this template pdf
	 */
	public void setTemplatePdfId(long templatePdfId);

	/**
	 * Returns the group ID of this template pdf.
	 *
	 * @return the group ID of this template pdf
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this template pdf.
	 *
	 * @param groupId the group ID of this template pdf
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this template pdf.
	 *
	 * @return the company ID of this template pdf
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this template pdf.
	 *
	 * @param companyId the company ID of this template pdf
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this template pdf.
	 *
	 * @return the user ID of this template pdf
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this template pdf.
	 *
	 * @param userId the user ID of this template pdf
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this template pdf.
	 *
	 * @return the user uuid of this template pdf
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this template pdf.
	 *
	 * @param userUuid the user uuid of this template pdf
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this template pdf.
	 *
	 * @return the user name of this template pdf
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this template pdf.
	 *
	 * @param userName the user name of this template pdf
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this template pdf.
	 *
	 * @return the create date of this template pdf
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this template pdf.
	 *
	 * @param createDate the create date of this template pdf
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this template pdf.
	 *
	 * @return the modified date of this template pdf
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this template pdf.
	 *
	 * @param modifiedDate the modified date of this template pdf
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the file entry ID of this template pdf.
	 *
	 * @return the file entry ID of this template pdf
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this template pdf.
	 *
	 * @param fileEntryId the file entry ID of this template pdf
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the procedura ID of this template pdf.
	 *
	 * @return the procedura ID of this template pdf
	 */
	public long getProceduraId();

	/**
	 * Sets the procedura ID of this template pdf.
	 *
	 * @param proceduraId the procedura ID of this template pdf
	 */
	public void setProceduraId(long proceduraId);

	/**
	 * Returns the template pdf parent ID of this template pdf.
	 *
	 * @return the template pdf parent ID of this template pdf
	 */
	public long getTemplatePdfParentId();

	/**
	 * Sets the template pdf parent ID of this template pdf.
	 *
	 * @param templatePdfParentId the template pdf parent ID of this template pdf
	 */
	public void setTemplatePdfParentId(long templatePdfParentId);

	@Override
	public TemplatePdf cloneWithOriginalValues();

}