/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestionecomunicazioni.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.servizidigitali.gestionecomunicazioni.model.LetturaComunicazione;
import it.servizidigitali.gestionecomunicazioni.model.LetturaComunicazioneModel;
import it.servizidigitali.gestionecomunicazioni.service.persistence.LetturaComunicazionePK;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LetturaComunicazione service. Represents a row in the &quot;lettura_comunicazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LetturaComunicazioneModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LetturaComunicazioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LetturaComunicazioneImpl
 * @generated
 */
public class LetturaComunicazioneModelImpl
	extends BaseModelImpl<LetturaComunicazione>
	implements LetturaComunicazioneModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lettura comunicazione model instance should use the <code>LetturaComunicazione</code> interface instead.
	 */
	public static final String TABLE_NAME = "lettura_comunicazione";

	public static final Object[][] TABLE_COLUMNS = {
		{"comunicazioneId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"dataLettura", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("comunicazioneId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataLettura", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table lettura_comunicazione (comunicazioneId LONG not null,userId LONG not null,dataLettura DATE null,primary key (comunicazioneId, userId))";

	public static final String TABLE_SQL_DROP =
		"drop table lettura_comunicazione";

	public static final String ORDER_BY_JPQL =
		" ORDER BY letturaComunicazione.id.comunicazioneId ASC, letturaComunicazione.id.userId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY lettura_comunicazione.comunicazioneId ASC, lettura_comunicazione.userId ASC";

	public static final String DATA_SOURCE = "servizidigitaliDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMUNICAZIONEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LetturaComunicazioneModelImpl() {
	}

	@Override
	public LetturaComunicazionePK getPrimaryKey() {
		return new LetturaComunicazionePK(_comunicazioneId, _userId);
	}

	@Override
	public void setPrimaryKey(LetturaComunicazionePK primaryKey) {
		setComunicazioneId(primaryKey.comunicazioneId);
		setUserId(primaryKey.userId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new LetturaComunicazionePK(_comunicazioneId, _userId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((LetturaComunicazionePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return LetturaComunicazione.class;
	}

	@Override
	public String getModelClassName() {
		return LetturaComunicazione.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LetturaComunicazione, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LetturaComunicazione, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LetturaComunicazione, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LetturaComunicazione)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LetturaComunicazione, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LetturaComunicazione, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LetturaComunicazione)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LetturaComunicazione, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LetturaComunicazione, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LetturaComunicazione>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LetturaComunicazione.class.getClassLoader(),
			LetturaComunicazione.class, ModelWrapper.class);

		try {
			Constructor<LetturaComunicazione> constructor =
				(Constructor<LetturaComunicazione>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LetturaComunicazione, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LetturaComunicazione, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LetturaComunicazione, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<LetturaComunicazione, Object>>();
		Map<String, BiConsumer<LetturaComunicazione, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<LetturaComunicazione, ?>>();

		attributeGetterFunctions.put(
			"comunicazioneId", LetturaComunicazione::getComunicazioneId);
		attributeSetterBiConsumers.put(
			"comunicazioneId",
			(BiConsumer<LetturaComunicazione, Long>)
				LetturaComunicazione::setComunicazioneId);
		attributeGetterFunctions.put("userId", LetturaComunicazione::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<LetturaComunicazione, Long>)
				LetturaComunicazione::setUserId);
		attributeGetterFunctions.put(
			"dataLettura", LetturaComunicazione::getDataLettura);
		attributeSetterBiConsumers.put(
			"dataLettura",
			(BiConsumer<LetturaComunicazione, Date>)
				LetturaComunicazione::setDataLettura);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getComunicazioneId() {
		return _comunicazioneId;
	}

	@Override
	public void setComunicazioneId(long comunicazioneId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_comunicazioneId = comunicazioneId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Date getDataLettura() {
		return _dataLettura;
	}

	@Override
	public void setDataLettura(Date dataLettura) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataLettura = dataLettura;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public LetturaComunicazione toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LetturaComunicazione>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LetturaComunicazioneImpl letturaComunicazioneImpl =
			new LetturaComunicazioneImpl();

		letturaComunicazioneImpl.setComunicazioneId(getComunicazioneId());
		letturaComunicazioneImpl.setUserId(getUserId());
		letturaComunicazioneImpl.setDataLettura(getDataLettura());

		letturaComunicazioneImpl.resetOriginalValues();

		return letturaComunicazioneImpl;
	}

	@Override
	public LetturaComunicazione cloneWithOriginalValues() {
		LetturaComunicazioneImpl letturaComunicazioneImpl =
			new LetturaComunicazioneImpl();

		letturaComunicazioneImpl.setComunicazioneId(
			this.<Long>getColumnOriginalValue("comunicazioneId"));
		letturaComunicazioneImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		letturaComunicazioneImpl.setDataLettura(
			this.<Date>getColumnOriginalValue("dataLettura"));

		return letturaComunicazioneImpl;
	}

	@Override
	public int compareTo(LetturaComunicazione letturaComunicazione) {
		LetturaComunicazionePK primaryKey =
			letturaComunicazione.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LetturaComunicazione)) {
			return false;
		}

		LetturaComunicazione letturaComunicazione =
			(LetturaComunicazione)object;

		LetturaComunicazionePK primaryKey =
			letturaComunicazione.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LetturaComunicazione> toCacheModel() {
		LetturaComunicazioneCacheModel letturaComunicazioneCacheModel =
			new LetturaComunicazioneCacheModel();

		letturaComunicazioneCacheModel.letturaComunicazionePK = getPrimaryKey();

		letturaComunicazioneCacheModel.comunicazioneId = getComunicazioneId();

		letturaComunicazioneCacheModel.userId = getUserId();

		Date dataLettura = getDataLettura();

		if (dataLettura != null) {
			letturaComunicazioneCacheModel.dataLettura = dataLettura.getTime();
		}
		else {
			letturaComunicazioneCacheModel.dataLettura = Long.MIN_VALUE;
		}

		return letturaComunicazioneCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LetturaComunicazione, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LetturaComunicazione, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LetturaComunicazione, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LetturaComunicazione)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LetturaComunicazione, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LetturaComunicazione, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LetturaComunicazione, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((LetturaComunicazione)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LetturaComunicazione>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _comunicazioneId;
	private long _userId;
	private Date _dataLettura;

	public <T> T getColumnValue(String columnName) {
		Function<LetturaComunicazione, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LetturaComunicazione)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("comunicazioneId", _comunicazioneId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("dataLettura", _dataLettura);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("comunicazioneId", 1L);

		columnBitmasks.put("userId", 2L);

		columnBitmasks.put("dataLettura", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LetturaComunicazione _escapedModel;

}