/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneforms.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import it.servizidigitali.gestioneforms.model.DefinizioneAllegato;
import it.servizidigitali.gestioneforms.service.DefinizioneAllegatoLocalService;
import it.servizidigitali.gestioneforms.service.DefinizioneAllegatoLocalServiceUtil;
import it.servizidigitali.gestioneforms.service.persistence.DefinizioneAllegatoPersistence;
import it.servizidigitali.gestioneforms.service.persistence.FormFinder;
import it.servizidigitali.gestioneforms.service.persistence.FormPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the definizione allegato local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.servizidigitali.gestioneforms.service.impl.DefinizioneAllegatoLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see it.servizidigitali.gestioneforms.service.impl.DefinizioneAllegatoLocalServiceImpl
 * @generated
 */
public abstract class DefinizioneAllegatoLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, DefinizioneAllegatoLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DefinizioneAllegatoLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DefinizioneAllegatoLocalServiceUtil</code>.
	 */

	/**
	 * Adds the definizione allegato to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DefinizioneAllegatoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param definizioneAllegato the definizione allegato
	 * @return the definizione allegato that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DefinizioneAllegato addDefinizioneAllegato(
		DefinizioneAllegato definizioneAllegato) {

		definizioneAllegato.setNew(true);

		return definizioneAllegatoPersistence.update(definizioneAllegato);
	}

	/**
	 * Creates a new definizione allegato with the primary key. Does not add the definizione allegato to the database.
	 *
	 * @param definizioneAllegatoId the primary key for the new definizione allegato
	 * @return the new definizione allegato
	 */
	@Override
	@Transactional(enabled = false)
	public DefinizioneAllegato createDefinizioneAllegato(
		long definizioneAllegatoId) {

		return definizioneAllegatoPersistence.create(definizioneAllegatoId);
	}

	/**
	 * Deletes the definizione allegato with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DefinizioneAllegatoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param definizioneAllegatoId the primary key of the definizione allegato
	 * @return the definizione allegato that was removed
	 * @throws PortalException if a definizione allegato with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DefinizioneAllegato deleteDefinizioneAllegato(
			long definizioneAllegatoId)
		throws PortalException {

		return definizioneAllegatoPersistence.remove(definizioneAllegatoId);
	}

	/**
	 * Deletes the definizione allegato from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DefinizioneAllegatoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param definizioneAllegato the definizione allegato
	 * @return the definizione allegato that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DefinizioneAllegato deleteDefinizioneAllegato(
		DefinizioneAllegato definizioneAllegato) {

		return definizioneAllegatoPersistence.remove(definizioneAllegato);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return definizioneAllegatoPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DefinizioneAllegato.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return definizioneAllegatoPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.gestioneforms.model.impl.DefinizioneAllegatoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return definizioneAllegatoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.gestioneforms.model.impl.DefinizioneAllegatoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return definizioneAllegatoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return definizioneAllegatoPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return definizioneAllegatoPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DefinizioneAllegato fetchDefinizioneAllegato(
		long definizioneAllegatoId) {

		return definizioneAllegatoPersistence.fetchByPrimaryKey(
			definizioneAllegatoId);
	}

	/**
	 * Returns the definizione allegato matching the UUID and group.
	 *
	 * @param uuid the definizione allegato's UUID
	 * @param groupId the primary key of the group
	 * @return the matching definizione allegato, or <code>null</code> if a matching definizione allegato could not be found
	 */
	@Override
	public DefinizioneAllegato fetchDefinizioneAllegatoByUuidAndGroupId(
		String uuid, long groupId) {

		return definizioneAllegatoPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the definizione allegato with the primary key.
	 *
	 * @param definizioneAllegatoId the primary key of the definizione allegato
	 * @return the definizione allegato
	 * @throws PortalException if a definizione allegato with the primary key could not be found
	 */
	@Override
	public DefinizioneAllegato getDefinizioneAllegato(
			long definizioneAllegatoId)
		throws PortalException {

		return definizioneAllegatoPersistence.findByPrimaryKey(
			definizioneAllegatoId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			definizioneAllegatoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DefinizioneAllegato.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"definizioneAllegatoId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			definizioneAllegatoLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			DefinizioneAllegato.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"definizioneAllegatoId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			definizioneAllegatoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DefinizioneAllegato.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"definizioneAllegatoId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<DefinizioneAllegato>() {

				@Override
				public void performAction(
						DefinizioneAllegato definizioneAllegato)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, definizioneAllegato);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					DefinizioneAllegato.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return definizioneAllegatoPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return definizioneAllegatoLocalService.deleteDefinizioneAllegato(
			(DefinizioneAllegato)persistedModel);
	}

	@Override
	public BasePersistence<DefinizioneAllegato> getBasePersistence() {
		return definizioneAllegatoPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return definizioneAllegatoPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the definizione allegatos matching the UUID and company.
	 *
	 * @param uuid the UUID of the definizione allegatos
	 * @param companyId the primary key of the company
	 * @return the matching definizione allegatos, or an empty list if no matches were found
	 */
	@Override
	public List<DefinizioneAllegato> getDefinizioneAllegatosByUuidAndCompanyId(
		String uuid, long companyId) {

		return definizioneAllegatoPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of definizione allegatos matching the UUID and company.
	 *
	 * @param uuid the UUID of the definizione allegatos
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of definizione allegatos
	 * @param end the upper bound of the range of definizione allegatos (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching definizione allegatos, or an empty list if no matches were found
	 */
	@Override
	public List<DefinizioneAllegato> getDefinizioneAllegatosByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<DefinizioneAllegato> orderByComparator) {

		return definizioneAllegatoPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the definizione allegato matching the UUID and group.
	 *
	 * @param uuid the definizione allegato's UUID
	 * @param groupId the primary key of the group
	 * @return the matching definizione allegato
	 * @throws PortalException if a matching definizione allegato could not be found
	 */
	@Override
	public DefinizioneAllegato getDefinizioneAllegatoByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return definizioneAllegatoPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the definizione allegatos.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.gestioneforms.model.impl.DefinizioneAllegatoModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of definizione allegatos
	 * @param end the upper bound of the range of definizione allegatos (not inclusive)
	 * @return the range of definizione allegatos
	 */
	@Override
	public List<DefinizioneAllegato> getDefinizioneAllegatos(
		int start, int end) {

		return definizioneAllegatoPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of definizione allegatos.
	 *
	 * @return the number of definizione allegatos
	 */
	@Override
	public int getDefinizioneAllegatosCount() {
		return definizioneAllegatoPersistence.countAll();
	}

	/**
	 * Updates the definizione allegato in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DefinizioneAllegatoLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param definizioneAllegato the definizione allegato
	 * @return the definizione allegato that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DefinizioneAllegato updateDefinizioneAllegato(
		DefinizioneAllegato definizioneAllegato) {

		return definizioneAllegatoPersistence.update(definizioneAllegato);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DefinizioneAllegatoLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		definizioneAllegatoLocalService =
			(DefinizioneAllegatoLocalService)aopProxy;

		_setLocalServiceUtilService(definizioneAllegatoLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DefinizioneAllegatoLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DefinizioneAllegato.class;
	}

	protected String getModelClassName() {
		return DefinizioneAllegato.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				definizioneAllegatoPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		DefinizioneAllegatoLocalService definizioneAllegatoLocalService) {

		try {
			Field field =
				DefinizioneAllegatoLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, definizioneAllegatoLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected DefinizioneAllegatoLocalService definizioneAllegatoLocalService;

	@Reference
	protected DefinizioneAllegatoPersistence definizioneAllegatoPersistence;

	@Reference
	protected FormPersistence formPersistence;

	@Reference
	protected FormFinder formFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}