/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.accreditamentoenti.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import it.servizidigitali.accreditamentoenti.model.ResponsabileEnte;
import it.servizidigitali.accreditamentoenti.service.ResponsabileEnteLocalService;
import it.servizidigitali.accreditamentoenti.service.ResponsabileEnteLocalServiceUtil;
import it.servizidigitali.accreditamentoenti.service.persistence.EntePersistence;
import it.servizidigitali.accreditamentoenti.service.persistence.ResponsabileEntePersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the responsabile ente local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.servizidigitali.accreditamentoenti.service.impl.ResponsabileEnteLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see it.servizidigitali.accreditamentoenti.service.impl.ResponsabileEnteLocalServiceImpl
 * @generated
 */
public abstract class ResponsabileEnteLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   ResponsabileEnteLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ResponsabileEnteLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ResponsabileEnteLocalServiceUtil</code>.
	 */

	/**
	 * Adds the responsabile ente to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ResponsabileEnteLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param responsabileEnte the responsabile ente
	 * @return the responsabile ente that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ResponsabileEnte addResponsabileEnte(
		ResponsabileEnte responsabileEnte) {

		responsabileEnte.setNew(true);

		return responsabileEntePersistence.update(responsabileEnte);
	}

	/**
	 * Creates a new responsabile ente with the primary key. Does not add the responsabile ente to the database.
	 *
	 * @param responsabileEnteId the primary key for the new responsabile ente
	 * @return the new responsabile ente
	 */
	@Override
	@Transactional(enabled = false)
	public ResponsabileEnte createResponsabileEnte(long responsabileEnteId) {
		return responsabileEntePersistence.create(responsabileEnteId);
	}

	/**
	 * Deletes the responsabile ente with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ResponsabileEnteLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param responsabileEnteId the primary key of the responsabile ente
	 * @return the responsabile ente that was removed
	 * @throws PortalException if a responsabile ente with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ResponsabileEnte deleteResponsabileEnte(long responsabileEnteId)
		throws PortalException {

		return responsabileEntePersistence.remove(responsabileEnteId);
	}

	/**
	 * Deletes the responsabile ente from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ResponsabileEnteLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param responsabileEnte the responsabile ente
	 * @return the responsabile ente that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ResponsabileEnte deleteResponsabileEnte(
		ResponsabileEnte responsabileEnte) {

		return responsabileEntePersistence.remove(responsabileEnte);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return responsabileEntePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ResponsabileEnte.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return responsabileEntePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.accreditamentoenti.model.impl.ResponsabileEnteModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return responsabileEntePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.accreditamentoenti.model.impl.ResponsabileEnteModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return responsabileEntePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return responsabileEntePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return responsabileEntePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ResponsabileEnte fetchResponsabileEnte(long responsabileEnteId) {
		return responsabileEntePersistence.fetchByPrimaryKey(
			responsabileEnteId);
	}

	/**
	 * Returns the responsabile ente matching the UUID and group.
	 *
	 * @param uuid the responsabile ente's UUID
	 * @param groupId the primary key of the group
	 * @return the matching responsabile ente, or <code>null</code> if a matching responsabile ente could not be found
	 */
	@Override
	public ResponsabileEnte fetchResponsabileEnteByUuidAndGroupId(
		String uuid, long groupId) {

		return responsabileEntePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the responsabile ente with the primary key.
	 *
	 * @param responsabileEnteId the primary key of the responsabile ente
	 * @return the responsabile ente
	 * @throws PortalException if a responsabile ente with the primary key could not be found
	 */
	@Override
	public ResponsabileEnte getResponsabileEnte(long responsabileEnteId)
		throws PortalException {

		return responsabileEntePersistence.findByPrimaryKey(responsabileEnteId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			responsabileEnteLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ResponsabileEnte.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("responsabileEnteId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			responsabileEnteLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ResponsabileEnte.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"responsabileEnteId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			responsabileEnteLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ResponsabileEnte.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("responsabileEnteId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<ResponsabileEnte>() {

				@Override
				public void performAction(ResponsabileEnte responsabileEnte)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, responsabileEnte);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(ResponsabileEnte.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return responsabileEntePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return responsabileEnteLocalService.deleteResponsabileEnte(
			(ResponsabileEnte)persistedModel);
	}

	@Override
	public BasePersistence<ResponsabileEnte> getBasePersistence() {
		return responsabileEntePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return responsabileEntePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the responsabile entes matching the UUID and company.
	 *
	 * @param uuid the UUID of the responsabile entes
	 * @param companyId the primary key of the company
	 * @return the matching responsabile entes, or an empty list if no matches were found
	 */
	@Override
	public List<ResponsabileEnte> getResponsabileEntesByUuidAndCompanyId(
		String uuid, long companyId) {

		return responsabileEntePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of responsabile entes matching the UUID and company.
	 *
	 * @param uuid the UUID of the responsabile entes
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of responsabile entes
	 * @param end the upper bound of the range of responsabile entes (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching responsabile entes, or an empty list if no matches were found
	 */
	@Override
	public List<ResponsabileEnte> getResponsabileEntesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<ResponsabileEnte> orderByComparator) {

		return responsabileEntePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the responsabile ente matching the UUID and group.
	 *
	 * @param uuid the responsabile ente's UUID
	 * @param groupId the primary key of the group
	 * @return the matching responsabile ente
	 * @throws PortalException if a matching responsabile ente could not be found
	 */
	@Override
	public ResponsabileEnte getResponsabileEnteByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return responsabileEntePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the responsabile entes.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.accreditamentoenti.model.impl.ResponsabileEnteModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of responsabile entes
	 * @param end the upper bound of the range of responsabile entes (not inclusive)
	 * @return the range of responsabile entes
	 */
	@Override
	public List<ResponsabileEnte> getResponsabileEntes(int start, int end) {
		return responsabileEntePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of responsabile entes.
	 *
	 * @return the number of responsabile entes
	 */
	@Override
	public int getResponsabileEntesCount() {
		return responsabileEntePersistence.countAll();
	}

	/**
	 * Updates the responsabile ente in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ResponsabileEnteLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param responsabileEnte the responsabile ente
	 * @return the responsabile ente that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ResponsabileEnte updateResponsabileEnte(
		ResponsabileEnte responsabileEnte) {

		return responsabileEntePersistence.update(responsabileEnte);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ResponsabileEnteLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		responsabileEnteLocalService = (ResponsabileEnteLocalService)aopProxy;

		_setLocalServiceUtilService(responsabileEnteLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ResponsabileEnteLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ResponsabileEnte.class;
	}

	protected String getModelClassName() {
		return ResponsabileEnte.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = responsabileEntePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		ResponsabileEnteLocalService responsabileEnteLocalService) {

		try {
			Field field =
				ResponsabileEnteLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, responsabileEnteLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected EntePersistence entePersistence;

	protected ResponsabileEnteLocalService responsabileEnteLocalService;

	@Reference
	protected ResponsabileEntePersistence responsabileEntePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}