/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.common.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.servizidigitali.common.model.ComuneEstero;
import it.servizidigitali.common.model.ComuneEsteroModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ComuneEstero service. Represents a row in the &quot;comune_estero&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ComuneEsteroModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ComuneEsteroImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ComuneEsteroImpl
 * @generated
 */
public class ComuneEsteroModelImpl
	extends BaseModelImpl<ComuneEstero> implements ComuneEsteroModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a comune estero model instance should use the <code>ComuneEstero</code> interface instead.
	 */
	public static final String TABLE_NAME = "comune_estero";

	public static final Object[][] TABLE_COLUMNS = {
		{"comuneEsteroId", Types.BIGINT}, {"codice", Types.INTEGER},
		{"denominazione", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("comuneEsteroId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("codice", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("denominazione", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table comune_estero (comuneEsteroId LONG not null primary key,codice INTEGER,denominazione VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table comune_estero";

	public static final String ORDER_BY_JPQL =
		" ORDER BY comuneEstero.denominazione ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY comune_estero.denominazione ASC";

	public static final String DATA_SOURCE = "servizidigitaliDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CODICE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DENOMINAZIONE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ComuneEsteroModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _comuneEsteroId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setComuneEsteroId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _comuneEsteroId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ComuneEstero.class;
	}

	@Override
	public String getModelClassName() {
		return ComuneEstero.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ComuneEstero, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ComuneEstero, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ComuneEstero, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ComuneEstero)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ComuneEstero, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ComuneEstero, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ComuneEstero)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ComuneEstero, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ComuneEstero, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ComuneEstero>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ComuneEstero.class.getClassLoader(), ComuneEstero.class,
			ModelWrapper.class);

		try {
			Constructor<ComuneEstero> constructor =
				(Constructor<ComuneEstero>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ComuneEstero, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ComuneEstero, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ComuneEstero, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ComuneEstero, Object>>();
		Map<String, BiConsumer<ComuneEstero, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ComuneEstero, ?>>();

		attributeGetterFunctions.put(
			"comuneEsteroId", ComuneEstero::getComuneEsteroId);
		attributeSetterBiConsumers.put(
			"comuneEsteroId",
			(BiConsumer<ComuneEstero, Long>)ComuneEstero::setComuneEsteroId);
		attributeGetterFunctions.put("codice", ComuneEstero::getCodice);
		attributeSetterBiConsumers.put(
			"codice",
			(BiConsumer<ComuneEstero, Integer>)ComuneEstero::setCodice);
		attributeGetterFunctions.put(
			"denominazione", ComuneEstero::getDenominazione);
		attributeSetterBiConsumers.put(
			"denominazione",
			(BiConsumer<ComuneEstero, String>)ComuneEstero::setDenominazione);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getComuneEsteroId() {
		return _comuneEsteroId;
	}

	@Override
	public void setComuneEsteroId(long comuneEsteroId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_comuneEsteroId = comuneEsteroId;
	}

	@Override
	public int getCodice() {
		return _codice;
	}

	@Override
	public void setCodice(int codice) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_codice = codice;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalCodice() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("codice"));
	}

	@Override
	public String getDenominazione() {
		if (_denominazione == null) {
			return "";
		}
		else {
			return _denominazione;
		}
	}

	@Override
	public void setDenominazione(String denominazione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_denominazione = denominazione;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDenominazione() {
		return getColumnOriginalValue("denominazione");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ComuneEstero.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ComuneEstero toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ComuneEstero>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ComuneEsteroImpl comuneEsteroImpl = new ComuneEsteroImpl();

		comuneEsteroImpl.setComuneEsteroId(getComuneEsteroId());
		comuneEsteroImpl.setCodice(getCodice());
		comuneEsteroImpl.setDenominazione(getDenominazione());

		comuneEsteroImpl.resetOriginalValues();

		return comuneEsteroImpl;
	}

	@Override
	public ComuneEstero cloneWithOriginalValues() {
		ComuneEsteroImpl comuneEsteroImpl = new ComuneEsteroImpl();

		comuneEsteroImpl.setComuneEsteroId(
			this.<Long>getColumnOriginalValue("comuneEsteroId"));
		comuneEsteroImpl.setCodice(
			this.<Integer>getColumnOriginalValue("codice"));
		comuneEsteroImpl.setDenominazione(
			this.<String>getColumnOriginalValue("denominazione"));

		return comuneEsteroImpl;
	}

	@Override
	public int compareTo(ComuneEstero comuneEstero) {
		int value = 0;

		value = getDenominazione().compareTo(comuneEstero.getDenominazione());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ComuneEstero)) {
			return false;
		}

		ComuneEstero comuneEstero = (ComuneEstero)object;

		long primaryKey = comuneEstero.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ComuneEstero> toCacheModel() {
		ComuneEsteroCacheModel comuneEsteroCacheModel =
			new ComuneEsteroCacheModel();

		comuneEsteroCacheModel.comuneEsteroId = getComuneEsteroId();

		comuneEsteroCacheModel.codice = getCodice();

		comuneEsteroCacheModel.denominazione = getDenominazione();

		String denominazione = comuneEsteroCacheModel.denominazione;

		if ((denominazione != null) && (denominazione.length() == 0)) {
			comuneEsteroCacheModel.denominazione = null;
		}

		return comuneEsteroCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ComuneEstero, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ComuneEstero, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ComuneEstero, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ComuneEstero)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ComuneEstero, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ComuneEstero, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ComuneEstero, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ComuneEstero)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ComuneEstero>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _comuneEsteroId;
	private int _codice;
	private String _denominazione;

	public <T> T getColumnValue(String columnName) {
		Function<ComuneEstero, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ComuneEstero)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("comuneEsteroId", _comuneEsteroId);
		_columnOriginalValues.put("codice", _codice);
		_columnOriginalValues.put("denominazione", _denominazione);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("comuneEsteroId", 1L);

		columnBitmasks.put("codice", 2L);

		columnBitmasks.put("denominazione", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ComuneEstero _escapedModel;

}