/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneenti.model.impl;

import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.servizidigitali.gestioneenti.model.EnteServizio;
import it.servizidigitali.gestioneenti.model.EnteServizioModel;
import it.servizidigitali.gestioneenti.service.persistence.EnteServizioPK;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EnteServizio service. Represents a row in the &quot;ente_servizio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EnteServizioModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EnteServizioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EnteServizioImpl
 * @generated
 */
public class EnteServizioModelImpl
	extends BaseModelImpl<EnteServizio> implements EnteServizioModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ente servizio model instance should use the <code>EnteServizio</code> interface instead.
	 */
	public static final String TABLE_NAME = "ente_servizio";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"organizationId", Types.BIGINT},
		{"servizioId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"uri", Types.VARCHAR},
		{"uriGuest", Types.VARCHAR}, {"uriScheda", Types.VARCHAR},
		{"autenticazione", Types.BOOLEAN},
		{"dataInizioAttivazione", Types.TIMESTAMP},
		{"dataFineAttivazione", Types.TIMESTAMP}, {"cittadino", Types.BOOLEAN},
		{"azienda", Types.BOOLEAN}, {"delega", Types.BOOLEAN},
		{"chatbot", Types.BOOLEAN}, {"prenotabile", Types.BOOLEAN},
		{"privacyDelega", Types.BOOLEAN}, {"allegatoDelega", Types.BOOLEAN},
		{"timbroCertificato", Types.BOOLEAN}, {"iseeInps", Types.BOOLEAN},
		{"attivo", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("organizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("servizioId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uri", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("uriGuest", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("uriScheda", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("autenticazione", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("dataInizioAttivazione", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataFineAttivazione", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("cittadino", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("azienda", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("delega", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("chatbot", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("prenotabile", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("privacyDelega", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("allegatoDelega", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("timbroCertificato", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("iseeInps", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("attivo", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ente_servizio (uuid_ VARCHAR(75) null,organizationId LONG not null,servizioId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,uri VARCHAR(75) null,uriGuest VARCHAR(75) null,uriScheda VARCHAR(75) null,autenticazione BOOLEAN,dataInizioAttivazione DATE null,dataFineAttivazione DATE null,cittadino BOOLEAN,azienda BOOLEAN,delega BOOLEAN,chatbot BOOLEAN,prenotabile BOOLEAN,privacyDelega BOOLEAN,allegatoDelega BOOLEAN,timbroCertificato BOOLEAN,iseeInps BOOLEAN,attivo BOOLEAN,primary key (organizationId, servizioId))";

	public static final String TABLE_SQL_DROP = "drop table ente_servizio";

	public static final String ORDER_BY_JPQL =
		" ORDER BY enteServizio.id.organizationId ASC, enteServizio.id.servizioId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ente_servizio.organizationId ASC, ente_servizio.servizioId ASC";

	public static final String DATA_SOURCE = "servizidigitaliDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ORGANIZATIONID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SERVIZIOID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EnteServizioModelImpl() {
	}

	@Override
	public EnteServizioPK getPrimaryKey() {
		return new EnteServizioPK(_organizationId, _servizioId);
	}

	@Override
	public void setPrimaryKey(EnteServizioPK primaryKey) {
		setOrganizationId(primaryKey.organizationId);
		setServizioId(primaryKey.servizioId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new EnteServizioPK(_organizationId, _servizioId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((EnteServizioPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return EnteServizio.class;
	}

	@Override
	public String getModelClassName() {
		return EnteServizio.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EnteServizio, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EnteServizio, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EnteServizio, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EnteServizio)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EnteServizio, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EnteServizio, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EnteServizio)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EnteServizio, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EnteServizio, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EnteServizio>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EnteServizio.class.getClassLoader(), EnteServizio.class,
			ModelWrapper.class);

		try {
			Constructor<EnteServizio> constructor =
				(Constructor<EnteServizio>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EnteServizio, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EnteServizio, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EnteServizio, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<EnteServizio, Object>>();
		Map<String, BiConsumer<EnteServizio, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EnteServizio, ?>>();

		attributeGetterFunctions.put("uuid", EnteServizio::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<EnteServizio, String>)EnteServizio::setUuid);
		attributeGetterFunctions.put(
			"organizationId", EnteServizio::getOrganizationId);
		attributeSetterBiConsumers.put(
			"organizationId",
			(BiConsumer<EnteServizio, Long>)EnteServizio::setOrganizationId);
		attributeGetterFunctions.put("servizioId", EnteServizio::getServizioId);
		attributeSetterBiConsumers.put(
			"servizioId",
			(BiConsumer<EnteServizio, Long>)EnteServizio::setServizioId);
		attributeGetterFunctions.put("groupId", EnteServizio::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EnteServizio, Long>)EnteServizio::setGroupId);
		attributeGetterFunctions.put("companyId", EnteServizio::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EnteServizio, Long>)EnteServizio::setCompanyId);
		attributeGetterFunctions.put("userId", EnteServizio::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<EnteServizio, Long>)EnteServizio::setUserId);
		attributeGetterFunctions.put("userName", EnteServizio::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EnteServizio, String>)EnteServizio::setUserName);
		attributeGetterFunctions.put("createDate", EnteServizio::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EnteServizio, Date>)EnteServizio::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EnteServizio::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EnteServizio, Date>)EnteServizio::setModifiedDate);
		attributeGetterFunctions.put("uri", EnteServizio::getUri);
		attributeSetterBiConsumers.put(
			"uri", (BiConsumer<EnteServizio, String>)EnteServizio::setUri);
		attributeGetterFunctions.put("uriGuest", EnteServizio::getUriGuest);
		attributeSetterBiConsumers.put(
			"uriGuest",
			(BiConsumer<EnteServizio, String>)EnteServizio::setUriGuest);
		attributeGetterFunctions.put("uriScheda", EnteServizio::getUriScheda);
		attributeSetterBiConsumers.put(
			"uriScheda",
			(BiConsumer<EnteServizio, String>)EnteServizio::setUriScheda);
		attributeGetterFunctions.put(
			"autenticazione", EnteServizio::getAutenticazione);
		attributeSetterBiConsumers.put(
			"autenticazione",
			(BiConsumer<EnteServizio, Boolean>)EnteServizio::setAutenticazione);
		attributeGetterFunctions.put(
			"dataInizioAttivazione", EnteServizio::getDataInizioAttivazione);
		attributeSetterBiConsumers.put(
			"dataInizioAttivazione",
			(BiConsumer<EnteServizio, Date>)
				EnteServizio::setDataInizioAttivazione);
		attributeGetterFunctions.put(
			"dataFineAttivazione", EnteServizio::getDataFineAttivazione);
		attributeSetterBiConsumers.put(
			"dataFineAttivazione",
			(BiConsumer<EnteServizio, Date>)
				EnteServizio::setDataFineAttivazione);
		attributeGetterFunctions.put("cittadino", EnteServizio::getCittadino);
		attributeSetterBiConsumers.put(
			"cittadino",
			(BiConsumer<EnteServizio, Boolean>)EnteServizio::setCittadino);
		attributeGetterFunctions.put("azienda", EnteServizio::getAzienda);
		attributeSetterBiConsumers.put(
			"azienda",
			(BiConsumer<EnteServizio, Boolean>)EnteServizio::setAzienda);
		attributeGetterFunctions.put("delega", EnteServizio::getDelega);
		attributeSetterBiConsumers.put(
			"delega",
			(BiConsumer<EnteServizio, Boolean>)EnteServizio::setDelega);
		attributeGetterFunctions.put("chatbot", EnteServizio::getChatbot);
		attributeSetterBiConsumers.put(
			"chatbot",
			(BiConsumer<EnteServizio, Boolean>)EnteServizio::setChatbot);
		attributeGetterFunctions.put(
			"prenotabile", EnteServizio::getPrenotabile);
		attributeSetterBiConsumers.put(
			"prenotabile",
			(BiConsumer<EnteServizio, Boolean>)EnteServizio::setPrenotabile);
		attributeGetterFunctions.put(
			"privacyDelega", EnteServizio::getPrivacyDelega);
		attributeSetterBiConsumers.put(
			"privacyDelega",
			(BiConsumer<EnteServizio, Boolean>)EnteServizio::setPrivacyDelega);
		attributeGetterFunctions.put(
			"allegatoDelega", EnteServizio::getAllegatoDelega);
		attributeSetterBiConsumers.put(
			"allegatoDelega",
			(BiConsumer<EnteServizio, Boolean>)EnteServizio::setAllegatoDelega);
		attributeGetterFunctions.put(
			"timbroCertificato", EnteServizio::getTimbroCertificato);
		attributeSetterBiConsumers.put(
			"timbroCertificato",
			(BiConsumer<EnteServizio, Boolean>)
				EnteServizio::setTimbroCertificato);
		attributeGetterFunctions.put("iseeInps", EnteServizio::getIseeInps);
		attributeSetterBiConsumers.put(
			"iseeInps",
			(BiConsumer<EnteServizio, Boolean>)EnteServizio::setIseeInps);
		attributeGetterFunctions.put("attivo", EnteServizio::getAttivo);
		attributeSetterBiConsumers.put(
			"attivo",
			(BiConsumer<EnteServizio, Boolean>)EnteServizio::setAttivo);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_organizationId = organizationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalOrganizationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("organizationId"));
	}

	@Override
	public long getServizioId() {
		return _servizioId;
	}

	@Override
	public void setServizioId(long servizioId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_servizioId = servizioId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalServizioId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("servizioId"));
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getUri() {
		if (_uri == null) {
			return "";
		}
		else {
			return _uri;
		}
	}

	@Override
	public void setUri(String uri) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uri = uri;
	}

	@Override
	public String getUriGuest() {
		if (_uriGuest == null) {
			return "";
		}
		else {
			return _uriGuest;
		}
	}

	@Override
	public void setUriGuest(String uriGuest) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uriGuest = uriGuest;
	}

	@Override
	public String getUriScheda() {
		if (_uriScheda == null) {
			return "";
		}
		else {
			return _uriScheda;
		}
	}

	@Override
	public void setUriScheda(String uriScheda) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uriScheda = uriScheda;
	}

	@Override
	public boolean getAutenticazione() {
		return _autenticazione;
	}

	@Override
	public boolean isAutenticazione() {
		return _autenticazione;
	}

	@Override
	public void setAutenticazione(boolean autenticazione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_autenticazione = autenticazione;
	}

	@Override
	public Date getDataInizioAttivazione() {
		return _dataInizioAttivazione;
	}

	@Override
	public void setDataInizioAttivazione(Date dataInizioAttivazione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataInizioAttivazione = dataInizioAttivazione;
	}

	@Override
	public Date getDataFineAttivazione() {
		return _dataFineAttivazione;
	}

	@Override
	public void setDataFineAttivazione(Date dataFineAttivazione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataFineAttivazione = dataFineAttivazione;
	}

	@Override
	public boolean getCittadino() {
		return _cittadino;
	}

	@Override
	public boolean isCittadino() {
		return _cittadino;
	}

	@Override
	public void setCittadino(boolean cittadino) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cittadino = cittadino;
	}

	@Override
	public boolean getAzienda() {
		return _azienda;
	}

	@Override
	public boolean isAzienda() {
		return _azienda;
	}

	@Override
	public void setAzienda(boolean azienda) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_azienda = azienda;
	}

	@Override
	public boolean getDelega() {
		return _delega;
	}

	@Override
	public boolean isDelega() {
		return _delega;
	}

	@Override
	public void setDelega(boolean delega) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_delega = delega;
	}

	@Override
	public boolean getChatbot() {
		return _chatbot;
	}

	@Override
	public boolean isChatbot() {
		return _chatbot;
	}

	@Override
	public void setChatbot(boolean chatbot) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_chatbot = chatbot;
	}

	@Override
	public boolean getPrenotabile() {
		return _prenotabile;
	}

	@Override
	public boolean isPrenotabile() {
		return _prenotabile;
	}

	@Override
	public void setPrenotabile(boolean prenotabile) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_prenotabile = prenotabile;
	}

	@Override
	public boolean getPrivacyDelega() {
		return _privacyDelega;
	}

	@Override
	public boolean isPrivacyDelega() {
		return _privacyDelega;
	}

	@Override
	public void setPrivacyDelega(boolean privacyDelega) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_privacyDelega = privacyDelega;
	}

	@Override
	public boolean getAllegatoDelega() {
		return _allegatoDelega;
	}

	@Override
	public boolean isAllegatoDelega() {
		return _allegatoDelega;
	}

	@Override
	public void setAllegatoDelega(boolean allegatoDelega) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_allegatoDelega = allegatoDelega;
	}

	@Override
	public boolean getTimbroCertificato() {
		return _timbroCertificato;
	}

	@Override
	public boolean isTimbroCertificato() {
		return _timbroCertificato;
	}

	@Override
	public void setTimbroCertificato(boolean timbroCertificato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_timbroCertificato = timbroCertificato;
	}

	@Override
	public boolean getIseeInps() {
		return _iseeInps;
	}

	@Override
	public boolean isIseeInps() {
		return _iseeInps;
	}

	@Override
	public void setIseeInps(boolean iseeInps) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_iseeInps = iseeInps;
	}

	@Override
	public boolean getAttivo() {
		return _attivo;
	}

	@Override
	public boolean isAttivo() {
		return _attivo;
	}

	@Override
	public void setAttivo(boolean attivo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_attivo = attivo;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EnteServizio.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public EnteServizio toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EnteServizio>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EnteServizioImpl enteServizioImpl = new EnteServizioImpl();

		enteServizioImpl.setUuid(getUuid());
		enteServizioImpl.setOrganizationId(getOrganizationId());
		enteServizioImpl.setServizioId(getServizioId());
		enteServizioImpl.setGroupId(getGroupId());
		enteServizioImpl.setCompanyId(getCompanyId());
		enteServizioImpl.setUserId(getUserId());
		enteServizioImpl.setUserName(getUserName());
		enteServizioImpl.setCreateDate(getCreateDate());
		enteServizioImpl.setModifiedDate(getModifiedDate());
		enteServizioImpl.setUri(getUri());
		enteServizioImpl.setUriGuest(getUriGuest());
		enteServizioImpl.setUriScheda(getUriScheda());
		enteServizioImpl.setAutenticazione(isAutenticazione());
		enteServizioImpl.setDataInizioAttivazione(getDataInizioAttivazione());
		enteServizioImpl.setDataFineAttivazione(getDataFineAttivazione());
		enteServizioImpl.setCittadino(isCittadino());
		enteServizioImpl.setAzienda(isAzienda());
		enteServizioImpl.setDelega(isDelega());
		enteServizioImpl.setChatbot(isChatbot());
		enteServizioImpl.setPrenotabile(isPrenotabile());
		enteServizioImpl.setPrivacyDelega(isPrivacyDelega());
		enteServizioImpl.setAllegatoDelega(isAllegatoDelega());
		enteServizioImpl.setTimbroCertificato(isTimbroCertificato());
		enteServizioImpl.setIseeInps(isIseeInps());
		enteServizioImpl.setAttivo(isAttivo());

		enteServizioImpl.resetOriginalValues();

		return enteServizioImpl;
	}

	@Override
	public EnteServizio cloneWithOriginalValues() {
		EnteServizioImpl enteServizioImpl = new EnteServizioImpl();

		enteServizioImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		enteServizioImpl.setOrganizationId(
			this.<Long>getColumnOriginalValue("organizationId"));
		enteServizioImpl.setServizioId(
			this.<Long>getColumnOriginalValue("servizioId"));
		enteServizioImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		enteServizioImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		enteServizioImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		enteServizioImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		enteServizioImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		enteServizioImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		enteServizioImpl.setUri(this.<String>getColumnOriginalValue("uri"));
		enteServizioImpl.setUriGuest(
			this.<String>getColumnOriginalValue("uriGuest"));
		enteServizioImpl.setUriScheda(
			this.<String>getColumnOriginalValue("uriScheda"));
		enteServizioImpl.setAutenticazione(
			this.<Boolean>getColumnOriginalValue("autenticazione"));
		enteServizioImpl.setDataInizioAttivazione(
			this.<Date>getColumnOriginalValue("dataInizioAttivazione"));
		enteServizioImpl.setDataFineAttivazione(
			this.<Date>getColumnOriginalValue("dataFineAttivazione"));
		enteServizioImpl.setCittadino(
			this.<Boolean>getColumnOriginalValue("cittadino"));
		enteServizioImpl.setAzienda(
			this.<Boolean>getColumnOriginalValue("azienda"));
		enteServizioImpl.setDelega(
			this.<Boolean>getColumnOriginalValue("delega"));
		enteServizioImpl.setChatbot(
			this.<Boolean>getColumnOriginalValue("chatbot"));
		enteServizioImpl.setPrenotabile(
			this.<Boolean>getColumnOriginalValue("prenotabile"));
		enteServizioImpl.setPrivacyDelega(
			this.<Boolean>getColumnOriginalValue("privacyDelega"));
		enteServizioImpl.setAllegatoDelega(
			this.<Boolean>getColumnOriginalValue("allegatoDelega"));
		enteServizioImpl.setTimbroCertificato(
			this.<Boolean>getColumnOriginalValue("timbroCertificato"));
		enteServizioImpl.setIseeInps(
			this.<Boolean>getColumnOriginalValue("iseeInps"));
		enteServizioImpl.setAttivo(
			this.<Boolean>getColumnOriginalValue("attivo"));

		return enteServizioImpl;
	}

	@Override
	public int compareTo(EnteServizio enteServizio) {
		EnteServizioPK primaryKey = enteServizio.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EnteServizio)) {
			return false;
		}

		EnteServizio enteServizio = (EnteServizio)object;

		EnteServizioPK primaryKey = enteServizio.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EnteServizio> toCacheModel() {
		EnteServizioCacheModel enteServizioCacheModel =
			new EnteServizioCacheModel();

		enteServizioCacheModel.enteServizioPK = getPrimaryKey();

		enteServizioCacheModel.uuid = getUuid();

		String uuid = enteServizioCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			enteServizioCacheModel.uuid = null;
		}

		enteServizioCacheModel.organizationId = getOrganizationId();

		enteServizioCacheModel.servizioId = getServizioId();

		enteServizioCacheModel.groupId = getGroupId();

		enteServizioCacheModel.companyId = getCompanyId();

		enteServizioCacheModel.userId = getUserId();

		enteServizioCacheModel.userName = getUserName();

		String userName = enteServizioCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			enteServizioCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			enteServizioCacheModel.createDate = createDate.getTime();
		}
		else {
			enteServizioCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			enteServizioCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			enteServizioCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		enteServizioCacheModel.uri = getUri();

		String uri = enteServizioCacheModel.uri;

		if ((uri != null) && (uri.length() == 0)) {
			enteServizioCacheModel.uri = null;
		}

		enteServizioCacheModel.uriGuest = getUriGuest();

		String uriGuest = enteServizioCacheModel.uriGuest;

		if ((uriGuest != null) && (uriGuest.length() == 0)) {
			enteServizioCacheModel.uriGuest = null;
		}

		enteServizioCacheModel.uriScheda = getUriScheda();

		String uriScheda = enteServizioCacheModel.uriScheda;

		if ((uriScheda != null) && (uriScheda.length() == 0)) {
			enteServizioCacheModel.uriScheda = null;
		}

		enteServizioCacheModel.autenticazione = isAutenticazione();

		Date dataInizioAttivazione = getDataInizioAttivazione();

		if (dataInizioAttivazione != null) {
			enteServizioCacheModel.dataInizioAttivazione =
				dataInizioAttivazione.getTime();
		}
		else {
			enteServizioCacheModel.dataInizioAttivazione = Long.MIN_VALUE;
		}

		Date dataFineAttivazione = getDataFineAttivazione();

		if (dataFineAttivazione != null) {
			enteServizioCacheModel.dataFineAttivazione =
				dataFineAttivazione.getTime();
		}
		else {
			enteServizioCacheModel.dataFineAttivazione = Long.MIN_VALUE;
		}

		enteServizioCacheModel.cittadino = isCittadino();

		enteServizioCacheModel.azienda = isAzienda();

		enteServizioCacheModel.delega = isDelega();

		enteServizioCacheModel.chatbot = isChatbot();

		enteServizioCacheModel.prenotabile = isPrenotabile();

		enteServizioCacheModel.privacyDelega = isPrivacyDelega();

		enteServizioCacheModel.allegatoDelega = isAllegatoDelega();

		enteServizioCacheModel.timbroCertificato = isTimbroCertificato();

		enteServizioCacheModel.iseeInps = isIseeInps();

		enteServizioCacheModel.attivo = isAttivo();

		return enteServizioCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EnteServizio, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EnteServizio, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EnteServizio, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((EnteServizio)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EnteServizio, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EnteServizio, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EnteServizio, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EnteServizio)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EnteServizio>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _organizationId;
	private long _servizioId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _uri;
	private String _uriGuest;
	private String _uriScheda;
	private boolean _autenticazione;
	private Date _dataInizioAttivazione;
	private Date _dataFineAttivazione;
	private boolean _cittadino;
	private boolean _azienda;
	private boolean _delega;
	private boolean _chatbot;
	private boolean _prenotabile;
	private boolean _privacyDelega;
	private boolean _allegatoDelega;
	private boolean _timbroCertificato;
	private boolean _iseeInps;
	private boolean _attivo;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EnteServizio, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EnteServizio)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("organizationId", _organizationId);
		_columnOriginalValues.put("servizioId", _servizioId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("uri", _uri);
		_columnOriginalValues.put("uriGuest", _uriGuest);
		_columnOriginalValues.put("uriScheda", _uriScheda);
		_columnOriginalValues.put("autenticazione", _autenticazione);
		_columnOriginalValues.put(
			"dataInizioAttivazione", _dataInizioAttivazione);
		_columnOriginalValues.put("dataFineAttivazione", _dataFineAttivazione);
		_columnOriginalValues.put("cittadino", _cittadino);
		_columnOriginalValues.put("azienda", _azienda);
		_columnOriginalValues.put("delega", _delega);
		_columnOriginalValues.put("chatbot", _chatbot);
		_columnOriginalValues.put("prenotabile", _prenotabile);
		_columnOriginalValues.put("privacyDelega", _privacyDelega);
		_columnOriginalValues.put("allegatoDelega", _allegatoDelega);
		_columnOriginalValues.put("timbroCertificato", _timbroCertificato);
		_columnOriginalValues.put("iseeInps", _iseeInps);
		_columnOriginalValues.put("attivo", _attivo);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("organizationId", 2L);

		columnBitmasks.put("servizioId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("uri", 512L);

		columnBitmasks.put("uriGuest", 1024L);

		columnBitmasks.put("uriScheda", 2048L);

		columnBitmasks.put("autenticazione", 4096L);

		columnBitmasks.put("dataInizioAttivazione", 8192L);

		columnBitmasks.put("dataFineAttivazione", 16384L);

		columnBitmasks.put("cittadino", 32768L);

		columnBitmasks.put("azienda", 65536L);

		columnBitmasks.put("delega", 131072L);

		columnBitmasks.put("chatbot", 262144L);

		columnBitmasks.put("prenotabile", 524288L);

		columnBitmasks.put("privacyDelega", 1048576L);

		columnBitmasks.put("allegatoDelega", 2097152L);

		columnBitmasks.put("timbroCertificato", 4194304L);

		columnBitmasks.put("iseeInps", 8388608L);

		columnBitmasks.put("attivo", 16777216L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EnteServizio _escapedModel;

}