/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestionecomunicazioni.model;

import com.liferay.portal.kernel.model.BaseModel;

import it.servizidigitali.gestionecomunicazioni.service.persistence.LetturaComunicazionePK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LetturaComunicazione service. Represents a row in the &quot;lettura_comunicazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.gestionecomunicazioni.model.impl.LetturaComunicazioneModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.gestionecomunicazioni.model.impl.LetturaComunicazioneImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LetturaComunicazione
 * @generated
 */
@ProviderType
public interface LetturaComunicazioneModel
	extends BaseModel<LetturaComunicazione> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lettura comunicazione model instance should use the {@link LetturaComunicazione} interface instead.
	 */

	/**
	 * Returns the primary key of this lettura comunicazione.
	 *
	 * @return the primary key of this lettura comunicazione
	 */
	public LetturaComunicazionePK getPrimaryKey();

	/**
	 * Sets the primary key of this lettura comunicazione.
	 *
	 * @param primaryKey the primary key of this lettura comunicazione
	 */
	public void setPrimaryKey(LetturaComunicazionePK primaryKey);

	/**
	 * Returns the comunicazione ID of this lettura comunicazione.
	 *
	 * @return the comunicazione ID of this lettura comunicazione
	 */
	public long getComunicazioneId();

	/**
	 * Sets the comunicazione ID of this lettura comunicazione.
	 *
	 * @param comunicazioneId the comunicazione ID of this lettura comunicazione
	 */
	public void setComunicazioneId(long comunicazioneId);

	/**
	 * Returns the user ID of this lettura comunicazione.
	 *
	 * @return the user ID of this lettura comunicazione
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lettura comunicazione.
	 *
	 * @param userId the user ID of this lettura comunicazione
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lettura comunicazione.
	 *
	 * @return the user uuid of this lettura comunicazione
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lettura comunicazione.
	 *
	 * @param userUuid the user uuid of this lettura comunicazione
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the data lettura of this lettura comunicazione.
	 *
	 * @return the data lettura of this lettura comunicazione
	 */
	public Date getDataLettura();

	/**
	 * Sets the data lettura of this lettura comunicazione.
	 *
	 * @param dataLettura the data lettura of this lettura comunicazione
	 */
	public void setDataLettura(Date dataLettura);

	@Override
	public LetturaComunicazione cloneWithOriginalValues();

}