/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestionecomunicazioni.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TipologiaComunicazione service. Represents a row in the &quot;tipologia_comunicazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.gestionecomunicazioni.model.impl.TipologiaComunicazioneModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.gestionecomunicazioni.model.impl.TipologiaComunicazioneImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TipologiaComunicazione
 * @generated
 */
@ProviderType
public interface TipologiaComunicazioneModel
	extends BaseModel<TipologiaComunicazione> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tipologia comunicazione model instance should use the {@link TipologiaComunicazione} interface instead.
	 */

	/**
	 * Returns the primary key of this tipologia comunicazione.
	 *
	 * @return the primary key of this tipologia comunicazione
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tipologia comunicazione.
	 *
	 * @param primaryKey the primary key of this tipologia comunicazione
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tipologia comunicazione ID of this tipologia comunicazione.
	 *
	 * @return the tipologia comunicazione ID of this tipologia comunicazione
	 */
	public long getTipologiaComunicazioneId();

	/**
	 * Sets the tipologia comunicazione ID of this tipologia comunicazione.
	 *
	 * @param tipologiaComunicazioneId the tipologia comunicazione ID of this tipologia comunicazione
	 */
	public void setTipologiaComunicazioneId(long tipologiaComunicazioneId);

	/**
	 * Returns the nome of this tipologia comunicazione.
	 *
	 * @return the nome of this tipologia comunicazione
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this tipologia comunicazione.
	 *
	 * @param nome the nome of this tipologia comunicazione
	 */
	public void setNome(String nome);

	@Override
	public TipologiaComunicazione cloneWithOriginalValues();

}