/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.gestioneservizi.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import it.servizidigitali.gestioneservizi.model.Tipologia;
import it.servizidigitali.gestioneservizi.service.TipologiaLocalService;
import it.servizidigitali.gestioneservizi.service.TipologiaLocalServiceUtil;
import it.servizidigitali.gestioneservizi.service.persistence.AreaTematicaPersistence;
import it.servizidigitali.gestioneservizi.service.persistence.ServizioFinder;
import it.servizidigitali.gestioneservizi.service.persistence.ServizioPersistence;
import it.servizidigitali.gestioneservizi.service.persistence.TipologiaPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the tipologia local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.servizidigitali.gestioneservizi.service.impl.TipologiaLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see it.servizidigitali.gestioneservizi.service.impl.TipologiaLocalServiceImpl
 * @generated
 */
public abstract class TipologiaLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, TipologiaLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>TipologiaLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>TipologiaLocalServiceUtil</code>.
	 */

	/**
	 * Adds the tipologia to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TipologiaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param tipologia the tipologia
	 * @return the tipologia that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Tipologia addTipologia(Tipologia tipologia) {
		tipologia.setNew(true);

		return tipologiaPersistence.update(tipologia);
	}

	/**
	 * Creates a new tipologia with the primary key. Does not add the tipologia to the database.
	 *
	 * @param tipologiaId the primary key for the new tipologia
	 * @return the new tipologia
	 */
	@Override
	@Transactional(enabled = false)
	public Tipologia createTipologia(long tipologiaId) {
		return tipologiaPersistence.create(tipologiaId);
	}

	/**
	 * Deletes the tipologia with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TipologiaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param tipologiaId the primary key of the tipologia
	 * @return the tipologia that was removed
	 * @throws PortalException if a tipologia with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Tipologia deleteTipologia(long tipologiaId) throws PortalException {
		return tipologiaPersistence.remove(tipologiaId);
	}

	/**
	 * Deletes the tipologia from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TipologiaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param tipologia the tipologia
	 * @return the tipologia that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Tipologia deleteTipologia(Tipologia tipologia) {
		return tipologiaPersistence.remove(tipologia);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return tipologiaPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Tipologia.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return tipologiaPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.gestioneservizi.model.impl.TipologiaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return tipologiaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.gestioneservizi.model.impl.TipologiaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return tipologiaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return tipologiaPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return tipologiaPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Tipologia fetchTipologia(long tipologiaId) {
		return tipologiaPersistence.fetchByPrimaryKey(tipologiaId);
	}

	/**
	 * Returns the tipologia matching the UUID and group.
	 *
	 * @param uuid the tipologia's UUID
	 * @param groupId the primary key of the group
	 * @return the matching tipologia, or <code>null</code> if a matching tipologia could not be found
	 */
	@Override
	public Tipologia fetchTipologiaByUuidAndGroupId(String uuid, long groupId) {
		return tipologiaPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the tipologia with the primary key.
	 *
	 * @param tipologiaId the primary key of the tipologia
	 * @return the tipologia
	 * @throws PortalException if a tipologia with the primary key could not be found
	 */
	@Override
	public Tipologia getTipologia(long tipologiaId) throws PortalException {
		return tipologiaPersistence.findByPrimaryKey(tipologiaId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(tipologiaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Tipologia.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("tipologiaId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			tipologiaLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Tipologia.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"tipologiaId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(tipologiaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Tipologia.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("tipologiaId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<Tipologia>() {

				@Override
				public void performAction(Tipologia tipologia)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, tipologia);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(Tipologia.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return tipologiaPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return tipologiaLocalService.deleteTipologia((Tipologia)persistedModel);
	}

	@Override
	public BasePersistence<Tipologia> getBasePersistence() {
		return tipologiaPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return tipologiaPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the tipologias matching the UUID and company.
	 *
	 * @param uuid the UUID of the tipologias
	 * @param companyId the primary key of the company
	 * @return the matching tipologias, or an empty list if no matches were found
	 */
	@Override
	public List<Tipologia> getTipologiasByUuidAndCompanyId(
		String uuid, long companyId) {

		return tipologiaPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of tipologias matching the UUID and company.
	 *
	 * @param uuid the UUID of the tipologias
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of tipologias
	 * @param end the upper bound of the range of tipologias (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching tipologias, or an empty list if no matches were found
	 */
	@Override
	public List<Tipologia> getTipologiasByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<Tipologia> orderByComparator) {

		return tipologiaPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the tipologia matching the UUID and group.
	 *
	 * @param uuid the tipologia's UUID
	 * @param groupId the primary key of the group
	 * @return the matching tipologia
	 * @throws PortalException if a matching tipologia could not be found
	 */
	@Override
	public Tipologia getTipologiaByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return tipologiaPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the tipologias.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.servizidigitali.gestioneservizi.model.impl.TipologiaModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of tipologias
	 * @param end the upper bound of the range of tipologias (not inclusive)
	 * @return the range of tipologias
	 */
	@Override
	public List<Tipologia> getTipologias(int start, int end) {
		return tipologiaPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of tipologias.
	 *
	 * @return the number of tipologias
	 */
	@Override
	public int getTipologiasCount() {
		return tipologiaPersistence.countAll();
	}

	/**
	 * Updates the tipologia in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TipologiaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param tipologia the tipologia
	 * @return the tipologia that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Tipologia updateTipologia(Tipologia tipologia) {
		return tipologiaPersistence.update(tipologia);
	}

	/**
	 */
	@Override
	public void addServizioTipologia(long servizioId, long tipologiaId) {
		servizioPersistence.addTipologia(servizioId, tipologiaId);
	}

	/**
	 */
	@Override
	public void addServizioTipologia(long servizioId, Tipologia tipologia) {
		servizioPersistence.addTipologia(servizioId, tipologia);
	}

	/**
	 */
	@Override
	public void addServizioTipologias(long servizioId, long[] tipologiaIds) {
		servizioPersistence.addTipologias(servizioId, tipologiaIds);
	}

	/**
	 */
	@Override
	public void addServizioTipologias(
		long servizioId, List<Tipologia> tipologias) {

		servizioPersistence.addTipologias(servizioId, tipologias);
	}

	/**
	 */
	@Override
	public void clearServizioTipologias(long servizioId) {
		servizioPersistence.clearTipologias(servizioId);
	}

	/**
	 */
	@Override
	public void deleteServizioTipologia(long servizioId, long tipologiaId) {
		servizioPersistence.removeTipologia(servizioId, tipologiaId);
	}

	/**
	 */
	@Override
	public void deleteServizioTipologia(long servizioId, Tipologia tipologia) {
		servizioPersistence.removeTipologia(servizioId, tipologia);
	}

	/**
	 */
	@Override
	public void deleteServizioTipologias(long servizioId, long[] tipologiaIds) {
		servizioPersistence.removeTipologias(servizioId, tipologiaIds);
	}

	/**
	 */
	@Override
	public void deleteServizioTipologias(
		long servizioId, List<Tipologia> tipologias) {

		servizioPersistence.removeTipologias(servizioId, tipologias);
	}

	/**
	 * Returns the servizioIds of the servizios associated with the tipologia.
	 *
	 * @param tipologiaId the tipologiaId of the tipologia
	 * @return long[] the servizioIds of servizios associated with the tipologia
	 */
	@Override
	public long[] getServizioPrimaryKeys(long tipologiaId) {
		return tipologiaPersistence.getServizioPrimaryKeys(tipologiaId);
	}

	/**
	 */
	@Override
	public List<Tipologia> getServizioTipologias(long servizioId) {
		return tipologiaPersistence.getServizioTipologias(servizioId);
	}

	/**
	 */
	@Override
	public List<Tipologia> getServizioTipologias(
		long servizioId, int start, int end) {

		return tipologiaPersistence.getServizioTipologias(
			servizioId, start, end);
	}

	/**
	 */
	@Override
	public List<Tipologia> getServizioTipologias(
		long servizioId, int start, int end,
		OrderByComparator<Tipologia> orderByComparator) {

		return tipologiaPersistence.getServizioTipologias(
			servizioId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getServizioTipologiasCount(long servizioId) {
		return servizioPersistence.getTipologiasSize(servizioId);
	}

	/**
	 */
	@Override
	public boolean hasServizioTipologia(long servizioId, long tipologiaId) {
		return servizioPersistence.containsTipologia(servizioId, tipologiaId);
	}

	/**
	 */
	@Override
	public boolean hasServizioTipologias(long servizioId) {
		return servizioPersistence.containsTipologias(servizioId);
	}

	/**
	 */
	@Override
	public void setServizioTipologias(long servizioId, long[] tipologiaIds) {
		servizioPersistence.setTipologias(servizioId, tipologiaIds);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			TipologiaLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		tipologiaLocalService = (TipologiaLocalService)aopProxy;

		_setLocalServiceUtilService(tipologiaLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return TipologiaLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Tipologia.class;
	}

	protected String getModelClassName() {
		return Tipologia.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = tipologiaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		TipologiaLocalService tipologiaLocalService) {

		try {
			Field field = TipologiaLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, tipologiaLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AreaTematicaPersistence areaTematicaPersistence;

	@Reference
	protected ServizioPersistence servizioPersistence;

	@Reference
	protected ServizioFinder servizioFinder;

	protected TipologiaLocalService tipologiaLocalService;

	@Reference
	protected TipologiaPersistence tipologiaPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}