/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.servizidigitali.common.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Provincia service. Represents a row in the &quot;provincia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.servizidigitali.common.model.impl.ProvinciaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.servizidigitali.common.model.impl.ProvinciaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Provincia
 * @generated
 */
@ProviderType
public interface ProvinciaModel extends BaseModel<Provincia> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a provincia model instance should use the {@link Provincia} interface instead.
	 */

	/**
	 * Returns the primary key of this provincia.
	 *
	 * @return the primary key of this provincia
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this provincia.
	 *
	 * @param primaryKey the primary key of this provincia
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the provincia ID of this provincia.
	 *
	 * @return the provincia ID of this provincia
	 */
	public long getProvinciaId();

	/**
	 * Sets the provincia ID of this provincia.
	 *
	 * @param provinciaId the provincia ID of this provincia
	 */
	public void setProvinciaId(long provinciaId);

	/**
	 * Returns the codice ripartizione of this provincia.
	 *
	 * @return the codice ripartizione of this provincia
	 */
	public int getCodiceRipartizione();

	/**
	 * Sets the codice ripartizione of this provincia.
	 *
	 * @param codiceRipartizione the codice ripartizione of this provincia
	 */
	public void setCodiceRipartizione(int codiceRipartizione);

	/**
	 * Returns the codice nuts1 of this provincia.
	 *
	 * @return the codice nuts1 of this provincia
	 */
	@AutoEscape
	public String getCodiceNUTS1();

	/**
	 * Sets the codice nuts1 of this provincia.
	 *
	 * @param codiceNUTS1 the codice nuts1 of this provincia
	 */
	public void setCodiceNUTS1(String codiceNUTS1);

	/**
	 * Returns the ripartizione geografica m of this provincia.
	 *
	 * @return the ripartizione geografica m of this provincia
	 */
	@AutoEscape
	public String getRipartizioneGeograficaM();

	/**
	 * Sets the ripartizione geografica m of this provincia.
	 *
	 * @param ripartizioneGeograficaM the ripartizione geografica m of this provincia
	 */
	public void setRipartizioneGeograficaM(String ripartizioneGeograficaM);

	/**
	 * Returns the ripartizione geografica of this provincia.
	 *
	 * @return the ripartizione geografica of this provincia
	 */
	@AutoEscape
	public String getRipartizioneGeografica();

	/**
	 * Sets the ripartizione geografica of this provincia.
	 *
	 * @param ripartizioneGeografica the ripartizione geografica of this provincia
	 */
	public void setRipartizioneGeografica(String ripartizioneGeografica);

	/**
	 * Returns the denominazione regione m of this provincia.
	 *
	 * @return the denominazione regione m of this provincia
	 */
	@AutoEscape
	public String getDenominazioneRegioneM();

	/**
	 * Sets the denominazione regione m of this provincia.
	 *
	 * @param denominazioneRegioneM the denominazione regione m of this provincia
	 */
	public void setDenominazioneRegioneM(String denominazioneRegioneM);

	/**
	 * Returns the denominazione regione of this provincia.
	 *
	 * @return the denominazione regione of this provincia
	 */
	@AutoEscape
	public String getDenominazioneRegione();

	/**
	 * Sets the denominazione regione of this provincia.
	 *
	 * @param denominazioneRegione the denominazione regione of this provincia
	 */
	public void setDenominazioneRegione(String denominazioneRegione);

	/**
	 * Returns the denominazione provincia of this provincia.
	 *
	 * @return the denominazione provincia of this provincia
	 */
	@AutoEscape
	public String getDenominazioneProvincia();

	/**
	 * Sets the denominazione provincia of this provincia.
	 *
	 * @param denominazioneProvincia the denominazione provincia of this provincia
	 */
	public void setDenominazioneProvincia(String denominazioneProvincia);

	/**
	 * Returns the codice regione of this provincia.
	 *
	 * @return the codice regione of this provincia
	 */
	public long getCodiceRegione();

	/**
	 * Sets the codice regione of this provincia.
	 *
	 * @param codiceRegione the codice regione of this provincia
	 */
	public void setCodiceRegione(long codiceRegione);

	/**
	 * Returns the codice nuts2 of this provincia.
	 *
	 * @return the codice nuts2 of this provincia
	 */
	@AutoEscape
	public String getCodiceNUTS2();

	/**
	 * Sets the codice nuts2 of this provincia.
	 *
	 * @param codiceNUTS2 the codice nuts2 of this provincia
	 */
	public void setCodiceNUTS2(String codiceNUTS2);

	/**
	 * Returns the codice nuts3 of this provincia.
	 *
	 * @return the codice nuts3 of this provincia
	 */
	@AutoEscape
	public String getCodiceNUTS3();

	/**
	 * Sets the codice nuts3 of this provincia.
	 *
	 * @param codiceNUTS3 the codice nuts3 of this provincia
	 */
	public void setCodiceNUTS3(String codiceNUTS3);

	/**
	 * Returns the sigla of this provincia.
	 *
	 * @return the sigla of this provincia
	 */
	@AutoEscape
	public String getSigla();

	/**
	 * Sets the sigla of this provincia.
	 *
	 * @param sigla the sigla of this provincia
	 */
	public void setSigla(String sigla);

	@Override
	public Provincia cloneWithOriginalValues();

}